docs(make-your-components-compatible-with-aao): add Asset Description in How to improve the compatibility
anatawa12/AvatarOptimizer pull request #1032
Opened 2024-04-29 07:33 UTC by anatawa12

Fixes #1024

2024-04-29 10:46 UTC, Sayamame-beans requested changes
部分的
反応後に英語確認します

2024-04-29 10:46 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +Avatar Optimizer v1.7.0以降では、ビルド時以降に処理を行わないコンポーネント向けに、[Asset Description]が追加されました。
```suggestion
Avatar Optimizer v1.7.0以降では、ビルド時に処理を行わないコンポーネント向けに[Asset Description]が追加されています。
```

2024-04-29 10:46 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +Avatar Optimizer v1.7.0以降では、ビルド時以降に処理を行わないコンポーネント向けに、[Asset Description]が追加されました。
「そのため、Avatar Optimizerに無視してほしい、ビルド時には意味のないコンポーネントを指定するためのシンプルな仕組みとして、Asset Descriptionがv1.7.0で追加されました。」より

2024-04-29 10:46 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +ビルド時に処理を行わないツールであればこちらを使用して登録することもできます。
```suggestion
ビルド時に処理を行わないようなツールであれば、こちらを利用して登録することもできます。
```

2024-04-29 10:46 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +ビルド時に処理を行うツールの場合、Asset Descriptionで登録する代わりにビルド時にコンポーネントを削除するのを推奨します。
```suggestion
ビルド時に何らかの処理を行うツールやコンポーネントの場合は、Asset Descriptionで登録するのではなく、ビルド時にコンポーネントを削除することを推奨します。
```

2024-04-29 10:46 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +ビルド時に処理を行うツールの場合、Asset Descriptionで登録する代わりにビルド時にコンポーネントを削除するのを推奨します。
ここ、前々の文と被ってるからちょっと考えた方が良いかも

2024-04-29 10:46 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +もしビルド処理の順番が意図しない順になった場合、Asset Descriptionで登録すると Avatar Optimizer がコンポーネントを削除してしまい、ツールが無効化される可能性があるためです。
```suggestion
これは、Asset Descriptionによる登録では、ビルド時の処理順が意図しないものになってしまった場合などにAvatar Optimizerがコンポーネントを削除してしまうことにより、ツールが正しく動作出来なくなる可能性があるためです。
```

2024-04-29 10:48 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +Avatar Optimizer v1.7.0以降では、ビルド時以降に処理を行わないコンポーネント向けに、[Asset Description]が追加されました。
一応ビルド時にとしてるけど、ビルド後のランタイム動きがあることをすごく稀に考えられはするのかなぁってこっちではその表記にしたけどまぁ揃えたほうがいいのかな

2024-04-29 11:16 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +ビルド時に処理を行うツールの場合、Asset Descriptionで登録する代わりにビルド時にコンポーネントを削除するのを推奨します。
そもそも削除に限らないから「追加するのは非推奨です」的な書き方にする？

2024-04-29 11:17 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +ビルド時に処理を行うツールの場合、Asset Descriptionで登録する代わりにビルド時にコンポーネントを削除するのを推奨します。
あ～

2024-04-29 11:18 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +Avatar Optimizer v1.7.0以降では、ビルド時以降に処理を行わないコンポーネント向けに、[Asset Description]が追加されました。
description側も書き換えるか

2024-04-29 11:24 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +Avatar Optimizer v1.7.0以降では、ビルド時以降に処理を行わないコンポーネント向けに、[Asset Description]が追加されました。
```suggestion
Avatar Optimizer v1.7.0以降では、ビルド時やランタイムで処理を行わないコンポーネント向けに[Asset Description]が追加されています。
```

2024-04-29 11:44 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +ビルド時に処理を行うツールの場合、Asset Descriptionで登録する代わりにビルド時にコンポーネントを削除するのを推奨します。
```suggestion
ビルド時に何らかの処理を行うツールやコンポーネントの場合は、Asset Descriptionで登録するのは非推奨です。
```

かな

2024-04-29 12:26 UTC, Sayamame-beans requested changes

2024-04-29 12:26 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +Since Avatar Optimizer v1.7.0, [Asset Description] is added for components that doesn't work on or after build time.
```suggestion
Since Avatar Optimizer v1.7.0, [Asset Description] is added for components that doesn't process during build time or runtime.
```

2024-04-29 12:26 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +you should remove components on the build time instead of registering with Asset Description.
```suggestion
```

2024-04-29 12:26 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +If your tool process something at build time,
```suggestion
If your tool process something at build time, registering with Asset Description is not recommended.
```

2024-04-29 12:26 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +This prevents Avatar Optimizer from accidentally removing components and disabling your tool when the execution order is unexpected.
```suggestion
This is to prevent Avatar Optimizer from accidentally removing components and causing your tool to not work properly when the processes execution order is unexpected/incorrect.
```

2024-04-29 12:58 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +Since Avatar Optimizer v1.7.0, [Asset Description] is added for components that doesn't work on or after build time.
なるほど(Asset Description側にduring buildとあったのでこうしてみてました)

2024-04-29 12:59 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +Since Avatar Optimizer v1.7.0, [Asset Description] is added for components that doesn't work on or after build time.
```suggestion
Since Avatar Optimizer v1.7.0, [Asset Description] is added for components that doesn't process on build or at runtime.
```

2024-04-29 13:01 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +This prevents Avatar Optimizer from accidentally removing components and disabling your tool when the execution order is unexpected.
this prevets~のほうが聞く気がする.

2024-04-29 13:03 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +This prevents Avatar Optimizer from accidentally removing components and disabling your tool when the execution order is unexpected.
前文全体をpreventsの主語にするにはどこかしっくり来ない気がして変えてました
This preventsでも大丈夫ではあると思います

2024-04-29 14:13 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +This prevents Avatar Optimizer from accidentally removing components and disabling your tool when the execution order is unexpected.
bdちゃんに聞いて変わらんとのことなのでThis preventsでいきます

2024-04-30 03:30 UTC, Sayamame-beans requested changes

2024-04-30 03:30 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、Avatar Optimizerに無視してほしい、ビルド時やランタイムで意味のないコンポーネントを指定するためのシンプルな仕組みとして、Asset Descriptionがv1.7.0で追加されました。
```suggestion
そのため、Avatar Optimizerに無視してほしい、ビルド時やランタイムで処理を行わないコンポーネントを指定するためのシンプルな仕組みとして、Asset Descriptionがv1.7.0で追加されました。
```

2024-04-30 03:31 UTC, Sayamame-beans commented
Others, LGTM!

2024-04-30 03:43 UTC, Sayamame-beans approved these changes

2024-04-30 03:47 UTC, merged