feat: implement mask texture editor
anatawa12/AvatarOptimizer pull request #1044
Opened 2024-05-04 08:40 UTC by nekobako

Resolves #1000 です。

Remove Mesh By Mask のマスクテクスチャのフィールドが None の場合は作成ボタンを表示し、そうでない場合は編集ボタンを表示します。
![1000-0](https://github.com/anatawa12/AvatarOptimizer/assets/4340778/aed3d390-7882-451a-a19d-3baa7548697c)
![1000-1](https://github.com/anatawa12/AvatarOptimizer/assets/4340778/2e3915e1-1ab4-49ab-83c7-3146a7c12861)

作成ボタンを押すとファイル保存ダイアログが開き、編集ボタンを押すとマスクテクスチャエディターが開きます。
マスクテクスチャエディターには必須かなと思う機能を実装しています。
![1000-2](https://github.com/anatawa12/AvatarOptimizer/assets/4340778/e43ef713-a0a9-4155-aa05-0a414c575236)

2024-05-04 08:52 UTC, nekobako commented
Windows とマウス操作でしか確認していないので、macOS やトラックパッドでの動作確認はお願いしたいです。
(そもそも動くかどうかやスクロール操作が速すぎたりしないかなど)

2024-05-04 09:01 UTC, anatawa12 commented
macのマウスは悪くなさそうです。トラックパッドはマウスのそのままなので使いやすいわけではないですが問題なさそうなのでこのままで行きます

2024-05-04 09:34 UTC, Sayamame-beans requested changes
CC: @anatawa12

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "マスクテクスチャエディター"
```suggestion
msgstr "AAO マスクテクスチャエディター"
```
```suggestion
msgstr "AAO マスクテクスチャエディタ"
```
一応どのツールからのウィンドウなのか分かりやすい方が良いのかなと思って足してみました
エディター vs エディタ はanatawaさんに任せます

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "{0}番"
```suggestion
msgstr "{0}番目"
```
anatawaさんのお好みでチョイスして欲しいかもです

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "反転する"
```suggestion
msgstr "色を反転させる"
```
お好みで?

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "テクスチャの作成に失敗しました"
```suggestion
msgstr "テクスチャの作成に失敗しました。"
```

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "テクスチャの保存に失敗しました"
```suggestion
msgstr "テクスチャの保存に失敗しました。"
```

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "テクスチャの保存に失敗しました"
この辺りのエラー、原因が分かるものがありそうなら書きたい感じもありますね(難しそうなら大丈夫です)

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "OK"
ダイアログのOKボタンって明示的な翻訳が必要なのかどうか…と思ったり…?
(anatawaさんに委ねます)

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "MaskTextureEditor"
```suggestion
msgstr "AAO MaskTextureEditor"
```

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "{0}番"
( https://github.com/anatawa12/AvatarOptimizer/blob/8077ff7b1a164009f3f54dc076ad20b9d4129c8c/Localization/ja-jp.po#L338 
を"番目"にしてなかったことには気付きました )

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Inverse"
```suggestion
msgstr "Inverse Color"
```
お好みで

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Failed to create the texture"
```suggestion
msgstr "Failed to create the texture."
```

2024-05-04 09:34 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Failed to save the texture"
```suggestion
msgstr "Failed to save the texture."
```

2024-05-04 09:35 UTC, Sayamame-beans commented
Docs生やすことも後で考える必要がありますね… anatawaさんが別PRとかで草案書きます?

2024-05-04 09:54 UTC, nekobako commented
Unity の Undo と整合性が取れなくなるため、ウィンドウ内の `<` / `>` ボタンを押すとそれより前に Undo できなくなる仕様にしていましたが、この操作を Undo 対象として捉えて Unity の Undo に記録するように変更しました。
Undo を Undo できるみたいな気持ちわるさはありますが、単に履歴を移動するボタンだと思えば途中から Ctrl/Command-Z できなくなるよりはマシかなと思ってます。

2024-05-04 10:06 UTC, anatawa12 requested changes
また可能であればEditMode Preview中は中間Texture2Dを経由するなどで即時に反映できると嬉しいですが難しそうであればこのままで行きます

2024-05-04 10:17 UTC, anatawa12 commented on Localization/ja-jp.po
> +msgstr "{0}番"
正直どっちでもいいので既存に合わせて "N番"で

2024-05-04 10:39 UTC, nekobako commented on Localization/ja-jp.po
> +msgstr "マスクテクスチャエディター"
ありがとうございます。
一旦のばし棒をそのままに AAO を付けました。

2024-05-04 10:42 UTC, nekobako commented on Localization/ja-jp.po
> +msgstr "反転する"
対応しました。分かりやすそうです。

2024-05-04 10:47 UTC, nekobako commented on Localization/ja-jp.po
> +msgstr "テクスチャの保存に失敗しました"
一応 Exception はログに流すようにはしていますが、それをそのままダイアログに表示しても・・という感じでとりあえずこうなっています。
anatawa さんの意見も聞きたいかもです。

2024-05-04 10:52 UTC, anatawa12 commented on Localization/ja-jp.po
> +msgstr "マスクテクスチャエディター"
エディターの方にしよう

2024-05-04 10:53 UTC, anatawa12 commented on Localization/ja-jp.po
> +msgstr "テクスチャの保存に失敗しました"
exception読まないと原因わかりませんし、エラーはログに吐くでいいと思う。やるならログを参照してくださいってメッセージ書くくらい

2024-05-04 10:53 UTC, anatawa12 commented on Localization/ja-jp.po
> +msgstr "OK"
なくていいと思う。他どうなってたっけ

2024-05-04 11:11 UTC, nekobako commented on Localization/ja-jp.po
> +msgstr "テクスチャの保存に失敗しました"
`テクスチャの保存に失敗しました。詳細はログを参照してください。`
`Failed to save the texture. Refer to the log for details.`

コンソールウィンドウの、と入れた方がよいでしょうか？

2024-05-04 11:13 UTC, anatawa12 commented on Localization/ja-jp.po
> +msgstr "テクスチャの保存に失敗しました"
ログでいいと思う。

2024-05-04 11:19 UTC, nekobako commented on Localization/ja-jp.po
> +msgstr "OK"
`OK`
https://github.com/anatawa12/AvatarOptimizer/blob/master/Editor/LegacyModularAvatarWarning.cs#L21-L24

`Ok`
https://github.com/anatawa12/AvatarOptimizer/blob/master/Editor/Inspector/UnusedBonesByReferencesToolEditor.cs#L58-L60

2024-05-04 11:23 UTC, anatawa12 commented on Localization/ja-jp.po
> +msgstr "OK"
他が全部OKそのままなので翻訳じゃなくしましょうか

2024-05-04 11:23 UTC, nekobako commented on Editor/MaskTextureEditor/Inspector.cs
> +                        AAOL10N.Tr("MaskTextureEditor:edit"),
対応しました。(Scope 系を使うと diff が見づらい…)
拡張子しか見てないですがよいですか？

2024-05-04 11:24 UTC, nekobako commented on Editor/MaskTextureEditor/Shaders/Fill.shader
> +Shader "Hidden/MaskTextureEditor/Fill"
対応しました。

2024-05-04 11:24 UTC, nekobako commented on Editor/MaskTextureEditor/TexturePainter.cs
> +        private void Init(Vector2 size)
対応しました。

2024-05-04 11:30 UTC, anatawa12 commented on Editor/MaskTextureEditor/Inspector.cs
> +                        AAOL10N.Tr("MaskTextureEditor:edit"),
拡張子だけでいいと思います。unityの仕組みが拡張子見てるので

2024-05-04 11:31 UTC, nekobako commented on Localization/ja-jp.po
> +msgstr "テクスチャの保存に失敗しました"
対応しました。

2024-05-04 11:32 UTC, nekobako commented on Localization/ja-jp.po
> +msgstr "OK"
翻訳じゃなくしました。

2024-05-04 11:34 UTC, anatawa12 commented
docs何書けばいいのかがあんまわからない。ボタンでウィンドウ出ることと出たときのウィンドウの使い方かな。別PRで私がやればいいのかな

2024-05-04 13:02 UTC, Sayamame-beans commented
これって、オブジェクトの選択を変えたり複数Inspector表示するなどして、複数のマスクテクスチャエディターを開こうとするとどうなりますか…?

2024-05-04 13:03 UTC, Sayamame-beans commented
> ボタンでウィンドウ出ることと出たときのウィンドウの使い方かな。

概ねそんなもののような気がします? 別PRで大丈夫だと思います。

2024-05-04 13:28 UTC, nekobako commented
> オブジェクトの選択を変えたり複数Inspector表示するなどして、複数のマスクテクスチャエディターを開こうとするとどうなりますか…?

ウィンドウが開いていない状態で編集ボタンを押すと、押したボタンが色付きになってウィンドウが開きます。
ウィンドウが開いている状態で色付きになった編集ボタンを押すと、押したボタンが通常の色に戻ってウィンドウが閉じます。

ウィンドウが開いている状態で色付きになっていない別の編集ボタンを押すと、色付きになっているボタンが通常の色に戻って開いているウィンドウが閉じ、押したボタンが色付きになって新しいウィンドウが開きます。

2024-05-04 17:35 UTC, nekobako commented on Editor/MaskTextureEditor/Window.cs
> +    internal class Window : EditorWindow
下記のときに保存していない変更があれば保存するか確認するようにしました。
- Inspector の編集ボタンをオフにしたとき
- Inspector の別のマスクテクスチャの編集ボタンを押したとき
- EditorWindow の閉じるボタンを押したとき (2019 は普通の方法では無理そうだったので非対応です)

2024-05-05 05:09 UTC, nekobako commented
> EditMode Preview中は中間Texture2Dを経由するなどで即時に反映できると嬉しいですが

こちら対応しました！

あとは 1 日経って気になったので

- 編集中のマスクテクスチャのフィールドを disabled に
  - 編集中にマスクテクスチャを変更されても困りはしませんでしたが、関係ないテクスチャを編集していることになって微妙だったので
- alt か shift か control か command を押していると左ドラッグでも移動できるように
  - 中ドラッグや右ドラッグができないトラックパッドでの操作性がよくなるはず
- 表示倍率のスライダーを触ったときにビューポートの中央を中心にスケールするように
  - 左上を中心にスケールするのが気持ちわるかったので

しました。

2024-05-05 05:46 UTC, anatawa12 commented on Editor/MaskTextureEditor/Window.cs
> +    internal class Window : EditorWindow
:+1: 確認しました

2024-05-05 06:03 UTC, anatawa12 reviewed
大体は良さそうですが、二点気になりました

- もともとそうだったようですがプレビュー中にremove mesh by Maskによって削除されるポリゴンのUVが表示されなくなりますが表示されたほうが嬉しいと思います
- EditMode Previewを有効な状態でマスクテクスチャエディターを開くと常にウィンドウのフォーカスがかかって他のアプリケーションやウィンドウを操作できなくなりました (macOSだけだったらすみません)

2024-05-05 06:05 UTC, anatawa12 commented
ドキュメントを書く必要があるのでターゲットを `mask-texture-editor` ブランチに変更しました

2024-05-05 06:36 UTC, nekobako commented
> プレビュー中にremove mesh by Maskによって削除されるポリゴンのUVが表示されなくなりますが表示されたほうが嬉しいと思います

特に境界のところなど、実際にどの頂点が消えるのかが分かりやすい方がよいかと思っているのですが、そうでもなさそうでしょうか・・？
プレビューをやめると元の UV も確認できるので今の仕様の方ができることは多い気がしています。

![スクリーンショット 2024-05-05 153159](https://github.com/anatawa12/AvatarOptimizer/assets/4340778/435b486a-4333-46c0-a484-05eb39cb1f5d)

> EditMode Previewを有効な状態でマスクテクスチャエディターを開くと常にウィンドウのフォーカスがかかって

すみません…！修正しました。

2024-05-05 06:45 UTC, anatawa12 commented
実際にどの頂点が消えるのかを見るのであれば線の色を変えたほうがいいかもしれないです。preview中にどこを白くすれば戻るかがわかりやすいほうがいいと思います

2024-05-05 07:17 UTC, Sayamame-beans approved these changes
l10nは多分OK…?

2024-05-05 12:02 UTC, nekobako commented
プレビュー中は消える線の色を変えて表示するようにしました。

2024-05-05 14:00 UTC, anatawa12 approved these changes
見た感じ良さそうですありがとうございます

2024-05-05 14:00 UTC, merged