Mask texture editor
anatawa12/AvatarOptimizer pull request #1051
Opened 2024-05-05 14:01 UTC by anatawa12

pending: documentation

2024-05-05 15:38 UTC, nekobako commented
ドキュメント、私の方でやった方がいいことがもしあればやりますので言ってくださいー

2024-05-06 13:02 UTC, Sayamame-beans requested changes
こんな感じ?

2024-05-06 13:02 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-mask/index.md
> +You can scroll to zoom in/out and shift + scroll to change the brush size.
```suggestion
You can scroll to zoom in/out, and shift + scroll to change the brush size.
```

2024-05-06 13:02 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-mask/index.ja.md
> +描画テクスチャに関する情報が描画ウィンドウの上に表示されます。\
```suggestion
ウィンドウの上部には、編集中のマスクテクスチャに関する情報が表示されます。\
```

2024-05-06 13:02 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-mask/index.ja.md
> +下の描画ウィンドウには、元のテクスチャ、マスクテクスチャ、メッシュのUVが表示されます。
```suggestion
ウィンドウの下部には、元のテクスチャ、マスクテクスチャ、メッシュのUVが表示されます。
```

2024-05-06 13:35 UTC, Sayamame-beans approved these changes

2024-05-06 14:41 UTC, merged