docs: add component scripting api
anatawa12/AvatarOptimizer pull request #1083
Opened 2024-06-03 12:47 UTC by anatawa12

WIP

Fixes 
- #1078

2024-06-06 14:03 UTC, Sayamame-beans requested changes

2024-06-06 14:03 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +- kurotuによる[VRChat Quest Tools]を使用する
```suggestion
- kurotuの[VRCQuestTools]を使用する
```
の なのか による なのか

2024-06-06 14:03 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +  [VRChat Quest Tools]は、アバターをAndroid / Quest対応アバターに変換するためのツールです。\
```suggestion
  [VRCQuestTools]は、アバターをAndroid / Quest対応アバターに変換するためのツールです。\
```

2024-06-06 14:03 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +  このツールには、[VQT Avatar Builder]というビルド前チェックをスキップしてアバターをAndroid向けにビルドする機能が含まれています。
```suggestion
  このツールには、ビルド前チェックをスキップしてアバターをAndroid向けにビルドするための[VQT Avatar Builder]という機能が含まれています。
```

2024-06-06 14:03 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +[VRChat Quest Tools]: https://kurotu.github.io/VRCQuestTools/
```suggestion
[VRCQuestTools]: https://kurotu.github.io/VRCQuestTools/
```

2024-06-06 14:03 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.md
(これまだ未チェックです)
日本語版はなくて良いのです?

2024-06-07 00:00 UTC, anatawa12 commented on .docs/content/docs/reference/merge-toonlit-material/index.md
> +You should add `Merge ToonLit Material` to the same GameObject as `AAO Merge Skinned Mesh` component if you want to merge materials from multiple renderers.
レファレンスではAAOなしにしてたはずなのでMergeSMR側を変えるかな

2024-06-07 00:02 UTC, anatawa12 commented on .docs/content/docs/reference/merge-toonlit-material/index.md
> +This component will create new materials thus materials created by this component will not be merged by `AAO Merge Skinned Mesh` component.
リファレンスではスロットにしてたっけ Submeshにしてたっけ

2024-06-07 00:04 UTC, anatawa12 commented on .docs/content/docs/reference/merge-toonlit-material/index.ja.md
> +複数のレンダラーからマテリアルを統合したい場合は、`AAO Merge Skinned Mesh`コンポーネントと同じGameObjectに`Merge ToonLit Material`を追加する必要があります。
マテリアル以外をマージしないので「マテリアルを」でいい気がする

2024-06-07 00:06 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +However, for technical reasons, the `AAO Trace and Optimize` component cannot detect some PhysBone / Contact Receiver components are used in the OSC-based gimmick or not being used.
OSCに使われてるか、一切使われてないかという二択なので単なるor notとは違う気がする

2024-06-07 00:09 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +I may implement list of parameters likely to be used by OSC and Avatar Optimizer may keep components for those parameters or other ways to prevent removing them in the future.
doなくて良くない？implementの目的句なので

2024-06-07 00:11 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +But, if your avatar does not exceed the hard limit after build, you can upload the avatar with some other ways.
これはpre buildを省略できるだけでビルド後のチェックはあるよっていう話なんだけど表現悪いかな

> 日本語にない

ミス

2024-06-07 00:14 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +I may implement list of parameters likely to be used by OSC and Avatar Optimizer may keep components for those parameters or other ways to prevent removing them in the future.
mayに掛かってるのかと思いました
implementに掛かってるのか…

2024-06-07 00:15 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-toonlit-material/index.md
> +This component will create new materials thus materials created by this component will not be merged by `AAO Merge Skinned Mesh` component.
> Also, it can reduce material slots using the same material, so we can reduce rendering cost.

> Check Merge to merge those MaterialSlots (SubMeshes) into one MaterialSlot. This reduces DrawCalls.

2024-06-07 00:18 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +But, if your avatar does not exceed the hard limit after build, you can upload the avatar with some other ways.
この辺り、全体的に同じ内容が2回出てきてそうなので、ちょっと整理した方が良いのかも…?

2024-06-07 00:19 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.md
日本語ないのはミス

2024-06-07 00:21 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +  アバターのGameObjectのコンテクストメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、アバターをアップロードする前に非破壊的なツールを適用できます。
ビルドせずってのなくてもいいと思ってるけどいれるならかっこなしでもいいかも

2024-06-07 00:23 UTC, anatawa12 commented on .docs/content/docs/reference/merge-toonlit-material/index.md
> +This component will create new materials thus materials created by this component will not be merged by `AAO Merge Skinned Mesh` component.
スロットが多そうだね。そっちで行こう

2024-06-07 00:24 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +But, if your avatar does not exceed the hard limit after build, you can upload the avatar with some other ways.
```suggestion
Even so, if your avatar does exceed the hard limit after build, you cannot upload the avatar with the following ways.
```

2024-06-07 01:43 UTC, anatawa12 commented on .docs/content/docs/reference/merge-toonlit-material/index.md
> +You should add `Merge ToonLit Material` to the same GameObject as `AAO Merge Skinned Mesh` component if you want to merge materials from multiple renderers.
Component Kindとかでの参照が`Merge Skinned Mesh`

2024-06-07 01:45 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +However, for technical reasons, the `AAO Trace and Optimize` component cannot detect some PhysBone / Contact Receiver components are used in the OSC-based gimmick or not being used.
でも判断できるのはOSDで使われてるかどうかだからいいか。

2024-06-07 01:46 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +I may implement list of parameters likely to be used by OSC and Avatar Optimizer may keep components for those parameters or other ways to prevent removing them in the future.
```suggestion
I may implement list of parameters likely to be used by OSC and keeping components for those parameters, or other ways to prevent removing them in the future.
```

品詞を色々揃えた。

2024-06-07 01:57 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.md
日本語書きました

2024-06-07 02:55 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +  アバターのGameObjectのコンテクストメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、アバターをアップロードする前に非破壊的なツールを適用できます。
```suggestion
  アバターのGameObjectを右クリックして出てくるメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、非破壊ツールによる処理をアップロードを開始する前に手動で適用することができます。
```

か

```suggestion
  アバターのGameObjectを右クリックして出てくるメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、非破壊ツールによる処理を手動で適用することができます。
```

2024-06-07 11:17 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +I may implement list of parameters likely to be used by OSC and Avatar Optimizer may keep components for those parameters or other ways to prevent removing them in the future.
👌

2024-06-07 11:22 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +  アバターのGameObjectのコンテクストメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、アバターをアップロードする前に非破壊的なツールを適用できます。
括弧が無いと若干読みづらいかも…と思ったので入れてました
後者にします?

2024-06-07 11:24 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +But, if your avatar does not exceed the hard limit after build, you can upload the avatar with some other ways.
よく見たらpost build checkの話すでにあるね。ごめんなさい


これ見直したら

ビルド前でハードリミットに引っかかっても他の方法でアップロードする方法はあるよ
その方法は以下の通りだよ


という話の流れなので冗長なだけかも？

2024-06-07 11:44 UTC, Sayamame-beans commented
今気付いたんですが、basic-usageのindex.ja(過去編集分)にだけ"AvatarOptimizer"表記が混ざってるっぽいですね?
"Avatar Optimizer"に揃えておきたいかも

2024-06-07 11:52 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +  アバターのGameObjectのコンテクストメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、アバターをアップロードする前に非破壊的なツールを適用できます。
じゃあ後者で。

(このくらいの長さ普通に説明として普通な気がしてるけど読みづらいのかなぁ)

2024-06-07 12:06 UTC, Sayamame-beans requested changes
とりあえず…

2024-06-07 12:06 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +Therefore, `AAO Trace and Optimize` will assume that such components are not for OSC-based gimmick and remove them.
```suggestion
Therefore, `AAO Trace and Optimize` will assume that such components are not for OSC-based gimmick, and remove them if they are not used for other ways.
```
ちょっとはっきりさせてみる?

2024-06-07 12:06 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +However, this is not always the case, so if you are using PhysBone / Contact Receiver components for the OSC-based gimmick,
```suggestion
However, this assumption is not always the case, so if you are using PhysBone / Contact Receiver components for the OSC-based gimmick without Animator or Expressions,
```
```suggestion
Of course, this assumption is not always the case, so if you are using PhysBone / Contact Receiver components for the OSC-based gimmick without Animator or Expressions,
```
試しに変えてみた

2024-06-07 12:06 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +please configure your avatar to detect them as used in the avatar.
```suggestion
please configure your avatar to detect them as used in the avatar.\
```

2024-06-07 12:09 UTC, anatawa12 commented on .docs/content/docs/reference/merge-toonlit-material/index.ja.md
> +このコンポーネントは新しいマテリアルを作成するため、このコンポーネントで統合されたマテリアルを使用しているマテリアルスロットは`AAO Merge Skinned Mesh`コンポーネントで統合されません。
"統合されるマテリアルを使用していたマテリアルスロット"はMergeToonlitが終わった時点で存在しないのでMergeSMRの視点からすると"統合されたマテリアルを使用しているマテリアルスロット"

2024-06-07 12:21 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +Avatar Optimizer v1.7.0以降、AvatarにAvatar Optimizerのコンポーネントを追加・設定するためのComponent APIを提供します。
```suggestion
Avatar Optimizer v1.7.0以降、アバターにAvatar Optimizerのコンポーネントを追加・設定するためのComponent APIを提供しています。
```

2024-06-07 12:24 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +- `TraceAndOptimize` - デフォルトの設定での追加はサポートされていますが、設定はサポートされていません
```suggestion
- `TraceAndOptimize` - デフォルト設定での追加はサポートされていますが、設定変更はサポートされていません
```

2024-06-07 12:28 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +Avatar Optimizerはランタイムで動作しないため、ランタイムビルドに`com.anatawa12.avatar-optimizer.runtime`アセンブリを依存させてはいけません。
```suggestion
Avatar Optimizerはランタイムで動作しないため、ランタイムビルド向けで`com.anatawa12.avatar-optimizer.runtime`に依存してはいけません。
```

2024-06-07 12:32 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +次に、コンポーネントを設定する場合は、将来の機能との互換性を確保するために`void Initialize(int version)`メソッドを呼び出す必要があります。
```suggestion
次に、コンポーネントの設定を変更する場合は、将来のバージョンで追加される機能との互換性を確保するために`void Initialize(int version)`メソッドを呼び出す必要があります。
```

2024-06-07 12:35 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +したがって、将来のバージョンとの動作の互換性を保つためには、使用するデフォルト設定のバージョンを指定して`Initialize`メソッドを呼び出す必要があります。
```suggestion
従って、Avatar Optimizerの将来のバージョンとの互換性を保つためには、使用するデフォルト設定のバージョンを指定して`Initialize`メソッドを呼び出す必要があります。
```

2024-06-07 12:50 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-toonlit-material/index.ja.md
> +このコンポーネントは新しいマテリアルを作成するため、このコンポーネントで統合されたマテリアルを使用しているマテリアルスロットは`AAO Merge Skinned Mesh`コンポーネントで統合されません。
それはそうなんですけど、ユーザー主観だとどうかなと思って…まあどっちでも良いのか…?
(複数メッシュを跨がずに、1メッシュに対してMerge ToonLitを使ってた場合は、そのメッシュ上のマテリアルスロットだけは統合されたりってしないんですっけ? その場合は、今の文章から感じられる"Merge ToonLit適用対象のマテリアルスロットは必ず統合されない"というイメージと反するような)

2024-06-07 15:22 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.ja.md
> +現在、すべてのコンポーネントがComponent APIでサポートされているわけではありません。
利用可能にしましょうか

2024-06-07 15:26 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.ja.md
> +将来、`com.anatawa12.avatar-optimizer.runtime`からいくつかのクラスをランタイムビルドで削除するかもしれません。
#ifで消すのはruntimeビルドのみなので必要だと思う

2024-06-07 15:31 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.ja.md
> +言い換えると、ランタイムアセンブリで`com.anatawa12.avatar-optimizer.runtime`を使用するのは避けることが推奨されます。エディタアセンブリでのみ使用するようにしてください。
アセンブリはasmdefで定義して作ったコンパイル済のバイナリなので一応別ではある。

asmdefで参照しようとしててもいいけどコードから参照しないでくれって話になる

2024-06-07 15:39 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.md
> +Second, If you want to configure components, you have to call `void Initialize(int version)` method to ensure the compatibility with future features.
今はensureのほうがいいと認識して変えた

2024-06-08 09:51 UTC, anatawa12 commented on .docs/content/docs/reference/merge-toonlit-material/index.ja.md
> +このコンポーネントは新しいマテリアルを作成するため、このコンポーネントで統合されたマテリアルを使用しているマテリアルスロットは`AAO Merge Skinned Mesh`コンポーネントで統合されません。
MergeToonLitはマテリアルスロット/SubMesh結合行います。

2024-06-08 13:31 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +言い換えると、ランタイムアセンブリで`com.anatawa12.avatar-optimizer.runtime`を使用するのは避けることが推奨されます。エディタアセンブリでのみ使用するようにしてください。
ランタイムアセンブリを"ランタイム向けのアセンブリ"とするのはちょっとニュアンス変わっちゃう?

2024-06-08 13:59 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-toonlit-material/index.ja.md
> +このコンポーネントは新しいマテリアルを作成するため、このコンポーネントで統合されたマテリアルを使用しているマテリアルスロットは`AAO Merge Skinned Mesh`コンポーネントで統合されません。
なーるほど

2024-06-08 14:40 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +将来、`com.anatawa12.avatar-optimizer.runtime`からいくつかのクラスをランタイムビルドで削除するかもしれません。
```suggestion
`com.anatawa12.avatar-optimizer.runtime`にあるいくつかのクラスは、将来のバージョンでランタイム向けビルドから除外される可能性があります。
```

2024-06-08 14:43 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.ja.md
> +言い換えると、ランタイムアセンブリで`com.anatawa12.avatar-optimizer.runtime`を使用するのは避けることが推奨されます。エディタアセンブリでのみ使用するようにしてください。
そこは変わらないかな

2024-06-08 14:44 UTC, Sayamame-beans requested changes

2024-06-08 14:44 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +現在、すべてのコンポーネントがComponent APIでサポートされているわけではありません。
```suggestion
現時点では、すべてのコンポーネントがComponent APIで利用出来るわけではありません。
```

2024-06-08 14:44 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +## Component APIがサポートするコンポーネント {#supported-components}
"で"なのか"が"なのかで若干迷ってます

2024-06-08 14:44 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +Component APIでサポートされているコンポーネントのリストは以下の通りです。
```suggestion
Component APIが利用可能なコンポーネントの一覧は以下の通りです。
```

2024-06-08 14:44 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +- `RemoveMeshInBox` - コンポーネントの追加と設定がサポートされています
```suggestion
- `RemoveMeshInBox` - コンポーネントの追加と設定変更が利用できます
```

2024-06-08 14:44 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +- `RemoveMeshByBlendShape` - コンポーネントの追加と設定がサポートされています
```suggestion
- `RemoveMeshByBlendShape` - コンポーネントの追加と設定変更が利用できます
```

2024-06-08 14:44 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +- `TraceAndOptimize` - デフォルトの設定での追加はサポートされていますが、設定はサポートされていません
```suggestion
- `TraceAndOptimize` - デフォルト設定での追加は利用できますが、設定変更は利用できません
```

2024-06-08 15:18 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.ja.md
> +- `RemoveMeshInBox` - コンポーネントの追加と設定がサポートされています
こっちの一覧上ではサポートにしたほうが自然な気がする

2024-06-08 16:21 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +- `RemoveMeshInBox` - コンポーネントの追加と設定がサポートされています
そう? まあそれならサポートのままにしましょう

2024-06-09 09:44 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +Component APIを使用するには、assembly definitionファイルで`com.anatawa12.avatar-optimizer.runtime`を参照する必要があります。
asmdefの注釈入れます?

2024-06-09 10:10 UTC, Sayamame-beans approved these changes

2024-06-09 10:10 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.md
> +Since Avatar Optimizer does not work on the runtime, you should not depends on `com.anatawa12.avatar-optimizer.runtime` assembly for runtime build.
```suggestion
Since Avatar Optimizer does not work on the runtime, you should not depends on `com.anatawa12.avatar-optimizer.runtime` assembly for runtime build.\
```

2024-06-09 10:10 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.md
> +The default setting of Avatar Optimizer can be changed in the future (as described in [Behavior Stability](../../basic-concept/#behavior-stability)).
```suggestion
The default setting of Avatar Optimizer can be changed in the future (as described in [Behavior Stability](../../basic-concept/#behavior-stability)).\
```

2024-06-09 10:10 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.md
> +The default configuration version should be described in the document of the `Initialize` method.
```suggestion
The default configuration version should be described in the document of the `Initialize` method.\
```

2024-06-09 10:11 UTC, Sayamame-beans commented
あ、approveにしちゃった
お好みでどうぞ

2024-06-09 12:11 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.ja.md
> +Component APIを使用するには、assembly definitionファイルで`com.anatawa12.avatar-optimizer.runtime`を参照する必要があります。
注釈は何を指しています？

2024-06-09 12:12 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +Component APIを使用するには、assembly definitionファイルで`com.anatawa12.avatar-optimizer.runtime`を参照する必要があります。
https://github.com/anatawa12/AvatarOptimizer/blob/d6f8c4919366cdbcd85fdae52f3f2212577332fe/.docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md?plain=1#L101

2024-06-09 12:21 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.ja.md
> +Component APIを使用するには、assembly definitionファイルで`com.anatawa12.avatar-optimizer.runtime`を参照する必要があります。
こっちのほうが高度なユーザを想定してるからなくていいや

2024-06-09 12:21 UTC, merged