chore: mention initially not configured viseme / eyelids
anatawa12/AvatarOptimizer pull request #1139
Opened 2024-08-07 07:11 UTC by anatawa12

Fixes #1134

2024-08-07 07:15 UTC, Sayamame-beans commented
description足したいかも?
VRCではここが設定されてないとlipsync全体が動かなくなるよ、ぐらいの情報量

2024-08-07 07:27 UTC, anatawa12 commented
こんな感じ？

2024-08-07 08:38 UTC, Sayamame-beans commented
そんな感じです
後でレビューします

2024-08-07 14:47 UTC, Sayamame-beans requested changes
こんな感じ…?

2024-08-07 14:47 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "瞬き用のBlendShapeが固定・除去されているか、はじめから設定されていません。"
```suggestion
msgstr "瞬き用のBlendShapeが固定・除去されているか、設定されていません。"
```
"適切に"とか"正しく"とか入れようかとも思いましたが、ちょっと意図とズレるので却下…

2024-08-07 14:47 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "瞬き用のBlendShapeが存在しないものや設定されていない物がある場合、すべての瞬き用のBlendShapeが機能しません。"
```suggestion
msgstr "VRChatでは、瞬き用のBlendShapeとして存在しないものが指定されているか、設定されていない項目がある場合、すべての瞬き用のBlendShapeが機能しなくなります。"
```
```suggestion
msgstr "VRChatでは、瞬き用のBlendShapeとして存在しないものが指定されているか、設定されていない項目がある場合、瞬きが全く機能しなくなります。"
```

BlendShapeがというよりは機能が駄目になるという印象なので後者…? (実際はBlendShapeも動かせないのかもしれない)

2024-08-07 14:47 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "リップシンク用のBlendShapeが固定・除去されているか、はじめから設定されていません。"
```suggestion
msgstr "リップシンク用のBlendShapeが固定・除去されているか、設定されていません。"
```

2024-08-07 14:47 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "リップシンク用のBlendShapeが存在しないものや設定されていない物がある場合、すべてのリップシンク用のBlendShapeが機能しません。"
```suggestion
msgstr "VRChatでは、リップシンク用のBlendShapeとして存在しないものが指定されているか、設定されていない項目がある場合、すべてのリップシンク用のBlendShapeが機能しなくなります。"
```
```suggestion
msgstr "VRChatでは、リップシンク用のBlendShapeとして存在しないものが指定されているか、設定されていない項目がある場合、リップシンクが全く機能しなくなります。"
```

2024-08-07 16:38 UTC, anatawa12 commented on Localization/ja-jp.po
> +msgstr "リップシンク用のBlendShapeが存在しないものや設定されていない物がある場合、すべてのリップシンク用のBlendShapeが機能しません。"
リップシンクはパラメータは動いた気がするのでリップシンクが動かないは嘘かも

2024-08-08 09:46 UTC, anatawa12 commented on Localization/ja-jp.po
> +msgstr "瞬き用のBlendShapeが存在しないものや設定されていない物がある場合、すべての瞬き用のBlendShapeが機能しません。"
瞬きってパラメータはないんだっけ

2024-08-08 09:48 UTC, anatawa12 commented on Localization/ja-jp.po
> +msgstr "瞬き用のBlendShapeが存在しないものや設定されていない物がある場合、すべての瞬き用のBlendShapeが機能しません。"
なさそうだったのでこっちは機能しなくなりますにします

2024-08-08 10:11 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "瞬き用のBlendShapeが存在しないものや設定されていない物がある場合、すべての瞬き用のBlendShapeが機能しません。"
> 瞬きってパラメータはないんだっけ

確か、要望は出してるけど無いって感じだったかなぁ

2024-08-08 10:45 UTC, Sayamame-beans approved these changes
よさそう

2024-08-08 11:14 UTC, merged