Merge Skinned Mesh Enablement Animation
anatawa12/AvatarOptimizer pull request #1173
Opened 2024-09-01 16:27 UTC by anatawa12

Fixes #894

2024-09-02 10:58 UTC, Sayamame-beans requested changes

2024-09-05 07:38 UTC, anatawa12 commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +This feature supports copying only one animated property so if there are multiple animated properties (in other words, both `enabled` and `activeSelf`, or multiple `activeSelf` are animated), it will
```
common Root
 `- Parent 1
     `-Parent 2
         `- Renderer 
```

とあったときにParent 1とParent 2の療法がアニメーションされてるとだめです

2024-09-05 07:39 UTC, anatawa12 commented on CHANGELOG-PRERELEASE.md
> +  - This feature supports copying activeness animation of `isActive` of the GameObject or ancestors of the GameObject,
m_IsActiveかactiveSelfなんでactiveSelfにします

```suggestion
  - This feature supports copying activeness animation of `activeSelf` of the GameObject or ancestors of the GameObject,
```

2024-09-05 07:40 UTC, anatawa12 commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +If this checkbox is checked, the activeness / enablement animation of the target renderer will be copied to the merged renderer.
source => destinationで書いてるからsourceでも間違いではないというかmerge sourceって最初の方は書いてた気がする

2024-09-05 07:47 UTC, anatawa12 commented on .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
> +この機能は、統合先のSkinnedMeshRendererの`enabled`プロパティや、そのGameObjectや祖先のGameObjectの`activeSelf`プロパティのアニメーションをコピーします。
referenceはどっちかというとある程度分かる人想定なんですよね難しいところ

2024-09-07 14:36 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +If this checkbox is checked, the activeness / enablement animation of the target renderer will be copied to the merged renderer.
docsはほぼtargetで書いてるかも(どこかのタイミングで私が書き換えてしまったかも?)

2024-09-07 15:44 UTC, anatawa12 commented on CHANGELOG.md
> +    - If animations are unsupported, AAO will show a error message and abort the build.
```suggestion
- `Copy Enablement Animation` to Merge Skinned Mesh `#1173`
  - This feature copies activeness / enablement animation from source renderers to the merged renderer.
  - This feature is not enabled by default. You have to enable it in the inspector.
  - This feature supports copying activeness animation of `activeSelf` of the GameObject or ancestors of the GameObject,
    However, this feature does not work if multiple GameObjects (or both GameObject and Renderer itself) are animated.
  - In addition, this feature will be animate the `enabled` of the merged renderer, so you must not animate the `enabled` of the merged renderer.
    - If animations are unsupported, AAO will show a error message and abort the build.
```

2024-09-07 15:45 UTC, anatawa12 commented on .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
> +この機能は、アニメーションされているプロパティを1つのみコピーする事が可能であるため、複数のプロパティがアニメーションされている場合には(つまり、`enabled`と`activeSelf`の両方、または複数の`activeSelf`がアニメーションされている場合)エラーになります。
これって確定？

2024-09-08 05:29 UTC, Sayamame-beans requested changes

2024-09-08 05:29 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
> +この機能は、統合先のSkinnedMeshRendererの`enabled`プロパティや、そのGameObjectや祖先のGameObjectの`activeSelf`プロパティのアニメーションをコピーします。
改変出来る程度に分かることと、Unityの変数が分かる(スクリプトが読める/書ける)のとはちょっと別だからにゃ…

2024-09-08 05:29 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
> +この機能は、アニメーションされているプロパティを1つのみコピーする事が可能であるため、複数のプロパティがアニメーションされている場合には(つまり、`enabled`と`activeSelf`の両方、または複数の`activeSelf`がアニメーションされている場合)エラーになります。
書き換えました

2024-09-08 05:29 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +This feature supports copying only one animated property so if there are multiple animated properties (in other words, both `enabled` and `activeSelf`, or multiple `activeSelf` are animated), it will
```suggestion
This feature supports copying only one animated property so if there are multiple animated properties (e.g., both `enabled` and `activeSelf` are animated, or `activeSelf` are animated on multiple layers), it will be error.
```
とかどうでしょう

2024-09-08 05:29 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +This feature supports copying only one animated property so if there are multiple animated properties (in other words, both `enabled` and `activeSelf`, or multiple `activeSelf` are animated), it will
両方がアニメーションされてる場合などが駄目なのは、それが全体で共通かどうかを判定するのが大変だからですかね?

2024-09-08 08:49 UTC, anatawa12 commented on .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
> +この機能は、統合先のSkinnedMeshRendererの`enabled`プロパティや、そのGameObjectや祖先のGameObjectの`activeSelf`プロパティのアニメーションをコピーします。
animatorでenabledとかactiveとかは出てくるのよね...うーむ

2024-09-08 08:52 UTC, anatawa12 commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +This feature supports copying only one animated property so if there are multiple animated properties (in other words, both `enabled` and `activeSelf`, or multiple `activeSelf` are animated), it will
両方がアニメーションされている場合には、どちらもtrueなときにMerged SMRのenabledをtrueにする(どちらかがfalseならfalseにする)という面倒なアニメーション(or blendtree)を組まないといけないですが、それの生成が難しい(面倒)なために制限を設けてます。

一つだけならアニメーションをコピペするだけで済む(そしてそのためのインフラがAAOにはある)ので

2024-09-08 08:53 UTC, anatawa12 commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +This feature supports copying only one animated property so if there are multiple animated properties (in other words, both `enabled` and `activeSelf`, or multiple `activeSelf` are animated), it will
> `activeSelf` are animated on multiple layers

animator layerと勘違いされるとおもう。

2024-09-08 08:56 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +This feature supports copying only one animated property so if there are multiple animated properties (in other words, both `enabled` and `activeSelf`, or multiple `activeSelf` are animated), it will
それはちょっと思った
階層を表現する方法が分からなかった(複数というだけだと階層の意味は認識しづらいと思っています)

2024-09-08 09:02 UTC, anatawa12 commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +This feature supports copying only one animated property so if there are multiple animated properties (in other words, both `enabled` and `activeSelf`, or multiple `activeSelf` are animated), it will
both one `activeSelf` and parents' `activeSelf` とか？

2024-09-08 09:40 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +This feature supports copying only one animated property so if there are multiple animated properties (in other words, both `enabled` and `activeSelf`, or multiple `activeSelf` are animated), it will
いいかも

2024-09-08 09:43 UTC, anatawa12 commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +This feature supports copying only one animated property so if there are multiple animated properties (in other words, both `enabled` and `activeSelf`, or multiple `activeSelf` are animated), it will
じゃあ日本語も同じ方針でお願いします

2024-09-08 09:51 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
> +この機能は、アニメーションされているプロパティを1つのみコピーする事が可能であるため、複数のプロパティがアニメーションされている場合には(つまり、`enabled`と`activeSelf`の両方、または複数の`activeSelf`がアニメーションされている場合)エラーになります。
再度書き換えました

2024-09-08 10:18 UTC, anatawa12 commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +This feature supports copying only one animated property so if there are multiple animated properties (in other words, both `enabled` and `activeSelf`, or multiple `activeSelf` are animated), it will
```suggestion
This feature supports copying only one animated property so if there are multiple animated properties (e.g., both `enabled` and `activeSelf` are animated, or both one `activeSelf` and parents' `activeSelf`), it will be error.
```

2024-09-08 11:32 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
> +この機能は、統合先のSkinnedMeshRendererの`enabled`プロパティや、そのGameObjectや祖先のGameObjectの`activeSelf`プロパティのアニメーションをコピーします。
まあ、"SkinnedMeshRendererの"とか"GameObjectの"とか書いてあるので比較的分かりやすい方ではあると思われ

2024-09-09 13:59 UTC, Sayamame-beans requested changes

2024-09-09 13:59 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.md
> +This feature supports copying only one animated property so if there are multiple animated properties (e.g., both `enabled` and `activeSelf` are animated, or both one `activeSelf` and parents' `activ
```suggestion
This feature supports copying only one animated property so if there are multiple animated properties (e.g., both `enabled` and `activeSelf` are animated, or both one `activeSelf` and parents' `activeSelf` are), it will be error.
```

2024-09-09 13:59 UTC, Sayamame-beans commented on CHANGELOG-PRERELEASE.md
> +  - This feature supports copying activeness animation of `activeSelf` of the GameObject or ancestors of the GameObject,
```suggestion
  - This feature supports copying activeness animation of `activeSelf` of the GameObjects or ancestors of the GameObjects.
```
docsでは複数になってた

2024-09-09 13:59 UTC, Sayamame-beans commented on CHANGELOG-PRERELEASE.md
> +    - If animations are unsupported, AAO will show a error message and abort the build.
```suggestion
    - If animations are unsupported, AAO will show an error message and abort the build.
```

2024-09-09 13:59 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - This feature supports copying activeness animation of `activeSelf` of the GameObject or ancestors of the GameObject,
```suggestion
  - This feature supports copying activeness animation of `activeSelf` of the GameObjects or ancestors of the GameObjects.
```

2024-09-09 13:59 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - In addition, this feature will be animate the `enabled` of the merged renderer, so you must not animate the `enabled` of the merged renderer.
```suggestion
  - In addition, this feature will be animate the `enabled` of the merged renderer, so you must not animate the `enabled` of the merged renderer.
```

2024-09-09 13:59 UTC, Sayamame-beans commented on CHANGELOG.md
> +    - If animations are unsupported, AAO will show a error message and abort the build.
```suggestion
    - If animations are unsupported, AAO will show an error message and abort the build.
```

2024-09-09 16:01 UTC, anatawa12 commented on CHANGELOG.md
> +  - In addition, this feature will be animate the `enabled` of the merged renderer, so you must not animate the `enabled` of the merged renderer.
no diff?

2024-09-09 16:31 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - In addition, this feature will be animate the `enabled` of the merged renderer, so you must not animate the `enabled` of the merged renderer.
そうっぽい(よく見ずにprereleaseからコピペした)

2024-09-12 13:48 UTC, Sayamame-beans requested changes

2024-09-12 13:48 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
> +なお、統合先のSkinnedMeshRendererの`enabled`に対するアニメーションはこの機能によって上書きされるため、統合先のSkinnedMeshRendererの`enabled`をアニメーションしてはいけません。
```suggestion
なお、統合先のSkinnedMeshRendererの`enabled`に対するアニメーションはこの機能によって上書きされるため、この機能を使用する時は統合先のSkinnedMeshRendererの`enabled`をアニメーションしてはいけません。
```
足した

2024-09-12 13:48 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - This feature copies activeness / enablement animation from source renderers to the merged renderer.
```suggestion
  - This feature copies activeness / enablement animation from merge target renderers to the merged renderer.
```

2024-09-12 13:50 UTC, Sayamame-beans commented
the others are ok

2024-09-18 10:00 UTC, merged