Rename BlendShape
anatawa12/AvatarOptimizer pull request #1245
Opened 2024-10-09 04:00 UTC by anatawa12

Fix #9

2024-10-09 04:04 UTC, anatawa12 commented on Internal/PrefabSafeSet/Runtime/PrefabSafeMap.cs
> +
```suggestion
```

PSMに関してはいらないな

2024-10-09 07:43 UTC, Sayamame-beans commented
ready to localize?

2024-10-09 08:06 UTC, anatawa12 commented
> ready to localize?

Yes. I'm investigating the CI failure that seems no errors

2024-10-09 08:46 UTC, anatawa12 commented
it looks SIGSEGV in unity editor

2024-10-09 08:53 UTC, Sayamame-beans requested changes

2024-10-09 08:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/rename-blendshape/component.png
remove mesh by blendshapeのスクショになっています

2024-10-09 09:07 UTC, Sayamame-beans commented on Editor/Inspector/RenameBlendShapeEditor.cs
> +                }
対応するmessageboxと発生位置が遠くなることが予想されるので、色が変わっている部分にカーソルを合わせるとtooltipで同じ内容のメッセージが表示されると良さそうです

2024-10-09 09:10 UTC, Sayamame-beans commented on Editor/Inspector/RenameBlendShapeEditor.cs
> +                }
🙏

2024-10-09 09:24 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgid "RenameBlendShape:warning:weight-conflict-some"
名前の重複なので、weight-conflictではなさそうです

2024-10-09 09:30 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
これwarningなんですね…? どういう挙動になるんでしょう

2024-10-09 09:32 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
> その名前になった最初のBlendShapeのweightになります

それは警告/Docs共に明示した方が良いですね…

2024-10-09 09:58 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Weights of source BlendShapes for merged BlendShape '{0}' is partially animated"
weight-conflictは統合対象の一覧があるのに対して、こちらでは無いのが若干気になりました

2024-10-09 10:00 UTC, anatawa12 commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
説明が難しいんですよね。最初とは言うもののマップの適用方法を丁寧に説明しないといけないので

うーんエラーにするかエラーにしなくても動きはするからこうしたけど

2024-10-09 10:03 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
ふーむ
どの値が使われるかわからない、的な感じでも良いとは思い

2024-10-09 10:26 UTC, Sayamame-beans commented
AAO Rename BlendShapeってModifying Edit Skinned Mesh Componentです? (記載なし)

2024-10-09 11:28 UTC, anatawa12 commented on Localization/en-us.po
> +msgstr "Weights of source BlendShapes for merged BlendShape '{0}' is partially animated"
いい表現が思いつかなかったのでこうなってるだけなので {1} に,区切りのが渡されてます

2024-10-09 11:42 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Weights of source BlendShapes for merged BlendShape '{0}' is partially animated"
助かる

2024-10-09 11:42 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Weights of source BlendShapes for merged BlendShape '{0}' is partially animated"
表現が思いつかないはそれはそう…(weight-conflictの方でも変な感じになっているので)

2024-10-09 11:45 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
animation-conflictの場合も、統合対象の内のいずれかに対するものが使用される感じですかね?

2024-10-09 11:47 UTC, Sayamame-beans commented
とりあえず日本語更新しました

2024-10-09 12:22 UTC, anatawa12 commented
> AAO Rename BlendShapeってModifying Edit Skinned Mesh Componentです? (記載なし)

はい。忘れですね

2024-10-09 14:40 UTC, anatawa12 commented
The cause of SIGSEGV is loooooong type name and the fact it's used in class name of delayCall.

`PrefabSafeUniqueCollection<MapEntry<TKey, TValue>, TKey, PrefabSafeMapManipulator<TKey, TValue>>` with string key/value would become ``Anatawa12.AvatarOptimizer.PrefabSafeUniqueCollection.PrefabSafeUniqueCollection`3[[Anatawa12.AvatarOptimizer.PrefabSafeMap.MapEntry`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], com.anatawa12.avatar-optimizer.internal.prefab-safe-set, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Anatawa12.AvatarOptimizer.PrefabSafeMap.PrefabSafeMapManipulator`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], com.anatawa12.avatar-optimizer.internal.prefab-safe-set, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]``, and this would cause buffer overflow

2024-10-09 15:00 UTC, anatawa12 commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
わからないって書くか。

2024-10-09 15:13 UTC, anatawa12 commented
CI通ったね...
F**k Unity C++

2024-10-10 00:36 UTC, anatawa12 commented on Editor/Inspector/RenameBlendShapeEditor.cs
> +                }
多分できた

2024-10-10 00:36 UTC, anatawa12 commented on Localization/en-us.po
> +msgid "RenameBlendShape:warning:weight-conflict-some"
fixed in 1d8e060305c541b49863ef4c58b056b72187c655

2024-10-10 01:38 UTC, anatawa12 commented on .docs/content/docs/reference/rename-blendshape/index.md
> +
```suggestion

This component should be added to a GameObject which has a SkinnedMeshRenderer component. (Kind: [Modifying Edit Skinned Mesh Component](../../component-kind/edit-skinned-mesh-components#modifying-component))

```

2024-10-10 06:30 UTC, anatawa12 commented
多分機能的にはOKなのでローカライズ/ドキュメント周りが良くなったらマージ

2024-10-11 06:48 UTC, Sayamame-beans commented
Edit Skinned Mesh Component側のページに記載忘れてる

2024-10-11 16:19 UTC, anatawa12 commented
> Edit Skinned Mesh Component側のページに記載忘れてる

直しました。

2024-10-12 05:57 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
結局これどうなります?

2024-10-12 08:17 UTC, anatawa12 commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
書いていいけどなんて書くか考えてない状態。

2024-10-12 09:38 UTC, anatawa12 commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
```suggestion
msgid "RenameBlendShape:warning:weight-conflict"
msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}.\n"
"It's hard to know which weight will be used."
```

とか？

2024-10-12 10:40 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
{1}が長くない前提ならそうかも…

2024-10-12 10:41 UTC, anatawa12 commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
{1}の長さは不定なのよね。100個のBlendShape結合されたらそうなる

2024-10-12 10:42 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
```suggestion
msgid "RenameBlendShape:warning:weight-conflict"
msgstr "Weight for merged BlendShape '{0}' is not same in all sources, so it's hard to know which weight will be used.\n"
"Sources: {1}"
```
とかでも無しではないかな…?

2024-10-12 10:50 UTC, anatawa12 commented on Localization/en-us.po
> +msgstr "Weight for merged BlendShape '{0}' is not same in all sources: {1}"
そのほうが見やすいか。そうします

2024-10-12 10:56 UTC, Sayamame-beans commented
多分良い感じになったと思う
changelogでmerge機能については言及しなくて良い?

2024-10-12 11:00 UTC, anatawa12 commented
マージはとりあえずおまけなので。

あとマージはこのまま行くかは少し検討したい 

BlendShape結合による軽量化をやりたいって考えたらもっと高度なコンポーネントが欲しくなる気がするので、Rename BlendShapeから消してv1.9で別コンポーネントを作るってやるかも

2024-10-12 11:06 UTC, anatawa12 commented
じゃぁマージします

2024-10-12 11:06 UTC, Sayamame-beans commented
👍

2024-10-12 11:13 UTC, anatawa12 commented
マージ仕様の是非について => #1250

2024-10-12 11:14 UTC, anatawa12 commented
SayamameさんがRequest Changesしたままだからマージできないわ

2024-10-12 11:27 UTC, Sayamame-beans approved these changes
good to go

2024-10-12 11:27 UTC, merged