feat: invert option for RemoveMeshInBox
anatawa12/AvatarOptimizer pull request #1257
Opened 2024-10-13 10:18 UTC by anatawa12

Fix #1035

2024-10-13 19:05 UTC, Sayamame-beans requested changes

2024-10-13 19:05 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-box/index.md
> +Remove some polygons in any of specified boxes.
```suggestion
Remove some polygons by any of specified boxes.
```
```suggestion
Remove some polygons with any of specified boxes.
```
inではなくなったので

2024-10-13 19:05 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-box/component.png
コンポーネント名がinのままになっている

2024-10-13 19:24 UTC, Sayamame-beans commented on .docs/content/docs/component-kind/edit-skinned-mesh-components/index.ja.md
> +- [Remove Mesh by Box](../../reference/remove-mesh-by-box)
```suggestion
- [Remove Mesh By Box](../../reference/remove-mesh-by-box)
```

2024-10-13 19:24 UTC, Sayamame-beans commented on .docs/content/docs/component-kind/edit-skinned-mesh-components/index.md
> +- [Remove Mesh by Box](../../reference/remove-mesh-by-box)
```suggestion
- [Remove Mesh By Box](../../reference/remove-mesh-by-box)
```

2024-10-14 00:48 UTC, anatawa12 commented on .docs/content/docs/reference/remove-mesh-by-box/component.png
9909b1efc48c230e977811524eb94e2a8d2fcbbc

2024-10-14 00:49 UTC, anatawa12 commented on .docs/content/docs/reference/remove-mesh-by-box/index.ja.md
diffになってなくて分かりづらいですけど箱の編集に関する説明も更新してます。

2024-10-14 07:16 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-box/index.md
> +You can add a box by changing size of the list with number on the left of `Boxes`.
左右逆?
```suggestion
You can add a box by changing size of the list with number on the right of `Boxes`.
```

2024-10-14 07:31 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-box/index.ja.md
正直いいかなって思っちゃった節もありますが、更新しておきました

2024-10-14 07:31 UTC, anatawa12 commented on .docs/content/docs/reference/remove-mesh-by-box/index.md
> +You can add a box by changing size of the list with number on the left of `Boxes`.
rightだね。逆でした

2024-10-14 07:32 UTC, Sayamame-beans commented
FYI: cause of game ci failure -> https://feedback.vrchat.com/creator-companion/p/403-forbidden-errors-from-vcc-endpoints-when-invoked-from-github-actions
https://misskey.niri.la/notes/9zburcz0nb

2024-10-14 07:40 UTC, anatawa12 commented
Reported as https://github.com/vrchat-community/creator-companion/issues/542#issuecomment-2410297277

2024-10-15 11:30 UTC, merged