Remove mesh by uv tile
anatawa12/AvatarOptimizer pull request #1263
Opened 2024-10-14 07:31 UTC by anatawa12

Fix #838

2024-10-14 07:57 UTC, Sayamame-beans requested changes

2024-10-14 07:57 UTC, Sayamame-beans commented on CHANGELOG-PRERELEASE.md
> +- Remove Mesh by UV Tile, a new way to remove polygons `#1263`
```suggestion
- Remove Mesh By UV Tile, a new way to remove polygons `#1263`
```

2024-10-14 07:57 UTC, Sayamame-beans commented on CHANGELOG.md
> +- Remove Mesh by UV Tile, a new way to remove polygons `#1263`
```suggestion
- Remove Mesh By UV Tile, a new way to remove polygons `#1263`
```

2024-10-14 07:57 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-uv-tile/index.md
> +This component should be added to a GameObject which has a SkinnedMeshRenderer component. (Kind: [Modifying Edit Skinned Mesh Component](../../component-kind/edit-skinned-mesh-components#modifying-co
edit skinned mesh components側に書いてない
(自動化したい感じ出てきたね)

2024-10-14 07:57 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-uv-tile/index.md
> +You can use this component to easily remove polygons of models designed to hide some portion with UV Tile Discard feature of poiyomi or liltoon.
"Poiyomi and lilToon"の方が良い? 小文字統一でいく?

2024-10-14 07:57 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-uv-tile/index.md
> +This component works as like UV Tile Discard Mode to Vertex.
asなのかlikeなのか

2024-10-14 07:57 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-uv-tile/index.md
> +Please read [documentation of poiyomi's UV Tile Discard][UV Tile Discard] for more details about UV Tile Discard.
P vs p (同上)

2024-10-14 07:57 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-uv-tile/index.md
> +Unlike UV Tile Discard of lilToon or poiyomi, this component can use any UV Channel for UV Tile selection.
P vs p (同上)

2024-10-14 08:03 UTC, anatawa12 commented on .docs/content/docs/reference/remove-mesh-by-uv-tile/index.md
> +This component works as like UV Tile Discard Mode to Vertex.
works like UV Tile Discard with Vertex Mode

とかかな

2024-10-14 08:03 UTC, anatawa12 commented on .docs/content/docs/reference/remove-mesh-by-uv-tile/index.md
> +You can use this component to easily remove polygons of models designed to hide some portion with UV Tile Discard feature of poiyomi or liltoon.
あー公式に揃えましょう

2024-10-14 08:04 UTC, anatawa12 commented on .docs/content/docs/reference/remove-mesh-by-uv-tile/index.md
> +This component should be added to a GameObject which has a SkinnedMeshRenderer component. (Kind: [Modifying Edit Skinned Mesh Component](../../component-kind/edit-skinned-mesh-components#modifying-co
自動化良い方法が思いつかずスルーしてる

2024-10-14 08:25 UTC, anatawa12 commented on .docs/content/docs/reference/remove-mesh-by-uv-tile/index.md
> +This component should be added to a GameObject which has a SkinnedMeshRenderer component. (Kind: [Modifying Edit Skinned Mesh Component](../../component-kind/edit-skinned-mesh-components#modifying-co
90925e28f54168516d3d1bc46c0a04d4008ad778

2024-10-14 13:32 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-uv-tile/index.md
> +You'll see the list of material slots of the mesh.
これ合ってる?

2024-10-14 16:19 UTC, Sayamame-beans commented
実際の画面を確認できていませんが、とりあえず翻訳しました

2024-10-15 14:17 UTC, Sayamame-beans approved these changes

2024-10-15 14:18 UTC, merged