Improve OSC Support in Avatar Optimizer
anatawa12/AvatarOptimizer pull request #1306
Opened 2024-10-26 12:39 UTC by anatawa12

2024-10-30 04:19 UTC, anatawa12 commented
Prefix / Suffixも必要っぽい (https://docs.vrcft.io/docs/tutorial-avatars/tutorial-avatars-extras/parameters がsuffix判定ある)

2024-11-02 13:34 UTC, Sayamame-beans requested changes

2024-11-02 13:34 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Therefore, Avatar Optimizer will remove those parameters or components that create those parameters.
```suggestion
Therefore, Avatar Optimizer will remove those parameters or components that create those parameters, unintentionally for the users.
```

2024-11-02 13:34 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
```suggestion
And, some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
```
andで繋げられたりするかな…
2文が浮いててちょっと気になる

2024-11-02 13:34 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Currently this information is not actually used by Avatar Optimizer, but it is planned to be used in the future.
infoにする?

2024-11-02 13:34 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +We will discuss why Asset Description is needed for each information below.
discussなの?

2024-11-02 13:39 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
Andじゃないと思うなぁ

日本語では私は接続詞なくても違和感ない範囲だと思う。入れるとしたら特にとかかな

2024-11-02 13:41 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Currently this information is not actually used by Avatar Optimizer, but it is planned to be used in the future.
しなくていいと思う。必要な理由は？というところに現状はないけど将来はという説明が普通かと

2024-11-02 13:42 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +We will discuss why Asset Description is needed for each information below.
論ずるという意味のdiscussの用法

2024-11-02 13:46 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
1文目がどうしても浮いて見える
私の感覚の問題か…

2024-11-02 13:49 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
うーん

少し考えてみて「また」とかに相当するfurthermoreとかならいいのかな。前提の列挙だし

2024-11-02 13:50 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +We will discuss why Asset Description is needed for each information below.
discussってほどしっかり論じてないからdescribeとかのほうがいいか

2024-11-02 13:54 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Asset Description is a file that provides information about your assets to Avatar Optimizer.\
これ真上の行と被ってるね

2024-11-02 13:56 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Asset Description is a file that provides information about your assets to Avatar Optimizer.\
被っててまぁいいかってやった。でも消す？

2024-11-02 13:58 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +- Parameters Changed By External Tools: Parameters that can be changed by external tools, especially for OSC Tools.
これ改行とかじゃなくてコロンの方が良い感じ? (他のところで別の書き方してなかったっけ)

2024-11-02 14:02 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Asset Description is a file that provides information about your assets to Avatar Optimizer.\
真上過ぎて繰り返してもしょうがない気がして?

2024-11-02 14:05 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Asset Description is a file that provides information about your assets to Avatar Optimizer.\
そうね。消して下の行thoseを書き換えるか

2024-11-02 14:07 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +- Parameters Changed By External Tools: Parameters that can be changed by external tools, especially for OSC Tools.
あったっけ。あるのを覚えてないのでこの書き方になってる

2024-11-02 14:36 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +- Parameters Changed By External Tools: Parameters that can be changed by external tools, especially for OSC Tools.
https://github.com/anatawa12/AvatarOptimizer/blob/master/.docs/content/docs/reference/trace-and-optimize/index.md?plain=1
とか

2024-11-02 14:45 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
そういえばMeaningless Componentsのとこでもコンポーネント消す話してるね
被るのは別の話だからしょうがないとして、書き方は揃えてもいいのかも?

2024-11-02 14:51 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +- Parameters Changed By External Tools: Parameters that can be changed by external tools, especially for OSC Tools.
揃えようか

2024-11-02 14:56 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
前提が多いので同じ書き方は難しいと思う

2024-11-02 14:58 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
今日本語のほうで書き方検討してる
ちょっとまってて

2024-11-02 15:06 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
```suggestion
Furthermore, some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
```

こう？

2024-11-02 15:06 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +We will discuss why Asset Description is needed for each information below.
```suggestion
We will describe why Asset Description is needed for each information below.
```

2024-11-02 15:07 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +- Parameters Changed By External Tools: Parameters that can be changed by external tools, especially for OSC Tools.
```suggestion
- `Meaningless Components`\
  Components that should be ignored by Avatar Optimizer.
- `Parameters Read By External Tools`\
  Parameters that can be read by external tools, especially for OSC Tools.
- `Parameters Changed By External Tools`
  Parameters that can be changed by external tools, especially for OSC Tools.
```

こうかな

2024-11-02 15:07 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Avatar Optimizer uses those information to not excessively optimize user's avatar.
```suggestion
Avatar Optimizer uses information from Asset Description to not excessively optimize user's avatar.
```

こうかな

2024-11-02 15:12 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
日本語草案
```md
PhysBoneやContact Receiverのようなコンポーネントは、OSCツールで読み取り可能なパラメーターを生成します。
そのようなパラメーターは、Animator ControllerやExpression Parameterに登録しなくても、OSCツールから読み取り可能であることが知られています。\
しかし、Avatar Optimizerはそれらのパラメーターが単に使用されていないものなのか、OSCツールで読み取るためのものなのかを判別することができません。
そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。

これを防ぐために、OSCツールから読み取られる目的のパラメーターをAsset Descriptionで指定することができます。
```

2024-11-02 15:22 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
段落わけないほうが適切だと思うけど文はそうかな。

2024-11-02 15:28 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
空行なしの意?

2024-11-02 15:30 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
Yes

2024-11-02 15:36 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
分けた方が見やすい気が個人的にはするけど、やめとく?
![image](https://github.com/user-attachments/assets/10cb0ce9-42b2-4b53-847c-18972066f845)

2024-11-02 15:36 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
というか英語の方分かれてなかったっけ

2024-11-02 15:39 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
眠くて頭回りきってないかも

まとまった区切りじゃないな。分けて良い

2024-11-02 15:40 UTC, Sayamame-beans commented
日本語done

2024-11-02 15:58 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
これのあんのsayamameさんの見解がほしい

2024-11-02 16:12 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
英語のやつ?
日本語に寄せた文入れ替え含む書き換えした方が良いかもと思ってるけど、Furthermore案も良いとは思うかな

2024-11-02 16:13 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Some components like VRCPhysBone and VRCContactReceiver will create Animator Parameters that can be read by OSC Tools.
じゃぁ書き換えるか

2024-11-02 16:22 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.ja.md
> +しかし、Avatar Optimizerはそれらのパラメーターが単に使用されていないものなのか、OSCツールで読み取るためのものなのかを判別することができません。
```suggestion
しかし、Avatar Optimizerはそれらのパラメーターが単に使用されていないものなのか、OSCツールで読み取るためのものなのかを判別することができません。
```

これ「しかし」じゃないな。登録しなくていいから判断基準がないって話なので

2024-11-02 16:30 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +しかし、Avatar Optimizerはそれらのパラメーターが単に使用されていないものなのか、OSCツールで読み取るためのものなのかを判別することができません。
実運用上は登録要らないけど、Avatar Optimizerにとっては〜という意図だとしかしで繋がる気がしてる
変えるのは問題ない、どう変えるかな…

2024-11-02 16:30 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +To prevent Avatar Optimizer from removing those parameters, you can specify the parameters that are read by OSC Tools in Asset Description.
```suggestion
Components such as PhysBone and Contact Receiver will make parameters that can be read by OSC tools.
Such parameters are readable by the OSC tool without parameters defined on Animator Controller or Expression Parameter. \
Therefore, Avatar Optimizer is unable to determine whether those parameters are simply unused or intended to be read by the OSC tool.
Since OSC Tools are relatively minor, components that generate such parameters are removed if parameters are unused from anywhere on the avatar.

To prevent Avatar Optimizer from removing those parameters and components, you can specify the parameters that are read by OSC Tools in Asset Description.
```

@Sayamame-beans 再チェックお願いします。何度もすみません

2024-11-02 16:38 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.ja.md
> +しかし、Avatar Optimizerはそれらのパラメーターが単に使用されていないものなのか、OSCツールで読み取るためのものなのかを判別することができません。
逆説ならAvatarOptimizerのためにはする必要があるってことを書くべきで、理由じゃないと思う。

2024-11-02 16:38 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.ja.md
> +しかし、Avatar Optimizerはそれらのパラメーターが単に使用されていないものなのか、OSCツールで読み取るためのものなのかを判別することができません。
英語ノを見てそれに合わせて日本語も調整したい

2024-11-02 16:57 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +To prevent Avatar Optimizer from removing those parameters, you can specify the parameters that are read by OSC Tools in Asset Description.
without being definedとかじゃ微妙?

1文目がmakeで4文目がgenerateなのは揃えなくても良いのかな

2024-11-02 17:01 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +To prevent Avatar Optimizer from removing those parameters, you can specify the parameters that are read by OSC Tools in Asset Description.
変えた。揃えた。

2024-11-02 17:09 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
```suggestion
PhysBoneやContact Receiverのようなコンポーネントは、OSCツールで読み取り可能なパラメーターを生成します。
そのようなパラメーターは、Animator ControllerやExpression Parameterに登録しなくても、OSCツールから読み取り可能であることが知られています。\
そのため、Avatar Optimizerはそれらのパラメーターが単に使用されていないものなのか、OSCツールで読み取るためのものなのかを判別することができません。
殆どの場合はコンポーネントの消し忘れであり、OSCツールで使用されていることは比較的稀であるため、それらのパラメーターがアバター上で全く使われていない場合にはコンポーネントが削除されることになります。
```

2024-11-02 17:10 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
"殆どの場合はコンポーネントの消し忘れであり、" 明示したくない

2024-11-02 17:19 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +To prevent Avatar Optimizer from removing those parameters, you can specify the parameters that are read by OSC Tools in Asset Description.
OSC Toolは単数で良い?

`In most cases, components are left because of forgetting to remove, and used by OSC Tools is relatively minor, so components that make such parameters are removed if parameters are unused from anywhere on the avatar.`
とか?
(due toの方が好き?)

2024-11-02 17:19 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
わかった

2024-11-02 17:21 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
というか非常に稀とは思ってない。

2024-11-02 17:24 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
OSCツール自体があんまり稀みたいな言い方も若干渋い気はするので、試しに絞ってみたver
```suggestion
PhysBoneやContact Receiverのようなコンポーネントは、OSCツールで読み取り可能なパラメーターを生成します。
そのようなパラメーターは、Animator ControllerやExpression Parameterに登録しなくても、OSCツールから読み取り可能であることが知られています。\
そのため、Avatar Optimizerはそれらのパラメーターが単に使用されていないものなのか、OSCツールで読み取るためのものなのかを判別することができません。
登録されていないパラメーターがOSCツールで使用されていることは比較的稀であるため、コンポーネントが生成するパラメーターがアバター上で全く使われていない場合にはコンポーネントが削除されることになります。
```

2024-11-02 17:29 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +To prevent Avatar Optimizer from removing those parameters, you can specify the parameters that are read by OSC Tools in Asset Description.
toolsにした。

> (due toの方が好き?)

はどゆこと？

2024-11-02 17:30 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +To prevent Avatar Optimizer from removing those parameters, you can specify the parameters that are read by OSC Tools in Asset Description.
消し忘れ

2024-11-02 17:39 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +To prevent Avatar Optimizer from removing those parameters, you can specify the parameters that are read by OSC Tools in Asset Description.
そのほうが明確化。そうする

2024-11-02 17:41 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
比較的少ないって意図だったけど稀のほうがいいかな

2024-11-02 17:44 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
あー、日本語は少ないでも良いね

2024-11-02 17:46 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
まぁいいとは思う。minorが稀にした理由少し気になりはするけど

2024-11-02 17:48 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
rarelyに引っ張られた
ツール使用は"マイナー"って言えるけどね

2024-11-02 17:49 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
なんかghの更新ラグが多いな、、、

2024-11-02 17:51 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
> 使用されていることは比較的少ないため

やっぱり違和感ある気もする
ﾆﾎﾝｺﾞﾑｽﾞｶｼｲ

2024-11-02 17:52 UTC, Sayamame-beans approved these changes
まあいっか(思いつかず)

2024-11-02 17:52 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、そのようなパラメーターを生成するコンポーネントは、アバター上のどこからも使われていないものであるとして削除されてしまいます。
違和感わからん、、、

2024-11-02 17:56 UTC, merged