Docs
anatawa12/AvatarOptimizer pull request #1335
Opened 2024-11-07 11:08 UTC by anatawa12

Fix #1321
Fix #1207
Fix #1229
Fix #1321

2024-11-08 05:19 UTC, anatawa12 commented
#1337 もやる

2024-11-13 05:39 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.ja.md
>  詳細については以下のドキュメントを参照してください。
詳細については〜の中に移動したほうがいいかもな。

2024-11-13 09:11 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +実際、1.8.0で追加されたRemove Mesh in Box invertオプションは、boxの意味を変更するため、1.7以前のみを想定したツールとは互換性がありません。
```suggestion
コンポーネントの設定変更はコンポーネントを追加した直後に行う場合のみサポートされており、既にGameObject上に存在しているコンポーネントに対する設定変更はサポートされていません。
これは、将来のバージョンで追加された機能が、既存のコンポーネントの設定内容と互換性がない可能性があるためです。

例えば、v1.8.0で追加された`AAO Remove Mesh in Box`コンポーネントの反転オプションを変更すると、設定される箱による効果が変わってしまうため、v1.7以前のみを想定して作成されているツールと互換性がなくなってしまいます。

将来のバージョンで追加されるデフォルトで有効な機能との互換性を保つためにも、コンポーネントの設定変更を行う際はご注意ください。
その他の詳細については以下のドキュメントを参照してください。
```

なんか迷走してきた

2024-11-13 09:28 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.ja.md
> +実際、1.8.0で追加されたRemove Mesh in Box invertオプションは、boxの意味を変更するため、1.7以前のみを想定したツールとは互換性がありません。
将来のデフォルトでオンとの互換性はInitializeの債務なのでここに書くのは違うと思う

2024-11-13 10:56 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +実際、1.8.0で追加されたRemove Mesh in Box invertオプションは、boxの意味を変更するため、1.7以前のみを想定したツールとは互換性がありません。
ふむふむ

2024-11-13 12:07 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
>  詳細については以下のドキュメントを参照してください。
あー、そもそもここじゃなくて下の方にってこと?

2024-11-13 12:17 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
>  詳細については以下のドキュメントを参照してください。
その方向性で調整する方が良いかも

2024-11-14 02:16 UTC, anatawa12 commented
レビュー途中だけど #1144 追加します

2024-11-14 14:44 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.ja.md
> +なお、非破壊ツールの場合については、正しくない実行順で処理が行われた場合に、Avatar Optimizerがコンポーネントを誤って削除してしまわないように、従来通り`IVRCSDKPreprocessAvatarCallback`やNDMFの実行パスでコンポーネントを削除することを推奨します。
NDMFを使用するでいいか。

2024-11-22 10:42 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.ja.md
>  詳細については以下のドキュメントを参照してください。
```suggestion
```

2024-11-23 03:41 UTC, Sayamame-beans requested changes

2024-11-23 03:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +これは、将来追加される機能が既存のコンポーネントの設定と互換性がない可能性があるためです。
```suggestion
コンポーネントの設定変更はコンポーネントを追加した直後に行う場合のみサポートされており、既にGameObject上に存在しているコンポーネントに対する設定変更はサポートされていません。
これは、将来のバージョンで追加された機能が、既存のコンポーネントの設定内容と互換性がない可能性があるためです。
```
15行目と16行目で"追加時の設定変更"と書くのも考えてる(明確化のため)

2024-11-23 03:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +実際、1.8.0で追加されたRemove Mesh in Box invertオプションは、指定されたboxの意味を変更するため、1.7以前のみを想定したツールとは互換性がありません。
```suggestion
例えば、v1.8.0で追加された`AAO Remove Mesh in Box`コンポーネントの反転オプションを変更すると、設定される箱による効果が変わってしまうため、v1.7以前のみを想定して作成されているツールと互換性がなくなってしまいます。
```

2024-11-23 03:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +なお、非破壊ツールの場合については、正しくない実行順で処理が行われた場合に、Avatar Optimizerがコンポーネントを誤って削除してしまわないように、従来通り`IVRCSDKPreprocessAvatarCallback`やNDMFの実行パスでコンポーネントを削除することを推奨します。
未適用っぽい

2024-11-23 03:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.md
未調整

2024-11-23 11:32 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.ja.md
> +実際、1.8.0で追加されたRemove Mesh in Box invertオプションは、指定されたboxの意味を変更するため、1.7以前のみを想定したツールとは互換性がありません。
"変更すると"の書き方にするなら"有効にすると"のほうがいいかも

2024-11-23 13:04 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.ja.md
> +実際、1.8.0で追加されたRemove Mesh in Box invertオプションは、指定されたboxの意味を変更するため、1.7以前のみを想定したツールとは互換性がありません。
異論なければ

2024-11-24 11:46 UTC, Sayamame-beans commented
他の場所だけれど、2点抜けてることがあったから足したい
- Manual Bakeについてどこかで言及
  - 今はhard limitに引っ掛かったときの話でしか出てきてないっぽい
- Remove Mesh By Mask、作成押したら新規生成されるから、基本それで足りる旨を書きたい
  - (メインテクスチャを複製してマスクにしている例を観測したため。UV表示されてるし必須ではない気がする)

2024-11-24 13:29 UTC, anatawa12 commented
Manual Bake、Hard Limitくらいしか使わなくない？

2024-11-24 13:30 UTC, Sayamame-beans commented
> Manual Bake、Hard Limitくらいしか使わなくない？

VRMとか

2024-11-27 06:31 UTC, anatawa12 commented
> 他の場所だけれど、2点抜けてることがあったから足したい
> 
>     * Manual Bakeについてどこかで言及
>       
>       * 今はhard limitに引っ掛かったときの話でしか出てきてないっぽい
> 
>     * Remove Mesh By Mask、作成押したら新規生成されるから、基本それで足りる旨を書きたい
>       
>       * (メインテクスチャを複製してマスクにしている例を観測したため。UV表示されてるし必須ではない気がする)

これってさやまめさんがやると認識してたけど、私がやってくださいってことだった？

2024-11-27 06:54 UTC, Sayamame-beans commented
忘れてた

2024-11-27 07:43 UTC, anatawa12 commented
今月中にマージ & リリースしたいので、模試間に合わなさそうであればできれば入れないで一旦リリースにしたい。(どうせバグ報告来るのでそれの修正リリースがあとに来るので)

2024-11-27 10:58 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.md
> +This is because some future functionality might be incompatible with the existing component configuration.
ここ、functionalityであってる? (意図通り?)

2024-11-27 11:18 UTC, Sayamame-beans commented on .docs/content/_index.md
> +### With VCC/ALCOM (Recommended) {#installation-vcc}
```suggestion
### With VCC / ALCOM (Recommended) {#installation-vcc}
```
空白入れた方が見やすい可能性あるかも
任せる

2024-11-27 11:18 UTC, Sayamame-beans commented on .docs/content/_index.md
> +2. Add Avatar Optimizer to your project from VCC/ALCOM.
同上

2024-11-27 11:21 UTC, Sayamame-beans commented
FAQのOSCの話、Asset Descriptionにパラメーター情報追加したときに更新忘れてるっぽい
変えて良さそう(お願いします)

2024-11-27 12:16 UTC, Sayamame-beans commented
> > 他の場所だけれど、2点抜けてることがあったから足したい
> > ```
> > * Manual Bakeについてどこかで言及
> >   
> >   * 今はhard limitに引っ掛かったときの話でしか出てきてないっぽい
> > 
> > * Remove Mesh By Mask、作成押したら新規生成されるから、基本それで足りる旨を書きたい
> >   
> >   * (メインテクスチャを複製してマスクにしている例を観測したため。UV表示されてるし必須ではない気がする)
> > ```
> 
> これってさやまめさんがやると認識してたけど、私がやってくださいってことだった？

やりました(その他の変更点も含めてレビューお願いします 🙏 )

2024-11-27 12:46 UTC, anatawa12 commented on .docs/content/docs/developers/component-api/index.md
> +This is because some future functionality might be incompatible with the existing component configuration.
future featureだと見た目が悪いなって機能の意味の単語でfunctionalityを選んだけどなんかいいのあるかな

2024-11-27 12:48 UTC, anatawa12 commented on .docs/content/_index.md
> +2. Add Avatar Optimizer to your project from VCC/ALCOM.
いれようか。

2024-11-27 12:51 UTC, Sayamame-beans commented on .docs/content/docs/developers/component-api/index.md
> +This is because some future functionality might be incompatible with the existing component configuration.
"将来実装される機能"って丁寧に書いちゃうのも手ではあるけれど、まあ微妙よね…
意味通ってるならまあそのままでも良いのかも("機能性"って出てきたからちょっと意味変わるのかなと思った)

2024-11-27 12:53 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +アバターのGameObjectを右クリックして出てくるメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、非破壊ツールによる処理が適用されたアバターを手動で生成することができます。
敵お要されたアバターを生成じゃなくて、"非破壊ツールを適用できます"のほうがユーザがやりたいことに近い気がする。機能の説明としては正しいんだけど。

faqには "非破壊ツールによる処理を手動で適用することができます。 " ってある。

2024-11-27 12:54 UTC, anatawa12 commented on .docs/content/_index.md
> +2. Add Avatar Optimizer to your project from VCC/ALCOM.
```suggestion
2. Add Avatar Optimizer to your project from VCC / ALCOM.
```

2024-11-27 12:59 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +アバターのGameObjectを右クリックして出てくるメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、非破壊ツールによる処理が適用されたアバターを手動で生成することができます。
それは見たんだけど(というかそこから持ってきたのではあるんだけど)、アバターを生成するって内容が含められなくて困ってた(faqの方は箇条の方に入ってた、ここは適当な場所が文中しかない)

2024-11-27 13:00 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +アバターのGameObjectを右クリックして出てくるメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、非破壊ツールによる処理が適用されたアバターを手動で生成することができます。
下に複製して適用しますってあるからそれで十分じゃないかなと思った

2024-11-27 13:11 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +アバターのGameObjectを右クリックして出てくるメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、非破壊ツールによる処理が適用されたアバターを手動で生成することができます。
まあ…そうかも?

2024-11-27 13:18 UTC, anatawa12 commented
OSC更新しました。

2024-11-27 13:44 UTC, Sayamame-beans requested changes

2024-11-27 13:44 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +アバターのGameObjectを右クリックして出てくるメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、非破壊ツールによる処理が適用されたアバターを手動で生成することができます。
```suggestion
アバターのGameObjectを右クリックして出てくるメニューの`NDM Framework`から`Manual bake avatar`をクリックすると、非破壊ツールによる処理を手動で適用することができます。
```

2024-11-27 13:44 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +You can use `NDM Framework/Manual bake avatar` on the context menu of the Avatar GameObject to manually generate the avatar with applied non-destructive tools.
```suggestion
You can use `NDM Framework/Manual bake avatar` on the context menu of the Avatar GameObject to apply non-destructive tools manually.
```

2024-11-27 13:44 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +仮定が正しいとは限らないため、PhysBone / Contact ReceiverコンポーネントをOSCギミックに使用している場合には、[Asset Description]ファイルを作成し、[Parameters Read By External Tools]を設定してください。
```suggestion
この仮定は正しいとは限らないため、PhysBone / Contact Receiverコンポーネントが(AnimatorやExpression Menuを使用せずに)OSCギミックで使用されている場合には、[Asset Description]ファイルを作成し、[Parameters Read By External Tools]を設定してください。
```

2024-11-27 13:44 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +もしよろしければ、[GitHub]、[NDMF Discord]、[Fediverse (Misskey / Mastodon)][Fediverse]、[Twitter]などでお知らせください。
```suggestion
そのギミックが公開・販売されているような場合には、そのギミックとAAOの互換性を改善するために、作成した Asset Descriptionファイルを共有していただけると助かります。
また、Asset Description を将来の Avatar Optimizer に組み込むことで、そのギミックが正しく動作するようになるかもしれません。
もしよろしければ、[GitHub]、[NDMF Discord]、[Fediverse (Misskey / Mastodon)][Fediverse]、[Twitter]などでお知らせください。
```

2024-11-27 14:03 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +もしよろしければ、[GitHub]、[NDMF Discord]、[Fediverse (Misskey / Mastodon)][Fediverse]、[Twitter]などでお知らせください。
また、ではないかな。共有してほしい理由 目的なので。

2024-11-27 14:26 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +もしよろしければ、[GitHub]、[NDMF Discord]、[Fediverse (Misskey / Mastodon)][Fediverse]、[Twitter]などでお知らせください。
こう？

2024-11-27 23:08 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +もしよろしければ、[GitHub]、[NDMF Discord]、[Fediverse (Misskey / Mastodon)][Fediverse]、[Twitter]などでお知らせください。
そうかな。

2024-11-28 03:04 UTC, Sayamame-beans approved these changes
2点だけ

2024-11-28 03:04 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +If you like, please contact us on [GitHub], [NDMF Discord], [Fediverse (Misskey / Mastodon)][Fediverse], or [Twitter].
```suggestion
If you would like to, please contact us on [GitHub], [NDMF Discord], [Fediverse (Misskey / Mastodon)][Fediverse], or [Twitter].
```

2024-11-28 03:04 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +Asset Description を将来の Avatar Optimizer に組み込むことで、そのギミックが正しく動作するようになるかもしれません。
```suggestion
そのAsset Descriptionを将来のAvatar Optimizerに組み込むことにより、そのギミックが正しく動作するようになるかもしれません。
```

2024-11-28 03:06 UTC, anatawa12 commented
> (あとオフトピだけどBoothページの説明更新忘れてるかも)

はどういう糸化聞いてなかった

2024-11-28 03:07 UTC, Sayamame-beans commented
連絡方法とかメッシュ結合のこととか言及書いてあったから若干更新した方が良いのかも?って
画像はまあどっちでもいい(最適化結果変わってるかもだけど)

2024-11-28 03:29 UTC, Sayamame-beans commented
とりあえずmerge可能です
また何かあったら変えるかもだけど一旦良いと思う

2024-11-28 04:14 UTC, anatawa12 commented
merge~ RC打ちます

2024-11-28 04:14 UTC, merged