Remove mesh by blend shape
anatawa12/AvatarOptimizer pull request #283
Opened 2023-08-07 07:30 UTC by anatawa12

Closes #43

Follow up #275

2023-08-07 10:03 UTC, anatawa12 commented
![Uploading image.png…]()

2023-08-08 11:54 UTC, Sayamame-beans requested changes

2023-08-08 11:54 UTC, Sayamame-beans commented on Localization/ja.po
> +"もし頂点がこの値より大きく選択されたBlendShapeのいずれかに動かされていたら、その頂点が削除されます。\n"
webの説明に揃えるか、或いは、
```suggestion
"選択されたブレンドシェイプのいずれかによって頂点がこの値より大きく動かされている場合、その頂点は削除されます。\n"
```

2023-08-08 11:54 UTC, Sayamame-beans commented on Localization/ja.po
> +"もし予期せぬ頂点が削除されたらこの値を大きくしてみてください。もし思った頂点が削除されてなかったらこの多胎を小さくしてみてください。\n"
```suggestion
"意図していない頂点が削除されてしまった場合はこの値を大きくしてみてください。思った通りに頂点が削除されなかった場合はこの値を小さくしてみてください。\n"
```

2023-08-08 11:54 UTC, Sayamame-beans commented on Localization/ja.po
> +"の値は通常、小さいです。"
```suggestion
"通常、この値は小さな数値になります。"
```
suggestも微妙にしっくり来ていません。

2023-08-08 15:29 UTC, anatawa12 commented on Localization/ja.po
> +"の値は通常、小さいです。"
"こ"が抜けてるのはtypoですね

もしかしてtooltipに小さな値である事いらない...?

2023-08-08 15:45 UTC, Sayamame-beans commented on Localization/ja.po
> +"の値は通常、小さいです。"
tooltipというよりはweb側という感じもありますが、補足としてはここにあっても嬉しいものではあると思いますね。

2023-08-08 15:56 UTC, anatawa12 commented on Localization/ja.po
> +"の値は通常、小さいです。"
とりあえずこのまま適用してなんかいいのあったらそっちに切り替えるか

2023-08-08 15:58 UTC, Sayamame-beans approved these changes

2023-08-08 16:02 UTC, merged