Animator Layer Parser
anatawa12/AvatarOptimizer pull request #343
Opened 2023-08-20 10:17 UTC by anatawa12

2023-08-21 14:32 UTC, anatawa12 commented
ReportingObjectをもっとつけてあげるべきでもあると思う

2023-08-22 08:58 UTC, anatawa12 commented
mergeAsNewLayer、propのMerge使ってるけど正しくないな。NewLayer側がAlwaysAppliedならそれを適用するべきなので。要修正

2023-08-22 08:59 UTC, anatawa12 commented
またBlendTreeのパースがこれでいいかは怪しいので要確認。加算とかってどう行われてるのか

2023-08-22 11:16 UTC, anatawa12 commented
Direct BlendTreeだと加算できるっぽい？

2023-08-22 15:42 UTC, anatawa12 commented
Direct BlendTreeがだめなの直した。

2023-08-22 16:19 UTC, anatawa12 commented
TODO: Animation Componentの対応

2023-08-22 16:45 UTC, anatawa12 commented
`System.InvalidOperationException: Collection was modified; enumeration operation may not execute.`が起きる書き方してるので要review & check

2023-08-22 17:43 UTC, anatawa12 commented on CHANGELOG-PRERELEASE.md
> +- Support for Layered Animator Parser `#343`
Advanced Animator Parserに書き換えて`Advanced Animator Parser`の説明数行入れる

2023-08-22 18:47 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +                    if (layer.syncedLayerIndex == -1)
additiveかみてないのあんま良くない気がする

2023-08-22 18:58 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +        /// Fallback AnimatorController Parser but always assumed as partially applied
コメントにadditiveやdirect blendtreeで稀に壊れるけど著しくレアだからなおさんよって書く?

2023-08-22 19:29 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +                    merged.MakeAllVariable();
前処理で(fallback parserレベルのでいいと思う) 変更されてないParamを探してWeight1固定を探してあげたいゲド今やる必要はないな

2023-08-22 19:30 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +                    parsedMotions = CollectStates(layer.stateMachine)
override処理してなくない?

2023-08-22 19:35 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
> +                                return prop.ConstValue.CompareTo(blendShapeValues[i]) == 0;
compare toでいいのか自信がない
要確認

2023-08-22 19:39 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/ModificationsContainers.cs
> +        ModificationsContainer ToMutable();
これいるんかな

2023-08-22 19:46 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/ModificationsContainers.cs
> +    readonly struct ImmutableModificationsContainer : IModificationsContainer
デバッグ用途でシリアライズ手段ほしい

2023-08-23 05:54 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +                    parsedMotions = CollectStates(layer.stateMachine)
01c9257f

2023-08-23 05:57 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +        /// Fallback AnimatorController Parser but always assumed as partially applied
0f3233a1

2023-08-23 06:06 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
> +                                return prop.ConstValue.CompareTo(blendShapeValues[i]) == 0;
よさそう。ほかも書き換えるかな

2023-08-23 06:11 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
> +                                return prop.ConstValue.CompareTo(blendShapeValues[i]) == 0;
なかった

2023-08-23 07:12 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/ModificationsContainers.cs
> +        ModificationsContainer ToMutable();
あったほうがコピー適度に減らせそう

2023-08-23 07:15 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +                    if (layer.syncedLayerIndex == -1)
ここじゃねぇ

2023-08-23 07:15 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +                mergedController.MergeAsNewLayer(parsedMotions.MergeContainersSideBySide(), alwaysAppliedLayer);
additiveかみてないの良くないと思う。

2023-08-23 07:27 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +                mergedController.MergeAsNewLayer(parsedMotions.MergeContainersSideBySide(), alwaysAppliedLayer);
67c74e3 でAdditiveの対応入れた

2023-08-23 07:36 UTC, anatawa12 commented on CHANGELOG-PRERELEASE.md
> +- Support for Layered Animator Parser `#343`
057f9c506bd8c5b5da7bf903df80a4155991fad3

2023-08-23 07:43 UTC, anatawa12 commented
testで #333 で作ったframework使いたいのでmasterのバージョンをnext minorにしてmergeしてupdate branchします

2023-08-23 13:56 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +                    layer.defaultWeight != 1 && i != 0 && (externallyWeightChanged?.Contains(i) ?? true);
Weightが0/1以外になったらvariableにしないとあかん気がするのでちゃんと確認しないとだめ

2023-08-23 17:50 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +                    layer.defaultWeight != 1 && i != 0 && (externallyWeightChanged?.Contains(i) ?? true);
externallyWeightChangedを`NotSet | ZeroOnly | OneOnly | ZeroOne | Variable`に分けて、`defaultWeight`とマージして、`ZeroOnly`ならレイヤ自体skip, `OneOnly`ならalwaysApplied, `Variable`ならこのレイヤーのmodificationsをVariableにしたい。

2023-08-23 17:50 UTC, anatawa12 commented
最低限のbasicなテストは追加した。

externallyWeightChanged周りのテストはまだやってない。

あとAdditive系でまだやんないといけない気がする

2023-08-23 20:44 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +        private IEnumerable<AnimatorState> CollectStates(AnimatorStateMachine stateMachineIn)
これTransitonでつながってないとかmutedのみなState除外していい気がする

2023-08-24 10:15 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +                    layer.defaultWeight != 1 && i != 0 && (externallyWeightChanged?.Contains(i) ?? true);
やった

2023-08-24 10:31 UTC, anatawa12 commented on Test~/AnimatorParser/AnimatorTest.cs
> +            Assert.That(properties["blendShape.shape11"], Is.EqualTo(AnimationProperty.ConstPartially(100)));
Transitionの関係でVariableですねこれ

2023-08-24 10:38 UTC, anatawa12 commented on Test~/AnimatorParser/AnimatorTest.cs
> +            Assert.That(properties["blendShape.shape11"], Is.EqualTo(AnimationProperty.ConstPartially(100)));
いや、元の値が100じゃないとPartiallyApplied意味を成さないのでもんだいなし

2023-08-24 11:30 UTC, anatawa12 commented
doc書くか

2023-08-24 11:49 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +  最適化内容を決めるため、AAOはAnimatorControllerを解析します。このオプションを有効にすると、AnimatorControllerのレイヤー構造とBlendTree構造を解析するAdvanced Animator Parserを用いて解析します。このオプションを無効にすると、AnimationClipのみを解析するFallback Animator Parserが使用されま
構造をパースするからもっと最適化できるとかって話書くべきかね

2023-08-24 12:09 UTC, anatawa12 commented
todo animation部分クラス分ける

2023-08-24 13:10 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +  最適化内容を決めるため、AAOはAnimatorControllerを解析します。このオプションを有効にすると、AnimatorControllerのレイヤー構造とBlendTree構造を解析するAdvanced Animator Parserを用いて解析します。このオプションを無効にすると、AnimationClipのみを解析するFallback Animator Parserが使用されま
現状だと、Fallback Animator Parserのメリットがシンプルさで、デメリットがDirect BlendTreeの解析無し、レイヤー解析無し(非明示)、ということだけが記述されているかと思います。

2023-08-24 13:23 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +  最適化内容を決めるため、AAOはAnimatorControllerを解析します。このオプションを有効にすると、AnimatorControllerのレイヤー構造とBlendTree構造を解析するAdvanced Animator Parserを用いて解析します。このオプションを無効にすると、AnimationClipのみを解析するFallback Animator Parserが使用されま
Advancedの無効化のメリットは原則なく、バグったときにFallbackに一時的にするくらいを想定してます。

シンプルなので比較的バグりづらいってのがメリットかなぁと

2023-08-24 13:31 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  With this option enabled, Advanced Animator Parser,
suggestion、if this option **is** enabledのほうが良さそう？

2023-08-24 13:59 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +  最適化内容を決めるため、AAOはAnimatorControllerを解析します。このオプションを有効にすると、AnimatorControllerのレイヤー構造とBlendTree構造を解析するAdvanced Animator Parserを用いて解析します。このオプションを無効にすると、AnimationClipのみを解析するFallback Animator Parserが使用されま
なるほど

2023-08-24 14:06 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +  最適化内容を決めるため、AAOはAnimatorControllerを解析します。このオプションを有効にすると、AnimatorControllerのレイヤー構造とBlendTree構造を解析するAdvanced Animator Parserを用いて解析します。このオプションを無効にすると、AnimationClipのみを解析するFallback Animator Parserが使用されま
「Fallback Animator ParserはDirect BlendTreeを正しく解析しませんが、動作がシンプルで安定しています。」と言う程Advanced Animator Parserが安定していないとは思わない(実装初期は何でも若干不安定ですが)ので、うーんって感じですね

2023-08-24 14:08 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  With this option enabled, Advanced Animator Parser,
あ、抜けました(一度cancelしたので)

2023-08-24 14:08 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +  最適化内容を決めるため、AAOはAnimatorControllerを解析します。このオプションを有効にすると、AnimatorControllerのレイヤー構造とBlendTree構造を解析するAdvanced Animator Parserを用いて解析します。このオプションを無効にすると、AnimationClipのみを解析するFallback Animator Parserが使用されま
`Fallback Animator Parserはよりシンプルですが、Direct BlendTreeを正しく解析しません。`消したほうがいい？

2023-08-24 14:20 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +  最適化内容を決めるため、AAOはAnimatorControllerを解析します。このオプションを有効にすると、AnimatorControllerのレイヤー構造とBlendTree構造を解析するAdvanced Animator Parserを用いて解析します。このオプションを無効にすると、AnimationClipのみを解析するFallback Animator Parserが使用されま
言いたいことは分かるんですが(単純な方がバグは起きづらい)、上手く説明出来ないですね…
Advancedが不安定ならまだしも、そうではないので…
しかし、残しているのはそのため(何らかの理由でFallbackが必要な可能性を想定して。或いはこれまでとの互換性。)だと思うので、何かは書かないと多分マズいですよね…

2023-08-24 14:23 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +  最適化内容を決めるため、AAOはAnimatorControllerを解析します。このオプションを有効にすると、AnimatorControllerのレイヤー構造とBlendTree構造を解析するAdvanced Animator Parserを用いて解析します。このオプションを無効にすると、AnimationClipのみを解析するFallback Animator Parserが使用されま
ちょっと変えてみました

2023-08-24 14:35 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +  最適化内容を決めるため、AAOはAnimatorControllerを解析します。このオプションを有効にすると、AnimatorControllerのレイヤー構造とBlendTree構造を解析するAdvanced Animator Parserを用いて解析します。このオプションを無効にすると、AnimationClipのみを解析するFallback Animator Parserが使用されま
> Fallback Animator Parserは旧式の処理であり、Direct BlendTreeを正しく解析しません。通常、このオプションは無効化の必要ありません

このくらい安定方向の話書かないでいい気がしてきました

2023-08-24 14:44 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +  最適化内容を決めるため、AAOはAnimatorControllerを解析します。このオプションを有効にすると、AnimatorControllerのレイヤー構造とBlendTree構造を解析するAdvanced Animator Parserを用いて解析します。このオプションを無効にすると、AnimationClipのみを解析するFallback Animator Parserが使用されま
良さそうかな

英語は私が直したほうがいいかな

2023-08-24 14:45 UTC, Sayamame-beans requested changes

2023-08-24 14:45 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  parses AnimationClips. Fallback Animator Parser is simpler but will parse Direct BlendTree incorrectly.
```suggestion
  parses AnimationClips. Fallback Animator Parser is an legacy process, so it will parse Direct BlendTree incorrectly.
  Normally, you do not need to disable this option.
```

2023-08-24 14:47 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  parses AnimationClips. Fallback Animator Parser is simpler but will parse Direct BlendTree incorrectly.
ありがとうございます

2023-08-25 05:02 UTC, Sayamame-beans requested changes

2023-08-25 05:02 UTC, Sayamame-beans commented on CHANGELOG-PRERELEASE.md
> +    AAO can freeze BlendShapes which always be animated to constant value on the final later.
```suggestion
    AAO can freeze BlendShapes which are always finally animated to a constant value.
```

2023-08-25 05:02 UTC, Sayamame-beans commented on CHANGELOG.md
> +    AAO can freeze BlendShapes which always be animated to constant value on the final later.
```suggestion
    AAO can freeze BlendShapes which are always finally animated to a constant value.
```

2023-08-25 05:07 UTC, Sayamame-beans commented
その他、気になる点は特に内容に見えました

2023-08-25 18:00 UTC, Sayamame-beans approved these changes

2023-08-26 07:14 UTC, anatawa12 commented
大丈夫でしょう。merge~

2023-08-26 07:14 UTC, merged