feat(remove-mesh-by-blendshape/editor): auto set blendshape weight
anatawa12/AvatarOptimizer pull request #389
Opened 2023-08-28 09:20 UTC by anatawa12

Fixes #387

2023-08-28 10:24 UTC, Sayamame-beans commented
これはどういう場合に使うどういった機能なのでしょうか?

2023-08-28 11:07 UTC, anatawa12 commented
削除対象の頂点がわかりづらくなるためそれをけいげんするための機能です

(手動でweight100にするのだとミスが発生しやすい)

2023-08-28 11:55 UTC, Sayamame-beans commented
ふむ、確認用の機能ということですね。
現状のtooltipだと、日英ともに、対象BlendShapeをトグルすると自動的に100/0にする(何故?)という感じでよく分からず…

2023-08-28 11:56 UTC, Sayamame-beans commented
挙動をあまり理解出来ていないので、文章が組めていません。

2023-08-28 12:08 UTC, anatawa12 commented
チェックしたときにWeight = 100にしてチェック外したときにweight = 0にするってシンプルな動作です

2023-08-28 12:25 UTC, Sayamame-beans commented
あ～
当該オプションを有効にした時、削除対象として選択したblendshapeを100にすることで、100で縮むタイプのものをプレビューする感じですかね?
0で縮むタイプは無いのでしたっけ?

2023-08-29 15:26 UTC, Sayamame-beans requested changes
ちょっとしっくり来てないですが、一旦これで

2023-08-29 15:26 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "BlendShapeのウェイトをトグル時に自動的に設定する"
```suggestion
msgstr "プレビューのために、BlendShapeの値を自動的に変更する"
```

2023-08-29 15:26 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "ウェイトを100か0にトグルしたときに自動的に設定します。"
```suggestion
msgstr "BlendShapeの値を自動的に100か0に設定します。"
```

2023-08-29 15:32 UTC, Sayamame-beans commented on Localization/en.po
> +msgstr "Automatically set BlendShape weight when toggle"
when toggle、情報量が少なくて無い方が良いと思っちゃいました(何をtoggleなのか、tooltipを見てさえよくわからず…)
他の表現を考えてみます

2023-08-29 15:39 UTC, anatawa12 commented on Localization/en.po
> +msgstr "Automatically set BlendShape weight when toggle"
toggle(verb)はチェックボックスを変えることを指すのであるチェックボックスがblendshapeのとこれしかないから`when toggle`が必要十分だと認識してました

2023-08-29 15:43 UTC, Sayamame-beans commented on Localization/en.po
> +msgstr "Automatically set BlendShape weight when toggle"
であれば尚更これがよく分からないですね…
> 変更時にのみ更新される

このオプションを有効にすると、(即座に)チェックされているものは100に、チェックされていないものは0になると認識しています。
…選択していないものならビルド結果には作用しないということを明示したいのです?

2023-08-29 15:46 UTC, anatawa12 commented on Localization/en.po
> +msgstr "Automatically set BlendShape weight when toggle"
このオプションが有効な間、on/offを切り替えたものが100/0に設定されるという動作です。

2023-08-29 15:48 UTC, Sayamame-beans commented on Localization/en.po
> +msgstr "Automatically set BlendShape weight when toggle"
となると、有効にしてから変更を加えなければどのBlendShapeもプレビューされないと…ふむ

2023-08-29 15:56 UTC, Sayamame-beans commented on Localization/en.po
> +msgstr "Automatically set BlendShape weight when toggle"
```suggestion
msgstr "Automatically set BlendShape weight for preview when toggled"
```

2023-08-29 16:02 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "BlendShapeのウェイトをトグル時に自動的に設定する"
```suggestion
msgstr "プレビューのために、切り替えたBlendShapeの値を自動的に変更する"
```

2023-08-29 16:24 UTC, Sayamame-beans requested changes

2023-08-29 16:24 UTC, Sayamame-beans commented on Localization/en.po
> +msgstr "Automatically set weight to 100 or 0 when you toggle this settings."
```suggestion
msgstr "Automatically set weight to 100 or 0 for blendshapes which are toggled while this option is enabled."
```

2023-08-29 16:24 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "BlendShapeの値を自動的に100か0に設定します。"
```suggestion
msgstr "このオプションが有効な間にブレンドシェイプの指定を切り替えた場合、その値を自動的に100か0に設定します。"
```

2023-08-29 16:24 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "プレビューのために、切り替えたBlendShapeの値を自動的に変更する"
```suggestion
msgstr "プレビューのために、切り替えたブレンドシェイプの値を自動的に変更する"
```
全体で表記揺れが見られますが、同一コンポーネント内で一旦統一したいと思いました。

2023-08-29 16:38 UTC, Sayamame-beans approved these changes
多分良いんじゃないでしょうか。
引っ掛かる気持ちが無いわけではないので、また何かあれば修正しましょう…

2023-08-29 16:38 UTC, merged