Migrate from unused bones by reference
anatawa12/AvatarOptimizer pull request #430
Opened 2023-09-06 15:53 UTC by anatawa12

Fixes #429
Fixes #291

2023-09-06 16:03 UTC, anatawa12 commented on Localization/ja.po
> +msgstr "チェックされている場合、親がactiveなendボーンを削除しません。"
コピペしたけど要改善。activeってなんだよなので。

2023-09-06 16:09 UTC, anatawa12 commented on Localization/ja.po
> +msgstr "チェックされている場合、親がactiveなendボーンを削除しません。"
docsの方で一応改善しましたがもっといいのがある気がするけどとりあえずsuggstionにだけします

```suggestion
msgstr "チェックされている場合、親が削除されていないendボーンを削除しません。"
```

2023-09-06 16:16 UTC, anatawa12 commented on CHANGELOG.md
> +  - Newly introduced `Remove Unused Objects` does same thing with more powerful algorithm!
```suggestion
  - Newly introduced algorithm of`Remove Unused Objects` does same thing!
```

2023-09-07 08:04 UTC, Sayamame-beans requested changes

2023-09-07 08:04 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "変換完了"
```suggestion
msgstr "移行完了"
```

2023-09-07 08:04 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "Trace and Optimizeへの変換が完了しました！"
```suggestion
msgstr "Trace and Optimizeへの移行が完了しました!"
```

2023-09-07 08:36 UTC, anatawa12 commented on CHANGELOG.md
> +  - With new algorithm, you can preserve end bones (`#430`)
```suggestion
  - With new algorithm, you can preserve end bones (`#430`)
  - You may use `Use Legacy GC` to use legacy algotythm for Remove Unused Objects in `Advanced Settings` (`#419`)
```

2023-09-07 12:36 UTC, merged

2023-09-07 12:42 UTC, Sayamame-beans commented on Localization/ja.po
> +"UnusedBonesByReferencesToolは、使用されていないボーンなどに対してより賢い処理を行うTrace and Optimizeに置き換えられました!\n"
PR出します