ContactBase is accidentally erased by Remove unsed Objects Automatically.
anatawa12/AvatarOptimizer pull request #438
Opened 2023-09-07 19:34 UTC by ReinaS-64892

Remove unsed Objects Automaticallyでコンタクトが使用されている物にも関わらず、自動で削除されてしまっていたためこのPullRequestのドラフトを書きました

そのコンタクトが、アニメーションで常にオフでない場合
ContactSenderは消すべきではなく、ほかのアバターに影響するため専用のような使い方がある、
ContactReceiverは、アニメーションのプロパティなどで、影響するか否かを見つつ消すべきで、アニメーションコントローラーが、そのパラメーターを持っていて、それを使用しているかなどで判断すればよいと思います。

今の状態でパラメーターのパーサーがあるのか私にはわからないので、それの回避策として"EntryPointComponent"を有効にすることで回避していますが、
パラメーターが使用されているかどうかのパーサーがある、または書く意思があるならこの回避策は使うべきではないので、PullRequestはクローズしてください。

2023-09-07 19:37 UTC, anatawa12 commented
ふつーにミスですねありがとうございます。

2023-09-07 19:38 UTC, anatawa12 requested changes

2023-09-07 19:38 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
> +                    (collector, deps, component) => { });
余計なdiffが入り込んでるようなのでforce pushて集成してください

2023-09-07 19:40 UTC, anatawa12 commented
force pushで修正する際、http://conventionalcommits.org に合うようなコミットメッセージにしていただきたいです

2023-09-08 03:08 UTC, ReinaS-64892 commented
余計なdiffの排除とコミットメッセージの[conventionalcommits](http://conventionalcommits.org/)に合わせてみましたがこれであっていますか？

2023-09-08 04:06 UTC, anatawa12 commented
ありがとうございます。良さそうですね。changelogつけてマージさせていただきます。

2023-09-08 04:14 UTC, merged