docs(tutorial/ja): add T&O at top and add remove mesh with blendshape
anatawa12/AvatarOptimizer pull request #479
Opened 2023-09-16 10:16 UTC by anatawa12

Fixes #436
Fixes #437

とりあえずドラフトです。良さそうになったら英語に訳します。

2023-09-16 15:11 UTC, Sayamame-beans requested changes

2023-09-16 15:11 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +服に隠れている素体部分など、見えない部分のメッシュを削除すると描画負荷、BlendShapeの処理負荷などが減るため軽量化になります。
```suggestion
服で隠れていたりして見えないような部分のメッシュを削除すると、見た目に影響させずに描画負荷やBlendShapeの処理負荷などを減らして軽量化することができます。
```

2023-09-16 15:11 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +AvatarOptimizerではそのために多くの素体で含まれているシュリンク用のBlendShapeを用いてメッシュを削除できます！
```suggestion
これを簡単に実現するために、AvatarOptimizerでは多くの素体に含まれている貫通防止用のBlendShapeを利用してメッシュを削除することができます！
```

2023-09-16 15:11 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +思ってもいない部位が削除されないかを確認するため、`プレビューのために切り替えたブレンドシェイプの値を自動的に変更する`にチェックし、
```suggestion
想定外の部位が削除されてしまわないかを確認するには、`プレビューのために切り替えたブレンドシェイプの値を自動的に変更する`にチェックし、
```

2023-09-16 15:11 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +下のBlendShapeの一覧から削除したい部位のシュリンク用BlendShapeを選択しましょう！
```suggestion
下のBlendShapeの一覧から削除したい部位の貫通防止用BlendShapeを選択しましょう！
```

2023-09-16 15:56 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +- 使われないPhysBone等の削除
等に含むものにはConstraintがあるんですがあんま使われなぃので具体的な方には書いてない感じです

2023-09-16 16:09 UTC, anatawa12 commented on .docs/README.md
> +  upgraded to 1.06 with replacing GUID of prefab to its of 1.05 (`3b37219c818344b47a491cca0686c190`) and
GUIDを変更したAnonちゃんってことなのでbyじゃないと思ってます

2023-09-16 16:12 UTC, Sayamame-beans commented on .docs/README.md
> +  upgraded to 1.06 with replacing GUID of prefab to its of 1.05 (`3b37219c818344b47a491cca0686c190`) and
"元が1.05で、GUIDを変更(1.06のGUIDを1.05のものに)することによって1.06にupgradeしたAnon.unity"と思ったのでbyにしたんですけど微妙でした?

2023-09-16 16:12 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +- 使われないPhysBone等の削除
なるほど…

2023-09-16 16:49 UTC, anatawa12 commented on .docs/README.md
> +  upgraded to 1.06 with replacing GUID of prefab to its of 1.05 (`3b37219c818344b47a491cca0686c190`) and
Anonちゃん自身のGUID変更です

2023-09-16 16:51 UTC, Sayamame-beans commented on .docs/README.md
> +  upgraded to 1.06 with replacing GUID of prefab to its of 1.05 (`3b37219c818344b47a491cca0686c190`) and
そのように認識しています("Anon.unity"と書いてあったからそのまま表記しただけです)

2023-09-16 18:05 UTC, anatawa12 commented on .docs/README.md
> +  upgraded to 1.06 with replacing GUID of prefab to its of 1.05 (`3b37219c818344b47a491cca0686c190`) and
"1.06に以下の変更を加えたもの"的な感じにしたくて、"XXXすることで更新したもの"というイメージじゃない認識

2023-09-16 21:47 UTC, anatawa12 commented on .docs/README.md
> +  upgraded to 1.06 with replacing GUID of prefab to its of 1.05 (`3b37219c818344b47a491cca0686c190`) and
vrc上での議論の結果

```suggestion
  upgraded to 1.06 with replacing GUID of prefab to with that 1.05 (`3b37219c818344b47a491cca0686c190`) and 
```

2023-09-16 22:20 UTC, Sayamame-beans commented on .docs/README.md
> +- Screenshots in tutorial are taken with Anon.unity. The Anon.unity is made with originally with [Anon] 1.05 and
これは適用忘れですかね…?

2023-09-17 06:33 UTC, anatawa12 commented on .docs/README.md
> +- Screenshots in tutorial are taken with Anon.unity. The Anon.unity is made with originally with [Anon] 1.05 and
半分そう。半分はどっちでもいいと思ってる感じ。適用します

2023-09-17 09:07 UTC, anatawa12 commented on .docs/README.md
> +  upgraded to 1.06 with replacing GUID of prefab to with that 1.05 (`3b37219c818344b47a491cca0686c190`) and
```suggestion
  upgraded to 1.06 with replacing GUID of prefab with that of 1.05 (`3b37219c818344b47a491cca0686c190`) and 
```

2023-09-18 08:29 UTC, Sayamame-beans requested changes
とりあえず日本語だけ再チェック。
英語は後で見ます。

2023-09-18 08:29 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +Skinned Meshを結合すると個別にオン・オフできなくなりますが、結合することで軽量化になります！
```suggestion
Skinned Meshを統合すると個別にオン・オフできなくなりますが、統合することで軽量化に繋がります！
```

2023-09-18 08:29 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +下のBlendShapeの一覧から削除したい部位の貫通防止用BlendShapeを選択しましょう！
```suggestion
削除したい部位の貫通防止用BlendShapeを下の一覧から選択しましょう！
```

2023-09-19 10:19 UTC, Sayamame-beans requested changes

2023-09-19 10:19 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +To easily achieve this, AvatarOptimizer can remove meshes using the BlendShapes which shrinks parts of body included in many avatars!
```suggestion
To make this easier, AvatarOptimizer allows you to remove polygons with BlendShapes which many avatars have for shrinking parts of the body!
```

2023-09-19 10:19 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +With Avatar Optimizer, You can those optimization with adding `Trace And Optimize` to the Avatar Root!
```suggestion
With AvatarOptimizer, these optimizations can be performed automatically by simply adding a `Trace And Optimize` to the Avatar Root!
```

よく見ると英語版説明の他の箇所では"component"表記を使っていないっぽい?

2023-09-19 10:19 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Let's add `Remove Mesh By BlendShape` to Body Mesh!
前述の理由から、componentを付けるか否か

2023-09-19 10:19 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Enable `Automatically set BlendShape weight for preview when toggled` to make sure that unexpected parts of the body are not removed,
```suggestion
Enable `Automatically set BlendShape weight for preview when toggled` to make sure that unintended parts of the body are not removed, and
```

2023-09-19 10:19 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Select the BlendShapes which shrinks parts of body which you want to remove from the list of BlendShapes below!
```suggestion
select the BlendShapes, which shrink the parts of the body you want to remove, from the BlendShapes list below!
```

2023-09-19 11:00 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +  - If a PhysBone that does not need to be swayed is enabled, for example a PhysBone where the mesh that exists as the target of the shaking is always disabled, an extra computational load is incurre
There be ~の形なら複数のほうがいいと思ってます。

2023-09-19 11:04 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Merging Skinned Mesh will not allow you to turn them on and off individually, but combining them will save some rendering weight!
たしかにcostのほうが良さそうですね

2023-09-19 11:05 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +  - If a PhysBone that does not need to be swayed is enabled, for example a PhysBone where the mesh that exists as the target of the shaking is always disabled, an extra computational load is incurre
```suggestion
  - If there are enabled PhysBones which do not need to be swayed (e.g., the swaying target mesh is always disabled), extra computational load is caused.
```
ついでにanが不要そうだったので取り除きました

2023-09-19 11:08 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +With Avatar Optimizer, You can those optimization with adding `Trace And Optimize` to the Avatar Root!
多分なしで書いてますね。明確な理由は多分ないです

2023-09-19 11:09 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Select the BlendShapes which shrinks parts of body which you want to remove from the list of BlendShapes below!
関係代名詞の制限用法なので,は入れてはいけない認識です

2023-09-19 11:17 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Select the BlendShapes which shrinks parts of body which you want to remove from the list of BlendShapes below!
選びうるBlendShapeにはshrinkしないものもあり得るということでしょうか

2023-09-19 11:18 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Select the BlendShapes which shrinks parts of body which you want to remove from the list of BlendShapes below!
いや、theがある程度ではBlendShapeに掛かる関係代名詞として重いということか…

2023-09-19 11:21 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +  - For BlendShapes with non-zero weight, there are processing load so freezing BlendShape will reduce processing load.
なしに揃えたいかな

2023-09-19 11:23 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Select the BlendShapes which shrinks parts of body which you want to remove from the list of BlendShapes below!
「BlendShapeのうち、消したい部分をシュリンクしてるの」という名詞句なので制限用法だと思う

2023-09-19 11:23 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Select the BlendShapes which shrinks parts of body which you want to remove from the list of BlendShapes below!
というかtheはないほうが良さそうかも

2023-09-19 11:27 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Select the BlendShapes which shrinks parts of body which you want to remove from the list of BlendShapes below!
```suggestion
select the BlendShapes from the BlendShapes list below that shrink the parts of the body you want to remove!
```
前後を入れ替えてthatにしてみました
正直自信は無いですが、少なくとも元のままだと、fromがどこに掛かるのかなど色々読みづらいと思っています

2023-09-19 11:33 UTC, Sayamame-beans requested changes
とりあえず1文だけ
load → cost については一旦後回しにします(変更点が多いので)

2023-09-19 11:33 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +  - Even if the weight is zero, removing the BlendShapes will reduce size of avatars.
```suggestion
  - Even if the weight is zero, removing BlendShapes will reduce the size of avatars.
```

2023-09-19 11:33 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Select the BlendShapes which shrinks parts of body which you want to remove from the list of BlendShapes below!
> というかtheはないほうが良さそうかも

反映しました

2023-09-19 11:42 UTC, anatawa12 commented
load -> constはこっちでまとめてやります

2023-09-19 11:54 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +- Merging bones being animated nor swayed with PhysBones
根拠がなくてコメントが遅くなりました。多分これはnot A or Bにすべきでnorジャなさそうですね。
```suggestion
- Merging bones which is not animated or swayed with PhysBones
```

2023-09-19 11:55 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +Reduce polygons with shrinking which shrinks parts of body
TODO: Anchor置く

2023-09-19 11:57 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +To easily achieve this, AvatarOptimizer can remove meshes using the BlendShapes which shrinks parts of body included in many avatars!
`for shrinking parts of the body`の部分は制限的にしたくて、`many avatars have`は非制限的だと思うので、
`BlendShapes for shrinking parts of the body, which many avatars have`とかのほうがいいかも

2023-09-19 12:10 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +To easily achieve this, AvatarOptimizer can remove meshes using the BlendShapes which shrinks parts of body included in many avatars!
```suggestion
To make this easier, AvatarOptimizer allows you to remove polygons with BlendShapes for shrinking parts of the body, which many avatars have!
```

2023-09-19 12:14 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +- Merging bones being animated nor swayed with PhysBones
前回norが使われていて、軽く調べて問題があると判断出来なかったのがあったのでそのままにしてました
https://github.com/anatawa12/AvatarOptimizer/blob/a65e4bb24da065893cdb64dc2d99ab03abdaf074/CONTRIBUTING.md?plain=1#L31

2023-09-19 12:15 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +With Avatar Optimizer, You can those optimization with adding `Trace And Optimize` to the Avatar Root!
"component"表記の追加は気が向いたらPRにします

2023-09-19 12:23 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +貫通防止用BlendShapeを利用してメッシュを減らす
@anatawa12

2023-09-19 12:25 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +貫通防止用BlendShapeを利用してメッシュを減らす
119f0d66

2023-09-19 12:26 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +貫通防止用BlendShapeを利用してメッシュを減らす
"ポリゴン数"じゃなくて"ポリゴン"の方が良かったですか? (ポリゴン数の方が馴染むかなと思ったのですが)

2023-09-19 12:32 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +貫通防止用BlendShapeを利用してメッシュを減らす
分かりました

2023-09-19 12:32 UTC, Sayamame-beans approved these changes

2023-09-19 12:33 UTC, merged