chore: avoid problematic material slot in MergeSkinnedMesh
anatawa12/AvatarOptimizer pull request #508
Opened 2023-09-24 13:52 UTC by nekobako

Fix #507
最適化に直接関係ないような、最適化した影響でバグを踏むので関係あるような、微妙なラインです。
Unity 2022 では直っているようなので、もし必要なければそのまま Close してください。

2023-09-24 14:21 UTC, anatawa12 requested changes

2023-09-24 14:21 UTC, anatawa12 commented on Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
> +        private void FixSubMeshIndexMap(OptimizerSession session, MeshInfo2[] meshInfos, int[][] subMeshIndexMap, List<Material> materials)
Indexのマップを処理するのではなくシンプルに https://github.com/anatawa12/AvatarOptimizer/pull/508/files#diff-ec07713a95a708f652c05b204be55c9ae11cdf7d524c514158f0efe60143d183R124 あたりに `target.SubMeshes.Insert(4, new SubMesh());` する形にしていただきたいです

2023-09-24 14:55 UTC, nekobako commented on Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
> +        private void FixSubMeshIndexMap(OptimizerSession session, MeshInfo2[] meshInfos, int[][] subMeshIndexMap, List<Material> materials)
https://github.com/anatawa12/AvatarOptimizer/pull/508/files#diff-ec07713a95a708f652c05b204be55c9ae11cdf7d524c514158f0efe60143d183R74-R75 の処理がずれないようにするとなると余計にややこしくなりそうですがどうでしょう・・？

2023-09-24 15:03 UTC, anatawa12 commented on Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
> +        private void FixSubMeshIndexMap(OptimizerSession session, MeshInfo2[] meshInfos, int[][] subMeshIndexMap, List<Material> materials)
AAOのObjectMappingは二段階のmove propertyを処理できるのでinsertのところで`RecordMoveProperties`を別途呼び出してください。

2023-09-24 15:54 UTC, nekobako commented on Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
> +        private void FixSubMeshIndexMap(OptimizerSession session, MeshInfo2[] meshInfos, int[][] subMeshIndexMap, List<Material> materials)
なるほどです。対応しましたが合っていますでしょうか？

2023-09-24 23:39 UTC, anatawa12 commented on Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
> +        private void FixSubMeshIndexMap(OptimizerSession session, MeshInfo2[] meshInfos, int[][] subMeshIndexMap, List<Material> materials)
ごめんなさい。指示したつもりの場所とリンクがずれてたようです。

マージ処理のforeach終了後にシフト処理を入れて欲しいという意図でした

2023-09-25 00:36 UTC, anatawa12 reviewed
方針は良さそうに見えます。

2023-09-25 00:36 UTC, anatawa12 commented on Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
> +                    }
meshInfosをforeachする必要ないと思います。イカの形で多分十分化とお思います。

```suggestion
                mappings.Clear();
                for (var i = 4; i < target.SubMeshes.Length; i++)
                {
                    mappings.Add(($"m_Materials.Array.data[{i}]",
                               $"m_Materials.Array.data[{i + 1}]"));                    
                }
```

2023-09-25 00:36 UTC, anatawa12 commented on Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
> +                            .Any(x => targetSubMeshIndices.Any(y => x.target == y.renderer && x.propertyName == $"m_Materials.Array.data[{y.src}]")))
`targetSubMeshIndices`をHashSetにしてcontainsにできませんか？

2023-09-25 10:13 UTC, nekobako commented on Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
> +                    }
対応しました。
二段階の move property は各 meshInfo ではなく target に対してやればよいということだったのですね。
元の Renderer を見る必要があるアニメーションのチェックだけ Destroy する前に残しています。

2023-09-25 10:14 UTC, nekobako commented on Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
> +                            .Any(x => targetSubMeshIndices.Any(y => x.target == y.renderer && x.propertyName == $"m_Materials.Array.data[{y.src}]")))
対応しました。とてもすっきりしました。

2023-09-25 11:06 UTC, merged