stable API
anatawa12/AvatarOptimizer pull request #623
Opened 2023-10-19 03:17 UTC by anatawa12

2023-10-20 19:38 UTC, Sayamame-beans requested changes
これレビューじゃなくてpatch規模の編集かもしれない…
すごく確認漏れがありそう。
日本語は英語が終わってからで。

your components、toolが主語の文脈ではits componentsな気がして若干悩んでます。

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +When you want to remove your component with `IVRCSDKPreprocessAvatarCallback`, please refer [this section](#improve-compatibility-non-ndmf-based).
```suggestion
If you want to remove your components with `IVRCSDKPreprocessAvatarCallback`, please refer [this section](#improve-compatibility-non-ndmf-based).
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +When you want to register your component to Avatar Optimizer, please refer [this section][register-component].
```suggestion
If you want to register your components to Avatar Optimizer, please refer [this section][register-component].
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +When you want to remove your component with `IVRCSDKPreprocessAvatarCallback`, please refer [this section](#improve-compatibility-non-ndmf-based).
そもそもこの部分を無くして、70行目の with IVRC～あたりに`#improve-compatibility-non-ndmf-based`を付けたほうが良いような感じもします。

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +When you want to register your component to Avatar Optimizer, please refer [this section][register-component].
`#register-component`の話は、他の部分と同様に71行目に統合しても良さそうです。(ここは無くす)

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +[^NDMF]: [NDMF], Non-Destructive Modular Framework, is a framework for running non-destructive build plugins when
```suggestion
[^NDMF]: [NDMF], Non-Destructive Modular Framework, is a framework for executing non-destructive build plugins when 
```
原文がどこかにあったらすみません。他の文ではexecuteなので揃えました。

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +If your tool want to keep your component after processing Avatar Optimizer, or want to removed by Avatar Optimizer,
```suggestion
If your tool wants to keep your components after Avatar Optimizer process, or not to be removed by Avatar Optimizer,
```
後者、notが抜けているような気がしました

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +you can register your component to Avatar Optimizer to tell about your component.
```suggestion
you can register your components to Avatar Optimizer to tell about your components.
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +To call APIs in Avatar Optimizer, first, Please make assembly definition file[^asmdef] if your tool doesn't have.
```suggestion
First, to call APIs of Avatar Optimizer, please make an assembly definition file[^asmdef] if your tool doesn't have.
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +register your component to Avatar Optimizer.
```suggestion
register your components to Avatar Optimizer.
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +please [register your component][register-component] to Avatar Optimizer.
```suggestion
please [register your components][register-component] to Avatar Optimizer.
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +please [register your component][register-component] to Avatar Optimizer.
```suggestion
please [register your components][register-component] to Avatar Optimizer.
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Because Avatar Optimizer didn't have public API piror to 1.6.0 and will break api in 2.0.0,
```suggestion
Because Avatar Optimizer doesn't have public API prior to 1.6.0 and will break in 2.0.0, 
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +it's recommended to add version range like `[1.6,2.0)` (or more stricter like `[1.7,2.0)`).
1.7以上にした方が良い理由があるのでしょうか…? (厳密性のためになる理由が掴めていません)

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Then, define `CompoinentInformation` for your component in your assembly.
```suggestion
Then, define `ComponentInformation` for your component in your assembly.
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +In `CollectDependency`, you should register build-time or run-time dependencies of your component.
```suggestion
In `CollectDependency`, you should register build-time or run-time dependencies of your component.  
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +In `CollectMutations`, you should register any mutation your component may do.
```suggestion
In `CollectMutations`, you should register any mutation your component may do.  
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Next, add `com.anatawa12.avatar-optimizer.api.editor` to assembly references in asmdef file.
```suggestion
Next, add `com.anatawa12.avatar-optimizer.api.editor` to assembly references in asmdef file.  
```

2023-10-20 19:38 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +If your component is just for keeping data for your in-editor tools, both will be empty method.
```suggestion
If your component is just for keeping data for your in-editor tool, both will be empty method.
```

2023-10-21 04:03 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Currently NDMF executes Optimization passes in order `-1025`, JUST before VRCSDK's `RemoveAvatarEditorOnly` callback so
Optimization phaseのpassは複数あるのでoptimization passesかoptimization phaseだと思う

2023-10-21 04:04 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +### For other tools that just holds data with components. {#non-destructive-tools}
たしかにnon-いらないね

2023-10-21 04:07 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +If your tool want to keep your component after processing Avatar Optimizer, or want to removed by Avatar Optimizer,
後者は実際にAAOに削除されてもいいものを指してるので`or to be removed`で正しいです

2023-10-21 04:08 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +it's recommended to add version range like `[1.6,2.0)` (or more stricter like `[1.7,2.0)`).
将来のAAOでAPI追加したときに1.7以上にしたくなる事があるので、それでもいいよって書いてるだけ。

2023-10-21 04:10 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +[^NDMF]: [NDMF], Non-Destructive Modular Framework, is a framework for running non-destructive build plugins when
一応元は https://ndmf.nadena.dev/

2023-10-21 04:12 UTC, anatawa12 commented on .docs/content/docs/tutorial/_index.md
> +title: Developers
yes

2023-10-21 04:18 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Currently NDMF executes Optimization passes in order `-1025`, JUST before VRCSDK's `RemoveAvatarEditorOnly` callback so
ふむ。まあそうですよね…
他の場所は単数が多かったと思いますが、そこは問題ない感じです?

2023-10-21 04:20 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +If your tool want to keep your component after processing Avatar Optimizer, or want to removed by Avatar Optimizer,
ふむ
うーん…

2023-10-21 04:20 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +it's recommended to add version range like `[1.6,2.0)` (or more stricter like `[1.7,2.0)`).
あー

2023-10-21 04:22 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Currently NDMF executes Optimization passes in order `-1025`, JUST before VRCSDK's `RemoveAvatarEditorOnly` callback so
どっちかというとNDMFのOptimiationを指してるの全部pass -> phaseにしたほうが良さそうなのでまとめてやります

2023-10-21 04:37 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +When you want to remove your component with `IVRCSDKPreprocessAvatarCallback`, please refer [this section](#improve-compatibility-non-ndmf-based).
まとめました

2023-10-21 05:00 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +When you want to register your component to Avatar Optimizer, please refer [this section][register-component].
まとめた

2023-10-21 05:03 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Because Avatar Optimizer didn't have public API piror to 1.6.0 and will break api in 2.0.0,
過去の話だからdidn't haveじゃない？

2023-10-21 05:16 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Avatar Optimizer process. Avatar Optimizer does most thing in Optimization pass
ここにおいてはbefore接続しのかたちのほうが自然だと思います

2023-10-21 05:24 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Because Avatar Optimizer didn't have public API piror to 1.6.0 and will break api in 2.0.0,
過去かと言われると微妙な気が少ししました(今も旧バージョンは存在するので)

2023-10-21 05:59 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Because Avatar Optimizer didn't have public API piror to 1.6.0 and will break api in 2.0.0,
ドキュメントの対象バージョンから相対的に見たら過去だと思う

2023-10-21 11:24 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +If your tool want to keep your component after processing Avatar Optimizer, or want to removed by Avatar Optimizer,
なるほど、理解しました
微妙に読みづらい気はしましたが、前後入れ替えも微妙ですし…

2023-10-30 06:53 UTC, Sayamame-beans requested changes
再び英語版です
抜けがあるかもしれません

2023-10-30 06:53 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Since Avatar Optimizer has Garbage Collection system for Components and others, Avatar Optimizer have to
```suggestion
Since Avatar Optimizer has Garbage Collection system for Components and others, Avatar Optimizer has to 
```
前reviewの適用忘れ?

2023-10-30 06:53 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Currently NDMF executes Optimization phase in order `-1025`, which is JUST before VRCSDK's `RemoveAvatarEditorOnly`
```suggestion
Currently, NDMF executes Optimization phase in order `-1025`, which is JUST before VRCSDK's `RemoveAvatarEditorOnly`
```
前reviewの適用忘れか、意図的か…?
NDMFに掛けていたとすれば、"Current NDMF"の方が良さそうです。

2023-10-30 06:53 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +If your tool holds some information with components and have no meaning on the build time,
```suggestion
If your tool holds some information with components and has no meaning on the build time, 
```
前reviewの適用忘れ?

2023-10-30 06:53 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +it's recommended to add version range like `[1.6,2.0)` (or more stricter like `[1.7,2.0)`).
その意図が現在の表現では伝わりづらいように感じています。
```suggestion
it's recommended to add version range like `[1.6,2.0)` (or stricter like `[1.7,2.0)` when following new APIs that can be available in the future).
```
例えばこんな感じにするのはどうでしょう?

2023-10-30 08:24 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +Currently NDMF executes Optimization phase in order `-1025`, which is JUST before VRCSDK's `RemoveAvatarEditorOnly`
Current NDMFにしますね

2023-10-30 08:59 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +it's recommended to add version range like `[1.6,2.0)` (or more stricter like `[1.7,2.0)`).
良さそうなので少し変えて適用しました

2023-10-30 09:08 UTC, Sayamame-beans requested changes

2023-10-30 09:08 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.md
> +(or stricter like `[1.7,2.0)` when you requires new APIs can be available in the future).
whichかthatは欲しい気がしました
```suggestion
(or stricter like `[1.7,2.0)` when you require new APIs which can be available in the future).
```
```suggestion
(or stricter like `[1.7,2.0)` when you require new APIs that can be available in the future).
```

2023-11-05 12:41 UTC, Sayamame-beans commented
残りreview: 日本語

2023-11-06 10:03 UTC, anatawa12 commented
READMEのほう、fedverseをあまり知らなかった時期なのでfedverseに揃えるが良さそう

2023-11-06 13:39 UTC, Sayamame-beans commented
日本語版見てて思ったんですけど、`improve-compatibility-ndmf-based`のところで、英語版で
> If your tool needs your components in Optimization phase, please execute

ってなってる部分が、日本語版だと何らかの処理を行う場合って感じになってるんですよね。
日英共にその後でコンポーネントの話が出てくることを考えると、この段階で英語版でコンポーネントの話が出てきてるのが不自然だったりしますか?

2023-11-06 14:39 UTC, anatawa12 commented
日本語版で"コンポーネントを用いて何かしらの処理を行う場合"ってすべきところが"何かしらの処理を行う場合"に略されてる方がダメそう

Optimization Phaseでなにかしたとしても、それがコンポーネントを見ない場合は問題ないので。(実際現行MAのGCGameObjects Phaseは順番指定ないけどコンポーネントを設定として使わないので問題がない)

2023-11-07 13:59 UTC, Sayamame-beans commented
なるほど
逆に、その次の部分で日本語版に"Avatar Optimizerよりあとに"とあるところは英語には無いみたいですね…

2023-11-08 09:57 UTC, Sayamame-beans commented
register-componentのところ、コンポーネント削除にも使うんです?

2023-11-08 10:20 UTC, anatawa12 commented
依存関係を一切ないと定義するとGCで消せるので一応そういう書き方してる。
情報を保持してるだけのコンポーネントの場合、ランタイム依存関係がないので消えます。

具体例としてはさてねあキセテネのComponentなんかはAAOにより(も)消えます

2023-11-08 10:24 UTC, anatawa12 commented
> つまり
Optimization Phaseで何かを行いたいという状況において
・AAOより先に実行する
・AAOにコンポーネントを登録して後に実行する
でしょうか?


気づいてなかった。そのとおりです。

2023-11-08 10:31 UTC, Sayamame-beans commented
> 依存関係を一切ないと定義するとGCで消せるので一応そういう書き方してる。 情報を保持してるだけのコンポーネントの場合、ランタイム依存関係がないので消えます。

他の部分では自分で消してねって書いてあるのに、ここではAAOに消してもらえる感じなのでちょっと気になって…
一旦そのままにしてあります

2023-11-08 10:33 UTC, Sayamame-beans requested changes
コミット参照
英語の方も少し変更があります

英語と日本語で整合性取れてるか分からないです
また、`register-component`が`##`と`###`で混ざっていてどちらか分かりませんでした。一旦`###`にしてあります。

気になる部分は指摘してください

2023-11-08 10:36 UTC, anatawa12 commented
データ保持用コンポーネントを消すだけのためにCallback追加したくないなら登録で消せるよーって話のつもりですね

登録のほうが面倒な気はしてきたので話し消してもいいのか

2023-11-08 14:23 UTC, Sayamame-beans commented
> ```
> we found errors in commit message of 21769c9db4f167bb386b8751aab53420c1a59417
>   unknown header type: review
> ```

docs(review)じゃないと駄目だったか…

2023-11-08 14:24 UTC, anatawa12 commented
register componentは`###` deyosasou

2023-11-08 15:09 UTC, anatawa12 commented
見た感じ問題なさそう。amendコミットでcommit message修正できます？無理であればラベルで除外してmergeでいいとおもいます

2023-11-08 15:17 UTC, Sayamame-beans commented
> データ保持用コンポーネントを消すだけのためにCallback追加したくないなら登録で消せるよーって話のつもりですね
> 
> 登録のほうが面倒な気はしてきたので話し消してもいいのか

これどうします?

2023-11-08 15:20 UTC, anatawa12 commented
読み直した感じ、消せるなら消して。嫌なら登録してって形に全部なってると思うので現状でgoだした。

2023-11-08 15:24 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-tool-compatible-with-aao/index.ja.md
>  このページでは以下の２つのことを説明します。
```suggestion
このページでは以下の2つのことを説明します。
```
半角に

2023-11-08 15:26 UTC, Sayamame-beans commented
明日最後に点検して問題なさそうならauto-merge掛けますね

2023-11-09 04:29 UTC, Sayamame-beans commented
見返してみて、現状
> ・AAOより先に実行する
> ・AAOにコンポーネントを登録して後に実行する

が並列になってるような書き方じゃないような気がしてきましたね…
AAOより先に実行する/先にコンポーネントを削除する が初めの提案として必ず出てきて、最後に「後から処理したいなら～」という話が少し出てくるようで…(improve-compatibility-ndmf-based, improve-compatibility-non-ndmf-based共に)

AAO的には多分、出来るだけAAOより先に処理して欲しいというところってことなんですよね～…?

2023-11-09 04:57 UTC, anatawa12 commented
> AAO的には多分、出来るだけAAOより先に処理して欲しいというところってことなんですよね～…?

YES。というのも現状のAPIで情報が不十分な場合がまぁ考えられるので。

2023-11-11 06:39 UTC, anatawa12 commented
そういえば、componentの話しかしてないからmake components of your tool compatible with avatar optimizerのほうがいいかもしれない(shader等別の話する記事生やすことに今後なるかもしれない)

2023-11-11 07:17 UTC, Sayamame-beans commented
あ〜〜

2023-11-13 01:45 UTC, anatawa12 commented
> そういえば、componentの話しかしてないからmake components of your tool compatible with avatar optimizerのほうがいいかもしれない(shader等別の話する記事生やすことに今後なるかもしれない)

これに合わせていじりました。すみません。

2023-11-13 02:00 UTC, Sayamame-beans commented
私が見るの遅かったのがアレなので大丈夫です
後で確認しますね

2023-11-20 10:00 UTC, Sayamame-beans requested changes
日本語版の再調整です

2023-11-20 11:42 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +もしコンポーネントがアバターに存在し、Avatar Optimizerが処理する時点でまだ存在している場合、そのコンポーネントはAvatar Optimizerと互換性が無い可能性があります。
アバターにあることは明確にしときたいかなぁ。シーン内の別のGameObjectは関係ないので

2023-11-20 14:19 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +もしコンポーネントがアバターに存在し、Avatar Optimizerが処理する時点でまだ存在している場合、そのコンポーネントはAvatar Optimizerと互換性が無い可能性があります。
なるほど

2023-11-20 14:20 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +もしコンポーネントがアバターに存在し、Avatar Optimizerが処理する時点でまだ存在している場合、そのコンポーネントはAvatar Optimizerと互換性が無い可能性があります。
```suggestion
Avatar Optimizerが処理する時点でアバターにコンポーネントが存在している場合、そのコンポーネントはAvatar Optimizerと互換性が無い可能性があります。
```

2023-11-20 23:54 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +コンポーネントを削除する方法はいくつかあります。
削除すること自体はあんまり特別なこと話してないのでいいかなぁと思ってる。registerは別ページからリンク貼るかもなとか思ってるのでこうしてます

2023-11-21 06:05 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +コンポーネントを削除する方法はいくつかあります。
なるほど…意図は理解しました
私としては、削除と登録の2手法があって片方だけ分かれてるのが気になった感じです

2023-11-21 06:24 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +コンポーネントを削除する方法はいくつかあります。
まぁバランスが悪いのはそうなのでうーんわけるかぁ

2023-11-21 08:47 UTC, Sayamame-beans requested changes

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +Please remove your components before Avatar Optimizer processes if your tool adds components to the avatar as possible.
```suggestion
Please remove your components before Avatar Optimizer processes as much as possible.
```

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +If you cannot, please register your components to Avatar Optimizer.
```suggestion
If you cannot remove some components, please register them to Avatar Optimizer.
```

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +If your tool is a non-destructive tool based on NDMF[^NDMF], removing your components before the Optimization phase
変更前はOptimization phaseにthe付けてなかったと思うのでちょっと気になりました(どちらでも良さそうではあります)

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +ツールがNDMFを使用していない非破壊ツールの場合は、NDMFのOptimization phaseより前にコンポーネントを削除することを推奨します。
```suggestion
ツールがNDMF[^NDMF]を使用していない非破壊ツールの場合は、NDMFのOptimization phaseより前にコンポーネントを削除することを推奨します。
```
英語版にはあったのでこっちにも追加

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +the NDMF's Optimization phase with `IVRCSDKPreprocessAvatarCallback` is recommended.
```suggestion
the NDMF's Optimization phase is recommended.
```

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +Current NDMF executes Optimization phase in order `-1025`, which is JUST before VRCSDK's `RemoveAvatarEditorOnly`
```suggestion
In this case, current NDMF executes Optimization phase in order `-1025`, which is JUST before VRCSDK's `RemoveAvatarEditorOnly`
```

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +callback, so your tool should remove components in `IVRCSDKPreprocessAvatarCallback` with smaller `callbackOrder`.
```suggestion
callback, so your tool should remove components with `IVRCSDKPreprocessAvatarCallback` with smaller `callbackOrder`.
```
with2回になるのは気になりますが、前者の部分が文章的にはinよりwithの方が良さそうです

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +You can remove your components with several ways.
> ここ、`コンポーネントを削除する {#remove-component}`とかした方が良い説がある?(登録はあるので)

日本語版と同

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +コンポーネントがデータを保持するためだけのものであれば、どちらも空にします。
```suggestion
```
英語版に合わせる場合

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +
```suggestion
```
同

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +ツールのコンポーネントをAvatar Optimizerの処理で削除したい、または残しておきたい場合、
```suggestion
ツールのコンポーネントをAvatar Optimizerの処理より後に残しておきたい場合、
```
英語版に合わせる場合

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +上記の`IVRCSDKPreprocessAvatarCallback`の順序を参照してください。
```suggestion
`IVRCSDKPreprocessAvatarCallback`の順序については上記を参照してください。
```
ちょっと違和感があったので修正。

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
> +コンポーネントを削除する方法はいくつかあります。
```suggestion
### コンポーネントを削除する {#remove-component}

コンポーネントを削除する方法はいくつかあります。
```

2023-11-21 08:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +You can remove your components with several ways.
```suggestion
### Removing your components {#remove-component}

You can remove your components with several ways.
```

2023-11-21 12:36 UTC, anatawa12 commented on .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
> +If your tool is a non-destructive tool based on NDMF[^NDMF], removing your components before the Optimization phase
考えた結果theだなと思ったのでこのまま行きます

2023-11-21 13:09 UTC, merged