chore: Wrap VRCSDK dependencies with AAO_VRCSDK3_AVATARS
anatawa12/AvatarOptimizer pull request #627
Opened 2023-10-19 16:03 UTC by kaikoga

2023-10-19 16:09 UTC, kaikoga commented on Runtime/AvatarTagComponent.cs
> +#endif
MEMO: Perhaps this should go to ndmf?

2023-10-23 00:45 UTC, anatawa12 requested changes
ありがとうございます

2023-10-23 00:45 UTC, anatawa12 commented on Editor/ObjectMapping/ObjectMappingContext.cs
> +#if AAO_VRCSDK3_AVATARS
`#if`はここじゃなくてSpecialMappingApplierの中にして欲しいです。非VRCSDKコンポーネントで必要になること考えられるので

(どっかのタイミングで ComponentInfoに移動すると思います)

2023-10-23 00:45 UTC, anatawa12 commented on Editor/AvatarGlobalComponentEditorBase.cs
>              ComponentValidation.RegisterValidator<AvatarGlobalComponent>(component =>
何かしら avatar rootであるvalidationを入れたいです。NDMFのavatar rootの確認API使えるならそれ使いたいです

2023-10-23 00:45 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +#endif
このままだとアバタールートにあるAnimator Componentを見ないので非VRCSDKアバターだとあまり良くないってなりそうな気がしてます。

別PR予定ならそれでOK

2023-10-23 00:45 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
> +#if AAO_VRCSDK3_AVATARS
ここも同様の理由でメソッド内部で`#if`して欲しいです。

2023-10-23 00:45 UTC, anatawa12 commented on Editor/Utils/Utils.cs
>  using VRC.Dynamics;
使用箇所が少ないので usingを`#if`ではなくfqnameにして欲しいです。

2023-10-23 00:45 UTC, anatawa12 commented on Test~/TestUtils.cs
>  using VRC.SDK3.Avatars.Components;
ここも使用数少ないのでfqnameにしてusingにしていただきたいです

2023-10-23 00:45 UTC, anatawa12 commented on Runtime/AvatarTagComponent.cs
> +#endif
可能ならNDMFで持っててほしいですね。`INdmfEditorOnly`とか

2023-10-23 04:48 UTC, anatawa12 commented
conflict mergeしました

2023-10-23 17:32 UTC, kaikoga commented
対応していきます

2023-10-23 17:55 UTC, kaikoga commented
```
we found errors in commit message of 796fe80bf0e1eaf1dd39e3cd92ac0e1990a6fbbf
  unknown header type: cosme
```

cosme なかったかーーーー

2023-10-23 17:55 UTC, kaikoga commented
https://github.com/anatawa12/conventional-commitlint/blob/bd2dbd207f86fe134bcb1760c6c474c158c2d6bb/src/main.rs#L240-L253

2023-10-23 18:12 UTC, kaikoga commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +#endif
そもそもVRCSDK3とVRMのみについてだけ考えると、アバタールートのAnimator Componentに設定されたアニメーションは使わない（VRCSDK3はアバタールート以外にAnimatorをつけられる一方でアバタールートはPlayable Layersがある、VRMにはアニメーションがない）ということもあり、 `#region AvatarDescriptor` だけ読んで丸ごと無視していましたが、もう少しちゃんとやった方が良さそうなのでやります。

2023-10-23 19:01 UTC, kaikoga commented on Editor/Utils/Utils.cs
>  using VRC.Dynamics;
f492d6a4a14e0ffcf567a7ac170e55d62fba5b78

2023-10-23 19:01 UTC, kaikoga commented on Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
> +#if AAO_VRCSDK3_AVATARS
f492d6a4a14e0ffcf567a7ac170e55d62fba5b78

2023-10-23 19:12 UTC, kaikoga commented on Editor/ObjectMapping/ObjectMappingContext.cs
> +#if AAO_VRCSDK3_AVATARS
自分の手元で既に必要そうなのを思い知らされましたが、VRM0/1のVRMBlendShapeProxy→BlendShapeAvatar→BlendShapeClip//Vrm10Instance→Vrm10Object→VRM10ObjectExpression→VRM10Expressionをちゃんと扱うとかなり大変なので、ファイルが分かれる気がします。 

（具体的には、AAOがMAから持ってきたAnimatorControllerのコピーと似たようなことを、複数のScriptableObjectにまたがってやることになります。MAで似たような処理をする必要が生じた時にAAOからMAにコピーするのは二度手間なので、別ライブラリにするか、ndmfに置いてもらおうかと思っています。）

2023-10-23 19:12 UTC, kaikoga commented on Editor/ObjectMapping/ObjectMappingContext.cs
> +#if AAO_VRCSDK3_AVATARS
それはそうと d679b5b970431f5a546a8e6d0bf8418a71bcef1f

2023-10-23 19:13 UTC, kaikoga commented on Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
> +#if AAO_VRCSDK3_AVATARS
d679b5b970431f5a546a8e6d0bf8418a71bcef1f

2023-10-23 19:13 UTC, kaikoga commented on Test~/TestUtils.cs
>  using VRC.SDK3.Avatars.Components;
f492d6a4a14e0ffcf567a7ac170e55d62fba5b78

2023-10-23 19:15 UTC, kaikoga commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +#endif
VRC / Non-VRC のAnimatorを扱えるように構成を見直しました 9d8b737c18a0afb3302e9addbd480575f0113f57

2023-10-23 19:24 UTC, kaikoga commented on Editor/AvatarGlobalComponentEditorBase.cs
>              ComponentValidation.RegisterValidator<AvatarGlobalComponent>(component =>
VRCSDKがUnity2022に移行した上でVRM対応が普通に使える状態になるまではAAO_VRCSDK3_AVATARS環境の挙動を変えるメリットが特にないので、状況が整うまで本対応を先送りにしたいと思います。 fc9e1dfadffbd5b460864fb6453ca4f513e40d3e

2023-10-24 01:54 UTC, anatawa12 commented on Editor/ObjectMapping/ObjectMappingContext.cs
> +#if AAO_VRCSDK3_AVATARS
:+1:

2023-10-24 01:56 UTC, anatawa12 commented on Editor/AvatarGlobalComponentEditorBase.cs
>              ComponentValidation.RegisterValidator<AvatarGlobalComponent>(component =>
わかりました。

2023-10-24 02:07 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AnimatorParser.cs
> +#endif
VRMについてはまぁHumanoidみてるから十分か。OKです

2023-10-24 02:13 UTC, anatawa12 requested changes

2023-10-24 02:13 UTC, anatawa12 commented on Runtime/AvatarTagComponent.cs
> +#endif
うーん再検討してましたがNDMFが持たないなら

```
#if AAO_VRCSDK3_AVATARS
        , VRC.SDKBase.IEditorOnly
#endif
```

のほうがいいと思いました。(他のと同様にusingをあまり#ifで囲いたくない)とりあえず放置してるとコンフリクトして面倒な気がするのでマージしたいのでこの形にしていただけますか？

2023-10-25 13:55 UTC, anatawa12 approved these changes
ありがとうございます

2023-10-25 13:55 UTC, merged