feat: Add VRM0 ComponentInfos
anatawa12/AvatarOptimizer pull request #652
Opened 2023-10-29 02:17 UTC by kaikoga

Parent Issue: #651

Defined VRM0 / VRM1 dependency infos because warnings.

2023-10-29 14:11 UTC, kaikoga commented
・ `UniHumanoid.Humanoid.BoneMap` はUniVRM最新版だとpublicだけど0.99.4の時点ではprivateなのでVRCSDKがUnity 2022になるまでの間はリフレクションが要る

2023-10-30 21:20 UTC, kaikoga commented
#663

2023-10-30 21:20 UTC, kaikoga commented
In particular, VRM0 SpringBone is HeavyBehaviour but VRM1 SpringBoneJoint is not!

2023-10-30 22:16 UTC, kaikoga commented
> CollectMutations

なんか生えてるー

2023-10-31 23:14 UTC, kaikoga commented
一旦リベースするか・・・

2023-11-02 19:59 UTC, kaikoga commented
VRCSDK3のLipSync / EyeLookに相当するVRMの機能がBlendShapeProxy(VRM0)/Expression(VRM1)を介しているので、ApplySpecialMapping()からSMRのBlend Shape Indexを扱う必要はなさそう！

2023-11-04 03:18 UTC, anatawa12 requested changes
遅くなりすみません。

2023-11-04 03:18 UTC, anatawa12 commented on CHANGELOG.md
> +- Improve support of UniVRM components `#652`
Addなきがします。`Improve support of projects without VRCSDK`もそうな気がするので後でやります

2023-11-04 03:18 UTC, anatawa12 commented on Editor/APIInternal/ComponentInfos.VRM0.cs
> +    internal class VRMBlendShapeProxyInformation : ComponentInformation<VRMBlendShapeProxy>
このコンポーネントがBlendShapeをいじるようですがCollectMutation/ApplySpecialMappingしないで問題ない感じですか？

2023-11-04 03:40 UTC, kaikoga commented on CHANGELOG.md
> +- Improve support of UniVRM components `#652`
このPRだけではVRMのサポートが不十分なのでこうなっています。 #653 とまとめた方が良ければそうします。

2023-11-04 03:46 UTC, anatawa12 commented on CHANGELOG.md
> +- Improve support of UniVRM components `#652`
まとめてほしいです

2023-11-04 03:49 UTC, kaikoga commented on Editor/APIInternal/ComponentInfos.VRM0.cs
> +    internal class VRMBlendShapeProxyInformation : ComponentInformation<VRMBlendShapeProxy>
AnimatorがCollectMutation/ApplySpecialMappingしていないのに合わせていて、VRMBlendShapeProxyがいじるBlendShapeの情報は全部BlendShapeClipに入っていてAnimatorParser経由で収集される（ #653 ）のでここでは気にしなくてよいはずです。

2023-11-04 03:51 UTC, kaikoga commented on CHANGELOG.md
> +- Improve support of UniVRM components `#652`
はい

2023-11-04 03:53 UTC, kaikoga commented on CHANGELOG.md
> +- Improve support of UniVRM components `#652`
まとめてrebaseするのがめっちゃ大変なのでbranchだけ残して #653 に統合します

2023-11-04 03:53 UTC, closed without merging

2023-11-04 04:00 UTC, kaikoga commented on CHANGELOG.md
> +- Improve support of UniVRM components `#652`
#653 のDraftが外れるのはもうしばらくかかると思います。