feat: Support VRM0 / VRM1 in AAO components
anatawa12/AvatarOptimizer pull request #653
Opened 2023-10-29 02:20 UTC by kaikoga

Parent Issue: #651

VRM0 / VRM1 components will survive Trace And Optimize.

Draft because this PR needs serious refactoring...

2023-11-04 04:54 UTC, kaikoga commented on API-Editor/ComponentInformation.cs
> +        protected virtual void PostprocessMapping(TComponent component, MappingSource mappingSource)
マッピングし終わった後なので `LateApplySpecialMapping()` とかではないと思う

2023-11-04 05:36 UTC, kaikoga commented
できている可能性がある（後でもう一度確認します）

2023-11-04 17:01 UTC, kaikoga commented
Perhaps MergeSkinnedMesh would need some extra validations regarding VRM FirstPersonFlags...

2023-11-04 18:21 UTC, anatawa12 commented on Editor/ObjectMapping/AnimationObjectMapper.cs
> +        public string MapPropertyName(string srcPath, string propertyName, Type type)
現状blendshape的には起きるよていがないけど`newProp.MappedProperty.Component`の型がtypeとは限らないのと数が増えないとはかぎらないのでMapPropertyNameの追加には反対します。

`MapBinding`は実質的には`(string path, Type, string property) => (string path, Type, string property)[]`なので`MapBinding`の引数を3値にし、戻り値をtuple(かstruct)の配列にするほうが良さそうな気がします

2023-11-04 18:21 UTC, anatawa12 commented on Editor/ObjectMapping/ObjectMappingContext.cs
> +
そもそもここinternal APIなので`public T MapObject<T>(T original) where T : UnityEngine.Object`にしていい気がしました。

2023-11-04 18:21 UTC, anatawa12 commented on Editor/ObjectMapping/ObjectMappingContext.cs
> +#endif
そうすると個々にある3つのほぼ一緒のコードも共通化できる気がしてます

2023-11-05 01:40 UTC, kaikoga commented on Editor/ObjectMapping/ObjectMappingContext.cs
> +#endif
過激っぽい気がして遠慮してましたが、お墨付きを得たのでやります

2023-11-05 01:41 UTC, kaikoga commented on Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
>  #endif
要調査・・・

2023-11-05 01:50 UTC, kaikoga commented on Editor/ObjectMapping/AnimationObjectMapper.cs
> +        public string MapPropertyName(string srcPath, string propertyName, Type type)
PropertyNameだけマッピングするのは雑すぎ把握しました（修正します）

2023-11-05 02:53 UTC, anatawa12 commented on Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
>  #endif
多分ですがどちらもAnimationClipもどきなのでBlendShape消したときにAnimationClipもどきからproperty消せば問題ない気がしています。

2023-11-05 03:30 UTC, kaikoga commented on Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
>  #endif
よく考えてみたらVRMのリップシンクはただの特別な名前がついた表情だったので特別扱いは不要でした（直しました）

2023-11-05 03:41 UTC, anatawa12 approved these changes
コードはOK
あとはさやまめさんの`ja.po`/`en.po`のレビュー通り次第mergeします

2023-11-05 13:35 UTC, Sayamame-beans requested changes
いかがでしょうか?

2023-11-05 13:35 UTC, Sayamame-beans commented on CHANGELOG-PRERELEASE.md
> +- Add support of UniVRM components `#653`
```suggestion
- Add support for UniVRM components `#653`
```

2023-11-05 13:35 UTC, Sayamame-beans commented on CHANGELOG.md
> +- Add support of UniVRM components `#653`
```suggestion
- Add support for UniVRM components `#653`
```

2023-11-05 13:35 UTC, Sayamame-beans commented on Localization/ja.po
> +"統合対象のRenderer間でFirstPersonFlagsの値が揃っていなかったため、'{0}'に統合されました。\n"
```suggestion
"統合対象のRenderer間でFirstPersonFlagsの値が揃っていなかったため、'{0}'に統一されました。\n"
```

2023-11-05 13:35 UTC, Sayamame-beans commented on Localization/en.po
> +"It is advisable to set same FirstPersonFlags values for Renderers to be merged by MergeSkinnedMesh.\n"
```suggestion
"It is recommended to set same FirstPersonFlags values for Renderers to be merged by MergeSkinnedMesh.\n"
```

2023-11-05 13:35 UTC, Sayamame-beans commented on Localization/en.po
> +"Source Renderers had mixed FirstPersonFlags values specified, and fallbacked into '{0}'.\n"
```suggestion
"Source Renderers had specified mixed FirstPersonFlags values, so fallbacked into '{0}'.\n"
```
或いは
```suggestion
"Source Renderers had mixed FirstPersonFlags values, so fallbacked into '{0}'.\n"
```
はどうでしょう?

2023-11-05 15:09 UTC, kaikoga commented
英語はわからないのでドキュメントは勝手に直してください。

2023-11-05 15:31 UTC, Sayamame-beans approved these changes

2023-11-05 15:35 UTC, merged