Remove zero size mesh
anatawa12/AvatarOptimizer pull request #659
Opened 2023-10-30 05:36 UTC by anatawa12

Resolve #650

2023-10-30 06:04 UTC, Sayamame-beans commented
T&O向けと単体で説明の書き方が違うのって何か理由あります…?

2023-10-30 08:34 UTC, anatawa12 commented
off by defaultのT&Oにするのを考えてます

2023-10-30 08:35 UTC, anatawa12 commented
> T&O向けと単体で説明の書き方が違うのって何か理由あります…?

単体だと実装に近い描き方した記憶がありますがそこまで強い意味はないです

2023-10-30 09:24 UTC, anatawa12 commented on Runtime/TraceAndOptimize.cs
> +        public bool removeZeroSizedPolygons = true;
```suggestion
        public bool removeZeroSizedPolygons = false;
```

Disabled by defaultにする?

2023-10-31 12:35 UTC, anatawa12 commented on Runtime/TraceAndOptimize.cs
> +        public bool removeZeroSizedPolygons = true;
にしようか。副作用まぁ怖いし

2023-10-31 12:38 UTC, Sayamame-beans commented
> > T&O向けと単体で説明の書き方が違うのって何か理由あります…?
> 
> 単体だと実装に近い描き方した記憶がありますがそこまで強い意味はないです

じゃあ適当にところどころ合わせるかんじでレビュー書きますね

2023-11-01 11:53 UTC, Sayamame-beans requested changes

2023-11-01 11:53 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "大きさのないポリゴンを削除する"
```suggestion
msgstr "面積がゼロのポリゴンを自動的に削除する"
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +- `Remove Polygons with Area of Zero`
```suggestion
- `Automatically Remove Zero Sized Polygons`
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +- `大きさのないポリゴンを削除する`
```suggestion
- `面積がゼロのポリゴンを自動的に削除する`
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  Removes polygons with area of zero with attaching [Remove Zero Sized Polygon](../remove-zero-sized-polygon) component.
```suggestion
  Removes polygons whose area are zero.
```
ここ見て気付いたんですが、T&Oでの動作的にはコンポーネント足すだけなんです…?
とはいえ、表にそう書いてある必要はないかもしれません。

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.ja.md
> +面積が0なポリゴンを削除します。
```suggestion
面積がゼロのポリゴンを削除します。
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.ja.md
> +このコンポーネントはビルドプロセスの最後の方に実行されるため、このコンポーネントは[Modifying Edit Skinned Mesh Component](../../component-kind/edit-skinned-mesh-components#modifying-component) では**ありません**。
```suggestion
このコンポーネントはビルドの最後の方で実行されるため、[Modifying Edit Skinned Mesh Component](../../component-kind/edit-skinned-mesh-components#modifying-component) では**ありません**。
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.ja.md
> +このコンポーネントを[Merge Skinned Mesh](../merge-skinned-mesh)のソースSkinnedMeshRendererに追加しても効果はありません。
```suggestion
このコンポーネントを[Merge Skinned Mesh](../merge-skinned-mesh)の統合対象となるSkinnedMeshRendererに追加しても効果がありません。
```
メッシュ?
どっちの表記が主だったか分からなくなりました

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.ja.md
> +面積が0なポリゴンを削除することで、描画負荷を減らすことができます。
```suggestion
面積がゼロのポリゴンを削除することで、描画負荷を減らすことができます。
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.ja.md
> +面積が0なポリゴンは見た目にほとんど影響を与えません。
```suggestion
見た目に影響を与えることはほとんどありません。
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.ja.md
> +現在のところ設定はありません。
```suggestion
今のところ、このコンポーネントに設定項目はありません。
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.md
> +Currently no settings.
```suggestion
This Component doesn't have any configuration for now.
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.md
> +Remove polygons with area of zero.
```suggestion
Remove polygons whose area are zero.
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.md
> +Putting this component on the source SkinnedMeshRenderers of [Merge Skinned Mesh](../merge-skinned-mesh) has no effect.
```suggestion
Adding this component to the SkinnedMeshRenderers to be merged by [Merge Skinned Mesh](../merge-skinned-mesh) component has no effect.
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.md
> +By removing polygons which has zero size, you can reduce rendering cost.
```suggestion
By removing polygons whose area are zero, you can reduce rendering cost.
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.md
> +Polygons with zero size will have almost zero effect on the appearance.
```suggestion
This will have almost zero effect on the appearance.
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.md
> +This component will be attached by [Trace and Optimize](../trace-and-optimize) component.
```suggestion
This component will be added by [Trace and Optimize](../trace-and-optimize) component.
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.md
> +I recommend you to use Trace and Optimize instead of attaching this component manually.
```suggestion
I recommend you to use Trace and Optimize instead of adding this component manually.
```

2023-11-01 11:53 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/component.png
変更に追従

2023-11-01 12:45 UTC, anatawa12 commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.ja.md
> +面積が0なポリゴンは見た目にほとんど影響を与えません。
 そういえば欠点欄に稀に描画が変わるってこと書くべきだったか

2023-11-01 12:48 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  Removes polygons with area of zero with attaching [Remove Zero Sized Polygon](../remove-zero-sized-polygon) component.
T&O的にはつけるだけですね。どっちかというとAutomatic Configurationの時代の名前に近い機能

2023-11-05 14:35 UTC, Sayamame-beans requested changes

2023-11-05 14:35 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-zero-sized-polygon/index.ja.md
> +シェーダーによってはモデルファイルでのポリゴンの大きさが0でも実際にはなにかが描画されることがあるため、見た目に影響がある可能性があります。
```suggestion
モデルファイルでのポリゴンの大きさがゼロであっても、シェーダーによって何かを描画していることがあるため、見た目に影響が出ることがあります。
```

2023-11-05 14:46 UTC, Sayamame-beans approved these changes

2023-11-05 14:47 UTC, merged