Skip initially disabled objects
anatawa12/AvatarOptimizer pull request #670
Opened 2023-10-31 00:49 UTC by anatawa12

Fixes #666

2023-10-31 02:39 UTC, Sayamame-beans commented
"Enabled Mismatched Renderers"だと意味が伝わらないような気がします…?
まだ代替表現思いついてないです

2023-10-31 07:40 UTC, anatawa12 commented
EnabledじゃなくてEnablementだなとなったのでそうしたけどまだ分かりづらいかも

2023-11-05 13:01 UTC, Sayamame-beans commented
代替案迷子中

2023-11-05 16:44 UTC, Sayamame-beans commented
"State Mismatched Renderers"だとさすがにふわっとし過ぎですかね?
SMRで(表で触れて)stateにあたりそうなのはisActiveかなと考えて、辛うじて伝わるかなって思ったんですけど…

2023-11-05 17:30 UTC, anatawa12 commented
普通にBlendShape状態ではないですかね

2023-11-05 18:12 UTC, Sayamame-beans commented
> 普通にBlendShape状態ではないですかね

a---
じゃあ没で

2023-11-06 08:50 UTC, Sayamame-beans requested changes
コード内はEnabled表記のままですけど大丈夫です?

2023-11-06 08:50 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/component.png
Enablement表記に更新

2023-11-06 08:50 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "有効無効が統合先と等しくないレンダラーを統合しない"
```suggestion
msgstr "有効無効状態が統合先と異なるレンダラーを統合しない"
```

2023-11-06 08:50 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
> +このオプションが有効なばあい、有効無効が統合先と等しくないSkinnedMeshRendererやMeshRendererがビルド時に無効になっている場合、統合対象から除外されます。
```suggestion
統合先のSkinnedMeshRendererと有効無効の状態が異なるSkinnedMeshRendererやMeshRendererが統合対象の中に含まれている場合、それらをビルド時に統合対象から除外するオプションです。
```

2023-11-06 08:50 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
> +### 有効無効が統合先と等しくないレンダラーを統合しない {#skip-enablement-mismatched-renderers}
```suggestion
### 有効無効状態が統合先と異なるレンダラーを統合しない {#skip-enablement-mismatched-renderers}
```

2023-11-06 09:47 UTC, anatawa12 commented
コード内はどっちでもいいと思ってるけど治すかぁ

2023-11-06 10:49 UTC, Sayamame-beans approved these changes
よさそう

2023-11-06 10:50 UTC, merged