Shader property animation
anatawa12/AvatarOptimizer pull request #769
Opened 2023-12-04 11:43 UTC by anatawa12

Fixes #768

2024-01-31 10:12 UTC, anatawa12 reviewed
とりあえずParser v2移植はOK

2024-01-31 15:42 UTC, anatawa12 commented
> #726 的なものよういして、Poiyomiとliltoonレベルに違う場合は流石に許可したい気はする

できた。

2024-01-31 15:42 UTC, anatawa12 commented
ついでに使われることが予想される `UV Tile Discard`についても対応を入れた。ほかはfuture updatesに

2024-02-07 08:24 UTC, Sayamame-beans requested changes

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "統合対象のメッシュ間でマテリアルのアニメーションが異なっているものが見つかりました: {0}"
```suggestion
msgstr "統合対象のメッシュ間で、以下のマテリアルプロパティに対するアニメーションが異なります: {0}"
```

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"統合対象のメッシュ間でマテリアルのアニメーションが異なっているものが見つかりました。\n"
```suggestion
"統合対象のメッシュ間で、マテリアルに対するアニメーションが異なります。\n"
```

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"マテリアルのアニメーションはメッシュ全体に影響するため、意図しない部分にアニメーションが適用されてしまう可能性があります。\n"
```suggestion
"マテリアルに対するアニメーションはメッシュ全体に影響するため、意図していない部分にアニメーションが適用されてしまう可能性があります。\n"
```

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"アニメーションが意図したものである場合は\n"
```suggestion
"アニメーションが統合したメッシュ全体に影響することを意図している場合は、以下のようにしてください。\n"
```

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"- 統合対象のメッシュのマテリアルのプロパティを同じカーブとアニメーションクリップでアニメーションする、\n"
```suggestion
"- 統合対象のメッシュのマテリアルプロパティを、それぞれ同じカーブとアニメーションクリップでアニメーションする。\n"
```
same curve and animation clipって、つまり、1つのアニメーションクリップで、対象のメッシュには同じ内容(カーブ)の変更をしてねってこと? 言い方を今と変えられそうな気もしています。

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"- 統合先のメッシュをアニメーションする、または\n"
```suggestion
"- 統合先のメッシュをアニメーションする。\n"
```

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"- この警告を無視してください\n"
```suggestion
"- この警告を無視する。\n"
```

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"もし統合対象のすべてのメッシュを同じカーブでアニメーションしてる場合、複数のレンダラをアニメーションする方法が良くない可能性があります。\n"
```suggestion
"統合対象のすべてのメッシュを同じカーブでアニメーションしているにもかかわらず、この警告が表示されている場合は、複数のメッシュをアニメーションする方法が良くない可能性があります。\n"
```

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"Avatar Optimizerは同じアニメーションクリップで同じ形のカーブで同じStateでアニメーションされている場合に同じようにアニメーションされていると判断します。\n"
```suggestion
"Avatar Optimizerは、同じアニメーションクリップにおいて、同じ形のカーブかつ、同じState上でアニメーションされている場合に、それらが同じようにアニメーションされていると判断します。\n"
```

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"Avatar Optimizerは同じアニメーションクリップで同じ形のカーブで同じStateでアニメーションされている場合に同じようにアニメーションされていると判断します。\n"
State…若干の悩み

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"これは、異なるレイヤーやクリップで同じようにアニメーションしている場合、アニメーションが異なっていると判断されることを意味します。\n"
```suggestion
"つまり、異なるレイヤーやアニメーションクリップから同じようにアニメーションしている場合、それらのアニメーションは別のものとして認識されることになります。\n"
```

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"もしアニメーションが他のメッシュに影響しない場合(例えば、メッシュのシェーダー機能の無効な機能にしか影響しない場合)は、この問題をAvatar Optimizerに報告してください。\n"
```suggestion
"アニメーションが他のメッシュに影響しない場合(例えば、メッシュ上で無効なシェーダー機能にしか影響しない場合)は、この問題をAvatar Optimizerに報告してください。\n"
```
the disabled shader features of meshesが分かっていないので、補足が欲しいです

2024-02-07 08:24 UTC, Sayamame-beans commented on Localization/ja.po
> +"もしシェーダーが有名なものであれば、アニメーションされていないレンダラに対してその機能が有効かどうかを確認するロジックを追加します。\n"
```suggestion
"シェーダーが有名なものであれば、アニメーションされていないメッシュに対してもその機能が有効なのかどうかを確認する処理を追加します。\n"
```

2024-02-07 09:21 UTC, anatawa12 commented on CHANGELOG-PRERELEASE.md
> +  - Since first version of Merge Skinned Mesh, animating material properties differently is not supported (in other words, it might be broken).
ここに関しては「最初から今までずっと」なのでinではないかなと思います

2024-02-07 09:22 UTC, anatawa12 commented on Localization/en.po
> +"Avatar Optimizer thinks it's animated similarly if property is animated with same shaped curve and same animation clip on the exactly same state.\n"
assumesとかのほうが適切？

2024-02-07 09:26 UTC, anatawa12 commented on Localization/ja.po
> +"- 統合対象のメッシュのマテリアルのプロパティを同じカーブとアニメーションクリップでアニメーションする、\n"
> 1つのアニメーションクリップで、対象のメッシュには同じ内容(カーブ)の変更をしてねってこと?

だいたいそうです。

2024-02-07 09:31 UTC, anatawa12 commented on Localization/ja.po
> +"もしアニメーションが他のメッシュに影響しない場合(例えば、メッシュのシェーダー機能の無効な機能にしか影響しない場合)は、この問題をAvatar Optimizerに報告してください。\n"
> the disabled shader features of meshesが分かっていないので、補足が欲しいです

たとえば輪郭線をオフにしてる場合には輪郭線に関わるアニメーションは「プロパティはあるけど影響がない」になり得るのでこういうのを想定してます

2024-02-07 09:47 UTC, Sayamame-beans commented on CHANGELOG-PRERELEASE.md
> +  - Since first version of Merge Skinned Mesh, animating material properties differently is not supported (in other words, it might be broken).
あー、今はfirst versionではないのか
じゃあ、first versionから今まで、という表記にしたいかもです

2024-02-07 09:50 UTC, anatawa12 commented on CHANGELOG-PRERELEASE.md
> +  - Since first version of Merge Skinned Mesh, animating material properties differently is not supported (in other words, it might be broken).
0.0.1からあるしremoveEmptyRendererObjectの追加等が行われてるのでfirst versionではないと思います。

2024-02-14 13:17 UTC, Sayamame-beans commented on CHANGELOG-PRERELEASE.md
> +  - Since first version of Merge Skinned Mesh, animating material properties differently is not supported (in other words, it might be broken).
んー…どう変えればよいだろう…

2024-02-14 13:18 UTC, Sayamame-beans commented on Localization/en.po
> +"Avatar Optimizer thinks it's animated similarly if property is animated with same shaped curve and same animation clip on the exactly same state.\n"
そうかも。
```suggestion
"Avatar Optimizer assumes it's animated similarly if property is animated with same shaped curve and same animation clip on the exactly same state.\n"
```

2024-02-14 13:50 UTC, Sayamame-beans reviewed
(追加じゃなくてうっかり別になっちゃった)

2024-02-14 13:50 UTC, Sayamame-beans commented on Localization/ja.po
> +"- 統合対象のメッシュのマテリアルのプロパティを同じカーブとアニメーションクリップでアニメーションする、\n"
```suggestion
"- 統合対象のメッシュのマテリアルプロパティを、共通のアニメーションクリップ内で全て同じようにアニメーションする。\n"
```
"カーブ"って表現、さてはややこしいな?となりました。
若干しっくり来ていないですが一旦変えてみた形です。
どう思われますか? (他の場所ではまだカーブ表記のまま)

2024-02-14 13:50 UTC, Sayamame-beans commented on Localization/ja.po
> +"もしアニメーションが他のメッシュに影響しない場合(例えば、メッシュのシェーダー機能の無効な機能にしか影響しない場合)は、この問題をAvatar Optimizerに報告してください。\n"
な→になっている としました

2024-02-14 18:01 UTC, anatawa12 commented on Localization/ja.po
> +"- 統合対象のメッシュのマテリアルのプロパティを同じカーブとアニメーションクリップでアニメーションする、\n"
"同じように"だと曖昧かなぁってカーブにしてたんですが、"同じように"のほうが良さそうであればそれでいいと思います。

2024-02-18 09:32 UTC, Sayamame-beans commented on Localization/ja.po
> +"- 統合対象のメッシュのマテリアルのプロパティを同じカーブとアニメーションクリップでアニメーションする、\n"
うーむ…
まあ"同じように"の捉え方次第という感じ

2024-02-20 14:41 UTC, Sayamame-beans requested changes

2024-02-20 14:41 UTC, Sayamame-beans commented on Localization/ja.po
> +"- 統合対象のメッシュのマテリアルのプロパティを同じカーブとアニメーションクリップでアニメーションする、\n"
ここでは"同じように"で良い気がします
より詳しい説明が必要なら、例とか出してdocsでやった方が良さそう

2024-02-20 14:41 UTC, Sayamame-beans commented on Localization/ja.po
> +"もし統合対象のすべてのメッシュを同じカーブでアニメーションしてる場合、複数のレンダラをアニメーションする方法が良くない可能性があります。\n"
```suggestion
"統合対象のすべてのメッシュを同じようにアニメーションしているにもかかわらず、この警告が表示されている場合は、複数のメッシュに対するアニメーションのさせ方が良くないかもしれません。\n"
```

2024-02-20 14:41 UTC, Sayamame-beans commented on Localization/ja.po
> +"これは、異なるレイヤーやクリップで同じようにアニメーションしている場合、アニメーションが異なっていると判断されることを意味します。\n"
```suggestion
"つまり、同じようにアニメーションしている場合でも、異なるレイヤーやアニメーションクリップからアニメーションしている場合は別のアニメーションとして認識されることになります。\n"
```

2024-02-20 14:41 UTC, Sayamame-beans commented on CHANGELOG-PRERELEASE.md
> +  - Since first version of Merge Skinned Mesh, animating material properties differently is not supported (in other words, it might be broken).
```suggestion
  - Until this version, Merge Skinned Mesh does not support animating material properties differently. (In other words, it can be broken.)
```
こうかな

2024-02-20 14:41 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - Since first version of Merge Skinned Mesh, animating material properties differently is not supported (in other words, it might be broken).
```suggestion
  - Until this version, Merge Skinned Mesh does not support animating material properties differently. (In other words, it can be broken.)
```

2024-02-22 06:56 UTC, anatawa12 commented on CHANGELOG-PRERELEASE.md
> +  - Since first version of Merge Skinned Mesh, animating material properties differently is not supported (in other words, it might be broken).
Until this versionだと今まで対応してない (= 今は対応してる)になっちゃうけど、昔も今もある程度の将来も対応しないので、`Until this version, Merge Skinned Mesh does not support animating material properties differently.`も不適切だと思います

2024-02-22 07:05 UTC, Sayamame-beans commented on CHANGELOG-PRERELEASE.md
> +  - Since first version of Merge Skinned Mesh, animating material properties differently is not supported (in other words, it might be broken).
> 昔も今もある程度の将来も対応しない

そうなんだ
じゃあ…SinceもUntilも要らないのでは?
```suggestion
  - Merge Skinned Mesh does not support animating material properties differently. (In other words, it can be broken.)
```

2024-02-22 08:05 UTC, anatawa12 commented on CHANGELOG-PRERELEASE.md
> +  - Since first version of Merge Skinned Mesh, animating material properties differently is not supported (in other words, it might be broken).
一番最初から対応してなかったんだよと明記するつもりで入れてたけどまぁなくていいか

2024-02-23 18:53 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - Since first version of Merge Skinned Mesh, animating material properties differently is not supported (in other words, it might be broken).
```suggestion
  - Merge Skinned Mesh does not support animating material properties differently. (In other words, it can be broken.)
```

2024-02-24 09:38 UTC, Sayamame-beans approved these changes

2024-02-24 09:43 UTC, merged