fix: merge PhysBone curve
anatawa12/AvatarOptimizer pull request #775
Opened 2023-12-07 06:43 UTC by anatawa12

Fixes #319

2023-12-07 11:50 UTC, Sayamame-beans commented
少々お待ちを

2023-12-08 00:34 UTC, Sayamame-beans requested changes

2023-12-08 00:34 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "統合対象のPhysBoneが一つしかありません。２つ以上指定してください。"
```suggestion
msgstr "統合対象のPhysBoneが1つしかありません。2つ以上のPhysBoneを指定してください。"
```

2023-12-08 00:34 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "統合対象のPhysBoneが一つしかありません。２つ以上指定してください。"
漢数字ってどこかで使ってましたっけ? (純粋に覚えてない)

2023-12-08 00:34 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "複数の統合対象の間でチェーンの長さが異なります。短いチェーンのPBがもとより太くなる可能性があります。"
```suggestion
msgstr "複数の統合対象の間でチェーンの長さが異なります。チェーンが短くなると、元よりも太くなる可能性があります。"
```
英語の意味を私が読み間違えてるかも

2023-12-08 00:34 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "複数の統合対象の間でチェーンの長さが異なります。短いチェーンのPBがもとより太くなる可能性があります。"
"チェーン"、若干気になりましたが他が思いつかないのでそのままに

2023-12-08 03:36 UTC, anatawa12 commented on Localization/ja.po
> +msgstr "複数の統合対象の間でチェーンの長さが異なります。短いチェーンのPBがもとより太くなる可能性があります。"
チェーン自体の長さは変わらないので"短くなる"だとなんか違うと思う。元々のチェーンが短いとという話なので

2023-12-08 12:09 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "複数の統合対象の間でチェーンの長さが異なります。短いチェーンのPBがもとより太くなる可能性があります。"
あ〜そっか、PBってそういう挙動だっけ…

2023-12-08 12:13 UTC, anatawa12 commented on Localization/ja.po
> +msgstr "複数の統合対象の間でチェーンの長さが異なります。短いチェーンのPBがもとより太くなる可能性があります。"
短いチェーンを根元側を揃えて長くすると(MergePBのチェーンの長さが揃ってないときの動作)Curveの1の位置が遠くなって、徐々に細くなるようなカーブだと全体的に太くなります。

2023-12-09 07:05 UTC, Sayamame-beans requested changes
変更提案は多分3つ?です

2023-12-09 07:05 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "複数の統合対象の間でチェーンの長さが異なります。短いチェーンのPBがもとより太くなる可能性があります。"
```suggestion
msgstr "複数の統合対象の間でチェーンの長さが異なります。短いチェーンのPBは元よりも太くなる可能性があります。"
```

2023-12-09 07:37 UTC, Sayamame-beans approved these changes

2023-12-09 16:45 UTC, merged