Upgrade NDMF to 1.3.0-rc.1
anatawa12/AvatarOptimizer pull request #815
Opened 2024-01-06 17:00 UTC by anatawa12

2024-01-06 17:05 UTC, Sayamame-beans commented
明日見ます

2024-01-07 06:56 UTC, Sayamame-beans requested changes

2024-01-07 06:56 UTC, Sayamame-beans commented on Localization/en.po
> +msgstr "There are some components unknown to Avatar Optimizer. This will reduce optimization performance and may break your Avatar."
```suggestion
msgstr "There are some components Avatar Optimizer doesn't know.. This will reduce optimization performance and may break your Avatar."
```

2024-01-07 06:56 UTC, Sayamame-beans commented on Localization/en.po
> +"If the component is components of your tool, please consider registering it to Avatar Optimizer.\n"
```suggestion
"If it is a component of your tool, please consider registering it to Avatar Optimizer.\n"
```

2024-01-07 06:56 UTC, Sayamame-beans commented on Localization/en.po
> +"If the component is components of tools you use, please ask tool author to register the component to Avatar Optimizer\n"
```suggestion
"If it is a component of a tool you are using, please ask tool author to register the component to Avatar Optimizer\n"
```

2024-01-07 06:56 UTC, Sayamame-beans commented on Localization/en.po
> +"or ask Avatar Optimizer to support the component if the tool is well-known tool."
```suggestion
"or ask Avatar Optimizer to support the component if the tool is a well-known one."
```

2024-01-07 06:56 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "Avatar Optimizerの知らないコンポーネントを見つけました。これにより最適化処理の品質が低下し、処理後のアバターが壊れる可能性があります。(元のアバターには影響しません)"
```suggestion
msgstr "Avatar Optimizerにとって未知のコンポーネントが見つかりました。これにより最適化処理の品質が低下し、処理後のアバターが壊れる可能性があります。(元のアバターには影響しません)"
```

2024-01-07 06:56 UTC, Sayamame-beans commented on Localization/ja.po
> +"もしバターが壊れていない場合、この警告を無視しても問題ありません。\n"
お好み
```suggestion
"アバターが壊れていない場合、この警告は無視しても問題ありません。\n"
```
```suggestion
"アバターが壊れなかった場合、この警告は無視しても問題ありません。\n"
```

2024-01-07 06:56 UTC, Sayamame-beans commented on Localization/ja.po
> +"このコンポーネントがあなたのツールのコンポーネントである場合、Avatar Optimizerへの登録をご検討してください。"
```suggestion
"このコンポーネントがあなたのツールのものである場合は、Avatar Optimizerにコンポーネントを登録することを検討してください。"
```

2024-01-07 06:56 UTC, Sayamame-beans commented on Localization/ja.po
> +"詳しくは https://vpm.anatawa12.com/avatar-optimizer/ja/docs/developers/make-your-components-compatible-with-aao/ を参照してください。\n"
```suggestion
"詳しくは https://vpm.anatawa12.com/avatar-optimizer/ja/docs/developers/make-your-components-compatible-with-aao/ をご覧ください。\n"
```

2024-01-07 06:56 UTC, Sayamame-beans commented on Localization/ja.po
> +"このコンポーネントがあなたが使っているツールのコンポーネントである場合、ツール作者にコンポーネントの登録を依頼するか、"
```suggestion
"このコンポーネントがあなたの使っているツールのものである場合は、ツール作者にAvatar Optimizerへのコンポーネント登録を依頼するか、"
```

2024-01-07 06:56 UTC, Sayamame-beans commented on Localization/ja.po
> +"ツールが有名である場合にはAvatar Optimizerにコンポーネントのサポートを依頼してください。"
```suggestion
"有名なツールであればAvatar Optimizerに対応を依頼してください。"
```

2024-01-07 09:04 UTC, Sayamame-beans requested changes

2024-01-07 09:04 UTC, Sayamame-beans commented on Localization/en.po
> +msgstr "There are some components Avatar Optimizer doesn't know.. This will reduce optimization performance and may break your Avatar."
This was my review mistake. Can fix by this.

2024-01-07 09:04 UTC, Sayamame-beans commented on Localization/ja.po
> +"有名なツールであればAvatar Optimizerに対応を依頼してください。"
```suggestion
"有名なツールであればAvatar Optimizer側に対応を依頼してください。"
```
あっても良いのかもしれないと思ったので足してみました。
任せます。

2024-01-07 09:05 UTC, anatawa12 commented on Localization/ja.po
> +"有名なツールであればAvatar Optimizerに対応を依頼してください。"
これはなくて良さそう

2024-01-07 09:17 UTC, Sayamame-beans approved these changes
多分ヨシ

2024-01-07 09:17 UTC, merged