feat(asset-description): initial commit for asset description
anatawa12/AvatarOptimizer pull request #847
Opened 2024-01-23 12:44 UTC by anatawa12

Fixes #717

2024-01-23 14:11 UTC, anatawa12 commented
ドキュメント書かないとだけど書くの面倒...

2024-01-24 16:55 UTC, Sayamame-beans requested changes
とりあえずpoファイルだけ

2024-01-24 16:55 UTC, Sayamame-beans commented on Localization/en.po
> +"Avatar Optimizer Asset Description is a asset that describe your assets for Avatar Optimizer.\n"
```suggestion
"Avatar Optimizer Asset Description is an asset that describe your assets to Avatar Optimizer.\n"
```

2024-01-24 16:55 UTC, Sayamame-beans commented on Localization/en.po
> +"For more details please visit our documentation"
```suggestion
"For more details, please visit our documentation."
```
or
```suggestion
"Please visit our documentation for more details."
```

2024-01-24 16:55 UTC, Sayamame-beans commented on Localization/ja.po
> +"Avatar Optimizer Asset DescriptionはAvatar Optimizerにアセットについて説明するアセットです。\n"
```suggestion
"Avatar Optimizer Asset Descriptionは、あなたのアセットについての情報をAvatar Optimizerに与えるためのアセットです。\n"
```
主語に名前ってこれまでにありましたっけ…?

2024-01-24 17:02 UTC, Sayamame-beans requested changes
changelogも

残り: docsと画像

2024-01-24 17:02 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - Asset Description is the file to provide Avatar Optimizer information of your assets.
```suggestion
  - Asset Description is the file to provide information of your assets to Avatar Optimizer.
```

2024-01-24 17:02 UTC, Sayamame-beans commented on Localization/en.po
> +"For more details please visit our documentation"
changelogでの書き方だと後者が近い

2024-01-24 17:02 UTC, Sayamame-beans commented on CHANGELOG-PRERELEASE.md
> +  - Asset Description is the file to provide Avatar Optimizer information of your assets.
```suggestion
  - Asset Description is the file to provide information of your assets to Avatar Optimizer.
```

2024-01-26 14:09 UTC, anatawa12 commented on Localization/en.po
> +"For more details please visit our documentation"
揃える必要もないかなと思っててFor more datails先のほうがここにおいては自然だと思ってるので後者かなぁ

2024-01-26 14:11 UTC, anatawa12 commented on CHANGELOG.md
> +  - Asset Description is the file to provide Avatar Optimizer information of your assets.
SVOOよりtoの方がいいというのはどのような判断です？

2024-01-26 14:45 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - Asset Description is the file to provide Avatar Optimizer information of your assets.
初め、見た感じの読解容易性からその様にした方が良さそうかな?と感じました。
その後調べたところ、provide A B のSVOOはあまり一般的な用法ではないようです。(アメリカ英語では割と使われている?)
provide A with B または provide B for/to A の中で、個人的にしっくり来るのはやはりtoなのかなぁ…と
諸説あるので選択はお好みという感じではあります。

2024-01-28 15:15 UTC, anatawa12 commented on CHANGELOG.md
> +  - Asset Description is the file to provide Avatar Optimizer information of your assets.
provide forにしますね。

```suggestion
- Asset Description is the file to provide information of your assets for Avatar Optimizer.
```

2024-01-28 15:15 UTC, anatawa12 commented on CHANGELOG-PRERELEASE.md
> +  - Asset Description is the file to provide Avatar Optimizer information of your assets.
```suggestion
  - Asset Description is the file to provide information of your assets for Avatar Optimizer.
```

2024-01-28 15:16 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Asset Description is the file to provide Avatar Optimizer information of  your assets.
```suggestion
Asset Description is the file to provide information of  your assets for Avatar Optimizer.
```

2024-01-28 15:34 UTC, anatawa12 commented on Localization/ja.po
> +"Avatar Optimizer Asset DescriptionはAvatar Optimizerにアセットについて説明するアセットです。\n"
UnusedBonesByReferencesToolである

2024-01-28 16:47 UTC, Sayamame-beans requested changes
とりあえずen docs

2024-01-28 16:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Avatar Optimizer needs to know all components in your avatar to remove unnecessary components.\
```suggestion
Avatar Optimizer has to know about all existing components in the Avatar to remove unnecessary ones.\
```
make-your-components-compatible-with-aaoに揃えました

2024-01-28 16:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +for tools that is not a non-destructive and does not process during build,
destructive toolという表現を意図的に避けてますかね…?

```suggestion
for tools that are not non-destructive and do not process during build, 
```

2024-01-28 16:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +For non-destructive tools, we still recommend you continue to remove components in `IVRCSDKPreprocessAvatarCallback` to prevent AvatarOptimizer from accidentally removing components when the executio
```suggestion
For non-destructive tools, we still recommend you to continue to remove components in `IVRCSDKPreprocessAvatarCallback` to prevent AvatarOptimizer from accidentally removing components when the execution order is incorrect.
```
recommend A to Bに沿った変更

2024-01-28 16:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +To create Asset Description, select `Create/Avatar Optimizer/Asset Description` from the Project window right-click menu.\
```suggestion
To create Asset Description, select `Create/Avatar Optimizer/Asset Description` from right-click menu in the Project window.\
```

2024-01-28 16:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Avatar Optimizer searches from all files, so the name and location of Asset Description are free.
```suggestion
Avatar Optimizer searches from all files, so the name and location of Asset Description is free.
```

2024-01-28 16:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Avatar Optimizer ignores the component of the specified Script Asset type or its subclass.
```suggestion
Avatar Optimizer ignores the component of the specified Script Asset type and its subclass.
```
```suggestion
Avatar Optimizer ignores the component of the specified Script Asset type and/or its subclass.
```

2024-01-28 16:47 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Therefore, even if the class name is changed, the specification in Asset Description will work without any problem as long as the components in the Scene are not broken.
```suggestion
Therefore, even if the class name is changed, the specification in Asset Description will work without any problems as long as the components in the Scene are not broken.
```

2024-01-28 19:41 UTC, Sayamame-beans requested changes
ふと気付いたんですが、Avatar OptimizerとAvatarOptimzier表記が時々混ざってますね…?

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +Avatar Optimizerはアバターのいらない要素削除するため、アバターにあるすべてのコンポーネントについての知識が必要があります。\
```suggestion
アバター上の不要な要素を削除するために、Avatar Optimizerはアバターに存在するすべてのコンポーネントのことを知る必要があります。\
```

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +## Asset Descriptionはなぜ必要なのか
```suggestion
## なぜAsset Descriptionが必要なのか {#why-asset-description-is-needed}
```

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +Avatar Optimizer v1.6.0で[コンポーネントの互換性を持たせるためのドキュメント][make-component-compatible]とAPIが追加されましたが、
```suggestion
Avatar Optimizer v1.6.0で[コンポーネントにAAOとの互換性をもたせるためのドキュメント][make-component-compatible]とAPIが追加されましたが、
```

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +非破壊ツールではなく、ビルド時に処理を行わないツールにとってはコンポーネントを `IVRCSDKPreprocessAvatarCallback`で削除するのは少し煩雑であろうと考えました。\
```suggestion
非破壊ツールでなく、ビルド時に処理を行わないようなツールでは、`IVRCSDKPreprocessAvatarCallback`でコンポーネントを削除するのは少し面倒だろうと考えました。\
```

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、ビルド時に意味のない、Avatar Optimizerに無視してほしいコンポーネントを指定するためのシンプルな仕組みとしてAsset Descriptionが1.7.0で追加されました。
```suggestion
そのため、Avatar Optimizerに無視してほしい、ビルド時には意味のないコンポーネントを指定するためのシンプルな仕組みとして、Asset Descriptionがv1.7.0で追加されました。
```

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Therefore, Asset Description was added in 1.7.0 as a simple mechanism to specify components that should be ignored by Avatar Optimizer at build time.
```suggestion
Therefore, Asset Description was added in v1.7.0 as a simple mechanism to specify components that should be ignored by Avatar Optimizer at build time.
```
見落としてました

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +非破壊ツールについては実行順が正しくなかったときにAvatarOptimizerによってコンポーネントを誤って削除されてしまうのを防ぐため、今まで通り`IVRCSDKPreprocessAvatarCallback`で削除することを推奨します。
```suggestion
なお、非破壊ツールの場合については、正しくない実行順で処理が行われた場合に、Avatar Optimizerがコンポーネントを誤って削除してしまわないように、従来通り`IVRCSDKPreprocessAvatarCallback`でコンポーネントを削除することを推奨します。
```

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +Asset Descriptionを作成するには Project ウィンドウの右クリックメニューから `Create/Avatar Optimizer/Asset Description` を選択してください。\
```suggestion
Asset Descriptionを作成するには、Projectウィンドウの右クリックメニューから`Create/Avatar Optimizer/Asset Description`を選択してください。\
```

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +Avatar Optimizerはすべてのファイルから検索するため、Asset Descriptionの名前、場所は自由です。
```suggestion
Avatar Optimizerはすべてのファイルの中からファイル検索を行うため、Asset Descriptionの名前、場所は自由です。
```

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +Meaningless ComponentsにはAvatar Optimizerに無視してほしいコンポーネントの型を列挙するものです。
```suggestion
Meaningless ComponentsはAvatar Optimizerに無視してほしいコンポーネントの型の一覧です。
```

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +指定されたScript Assetの型もしくはそのサブクラスのコンポーネントはAvatar Optimizerに無視されます。
```suggestion
指定されたScript Assetの型のコンポーネントと、そのサブクラスのコンポーネントはAvatar Optimizerに無視されます。
```

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +Asset Descriptionでは実際のScene上のコンポーネントと同様に、Script AssetのguidとfileIDの形で保持されています。
```suggestion
Asset Descriptionでは実際のScene上のコンポーネントと同様に、Script AssetがguidとfileIDの形で保持されています。
```

2024-01-28 19:41 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.ja.md
> +そのため、クラス名を変更してもシーン上のコンポーネントが壊れない限りはAsset Descriptionでの指定も問題なく機能します。
```suggestion
そのため、クラス名を変更したとしても、シーン上のコンポーネントが壊れていない限り、Asset Descriptionでの指定も問題なく機能します。
```

2024-01-28 20:31 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/asset-description-inspector.png
例だし無視します

2024-01-28 20:34 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/index.en.md
> +Avatar Optimizer searches from all files, so the name and location of Asset Description are free.
nameとlocationで２つじゃない ？

2024-01-28 20:37 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/index.en.md
> +Avatar Optimizer searches from all files, so the name and location of Asset Description are free.
確かに

2024-02-02 18:55 UTC, Sayamame-beans approved these changes
コメントの通りです(画像の文章が気になるのみ)

2024-02-02 18:55 UTC, Sayamame-beans commented on .docs/content/docs/developers/asset-description/asset-description-inspector.png
en.poの変更に伴って、表示されている文章の内容が変わってしまったことを除けば特に問題無さそう…?

2024-02-11 18:09 UTC, anatawa12 commented on .docs/content/docs/developers/asset-description/asset-description-inspector.png
更新した。unityを移動したので2022になったけどまぁいいでしょう

2024-02-11 18:15 UTC, merged