docs(contributing): add about localization changes
anatawa12/AvatarOptimizer pull request #929
Opened 2024-03-20 14:36 UTC by anatawa12

Fixes #920

2024-03-21 13:51 UTC, Sayamame-beans requested changes

2024-03-21 13:51 UTC, Sayamame-beans commented on CONTRIBUTING.md
> +5. Make changes in CHANGELOG file
57行目と矛盾して見える気がします。
初回追加にはchangelogが欲しい、と推測しました
```suggestion
5. Make changes in CHANGELOG file as a notice of adding new locale
```

2024-03-21 13:51 UTC, Sayamame-beans commented on CONTRIBUTING.md
> +If you can be the maintainer of the locale, I'm glad to add new locale for localization.
```suggestion
If you can be the maintainer of the new locale, I'm glad to add it for localization.
```

2024-03-21 13:51 UTC, Sayamame-beans commented on CONTRIBUTING.md
> +If you can be the maintainer of the locale, I'm glad to add new locale for localization.
```suggestion
If you can be the maintainer of the new locale, I'm glad to add it for document localization.
```

2024-03-22 11:45 UTC, Sayamame-beans commented on CONTRIBUTING.md
> +2. Create `page.<langid>.md` in all files in `.docs/content` directory.
```suggestion
2. Create `<page>.<langid>.md` in all files in `.docs/content` directory.
```
とかにします? pageって名前のmdがあるわけではないので、別の表記に変えたい気が少ししました。(そのままでも伝わるとは思いますが)
`<page>`で良いかは微妙ですが…

2024-03-22 11:47 UTC, Sayamame-beans commented on CONTRIBUTING.md
> +For localization or documentation changes, updating CHANGELOG is not required.
```suggestion
For documentation or localization changes, updating CHANGELOG is not required.
```

2024-03-22 11:47 UTC, Sayamame-beans commented on CONTRIBUTING.md
> +For localization or documentation changes, updating CHANGELOG is not required.
(ラベルの表記順と違ったので)

2024-03-22 11:50 UTC, Sayamame-beans commented
他に気になるところはなさそうです

2024-03-22 12:46 UTC, anatawa12 commented on CONTRIBUTING.md
> +2. Create `page.<langid>.md` in all files in `.docs/content` directory.
`<slug>.<langid>.md`?

2024-03-22 12:48 UTC, Sayamame-beans commented on CONTRIBUTING.md
> +2. Create `page.<langid>.md` in all files in `.docs/content` directory.
違う気がする

2024-03-22 12:50 UTC, anatawa12 commented on CONTRIBUTING.md
> +2. Create `page.<langid>.md` in all files in `.docs/content` directory.
ページのid的なのをslugというのはwebでの用途としては正しいと思うけど...

例：https://github.com/vrchat-community/creator-docs/blob/d005b4afe185eef62937264c93c963a655131cb7/Docs/docs/getting-started.md?plain=1#L3

2024-03-22 12:54 UTC, Sayamame-beans commented on CONTRIBUTING.md
> +2. Create `page.<langid>.md` in all files in `.docs/content` directory.
> ページのid的なの

見た感じでは、ここでのindex.ja.mdのindexのようなものはあたらない気がしました。
実際、例に挙げられたものは`https://creators.vrchat.com/getting-started/`に展開されていますし…
https://developer.mozilla.org/ja/docs/Glossary/Slug

もちろん、indexと書けば親dirの名前になるというのが自明であれば、問題ないようなものかもしれません…

2024-03-22 12:56 UTC, anatawa12 commented on CONTRIBUTING.md
> +2. Create `page.<langid>.md` in all files in `.docs/content` directory.
あーindex.mdに揃えてるの忘れてました。というか揃えてるから`index.<langid>.md`が正しそう？

2024-03-22 12:56 UTC, Sayamame-beans commented on CONTRIBUTING.md
> +2. Create `page.<langid>.md` in all files in `.docs/content` directory.
自明かも

2024-03-22 12:57 UTC, Sayamame-beans commented on CONTRIBUTING.md
> +2. Create `page.<langid>.md` in all files in `.docs/content` directory.
今のところ、例外はchangelog.mdぐらいですかね?

2024-03-22 13:01 UTC, anatawa12 commented on CONTRIBUTING.md
> +2. Create `page.<langid>.md` in all files in `.docs/content` directory.
そうですね。changelogは画像がないからそれで通ってるだけなのでどっちかというと例外だしchangelog.mdにしたのがまちがいにちかいかも

2024-03-22 13:29 UTC, Sayamame-beans commented on CONTRIBUTING.md
> +2. Create `page.<langid>.md` in all files in `.docs/content` directory.
じゃあとりあえずここはindexに揃えるで良さそうですね〜(一部使われないページとして_indexはありますが…)
```suggestion
2. Create `index.<langid>.md` in all files in `.docs/content` directory.
```

2024-03-22 15:12 UTC, Sayamame-beans approved these changes

2024-03-22 15:19 UTC, merged