Automatic MergeSMR
anatawa12/AvatarOptimizer pull request #952
Opened 2024-03-26 11:07 UTC by anatawa12

Fixes #767

2024-03-26 19:24 UTC, anatawa12 commented
検討事項: TutorialにおけるMerge Skinned Meshの扱いどうするか

2024-03-27 12:14 UTC, Sayamame-beans requested changes
部分的にreview

2024-03-27 12:14 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +  - `マテリアルスロットの前後関係を壊すのを許可する`\
```suggestion
  - `マテリアルスロットの前後関係を変えることを許可する`\
```

2024-03-27 12:14 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +    マテリアルスロットの前後関係を壊すのを許可します。\
```suggestion
    マテリアルスロットの前後関係を変えることを許可します。\
```

2024-03-27 12:14 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +    マテリアルスロットの前後関係は多くの場合は意味を持ちませんが、場合によっては描画順が変わることがある模様です。
```suggestion
    多くの場合、マテリアルスロットの前後関係は特に意味を持ちませんが、描画順に影響を与える場合もあるようです。
```

2024-03-27 12:43 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +- `スキンメッシュを結合する`\
自動的に、どうしよう。内部名称には(最初から)ないのでどっちかに揃えたほうが良さそうかな

2024-03-27 13:36 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +- `スキンメッシュを結合する`\
ある方が良いような気がしつつも、でも冗長だよね…という微妙な感想です

2024-03-27 15:53 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +- `スキンメッシュを結合する`\
とりあえず今はない状態にしておきましょう。どっかで揃える。

2024-03-28 08:56 UTC, Sayamame-beans requested changes

2024-03-28 08:56 UTC, Sayamame-beans commented on CHANGELOG-PRERELEASE.md
> +  - Trace and Optimize will merge your mesh if the material properties of the mesh is not animated and has no BlensShapes.
```suggestion
  - Trace and Optimize will merge your mesh if the material properties or enablement of the mesh is animated similarly and has no BlendShapes.
```

2024-03-28 08:56 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - Trace and Optimize will merge your mesh if the material properties of the mesh is not animated and has no BlensShapes.
```suggestion
  - Trace and Optimize will merge your mesh if the material properties or enablement of the mesh is animated similarly and has no BlendShapes.
```

2024-03-28 08:56 UTC, Sayamame-beans commented on Localization/en.po
> +msgstr "Allow shuffling material slots to reduce draw calls. however, this may change the order of rendering a bit."
docsと書いてる内容が違うのでどうしようかな…になってます
(合わせておかないと後で苦しそう)

2024-03-28 08:56 UTC, Sayamame-beans commented on Localization/en.po
> +msgstr "Allow shuffling material slots to reduce draw calls. however, this may change the order of rendering a bit."
```suggestion
msgstr "Allow shuffling material slots to reduce draw calls. This may affect the drawing order."
```
とりあえずそのまま維持する感じで後半だけdocsから持ってきました。
書いてて気付きましたけどdrawing orderなのかrendering orderなのかが…?

2024-03-28 08:56 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "スキンメッシュを結合する"
```suggestion
msgstr "スキンメッシュレンダラーを統合する"
```

2024-03-28 08:56 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "マテリアルスロットの前後関係を壊すのを許可する"
```suggestion
msgstr "マテリアルスロットの前後関係を変えることを許可する"
```

2024-03-28 08:56 UTC, Sayamame-beans commented on Localization/ja.po
> +msgstr "マテリアルスロットの前後関係を壊すことで描画コール数を減らすことを許可します。ただし、これは描画順序を少し変更する可能性があります。"
```suggestion
msgstr "マテリアルスロットの前後関係を変えることでドローコールを減らすことを許可します。これは描画順に影響を与える可能性があります。"
```
同

2024-03-28 11:42 UTC, anatawa12 commented on Localization/en.po
> +msgstr "Allow shuffling material slots to reduce draw calls. however, this may change the order of rendering a bit."
rendering orderのほうが良さそう

2024-03-28 11:43 UTC, anatawa12 commented on .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
> +[Trace And Optimize](../trace-and-optimize)が自動で同様の処理を行える場合があるため、このコンポーネントを使用する必要がない可能性があります。
もとよりは良さそう

2024-03-28 13:39 UTC, Sayamame-beans commented on Localization/en.po
> +msgstr "Allow shuffling material slots to reduce draw calls. however, this may change the order of rendering a bit."
```suggestion
msgstr "Allow shuffling material slots to reduce draw calls. This may affect the rendering order."
```

2024-03-28 13:41 UTC, Sayamame-beans commented on Localization/en.po
> +msgstr "Allow shuffling material slots to reduce draw calls. however, this may change the order of rendering a bit."
どうしましょうねこれ
ドローコール減るって内容をdocsに足します…?

2024-03-28 15:41 UTC, anatawa12 commented on Localization/en.po
> +msgstr "Allow shuffling material slots to reduce draw calls. however, this may change the order of rendering a bit."
書きました

2024-03-28 16:23 UTC, Sayamame-beans requested changes

2024-03-28 16:23 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +    マテリアルスロットの前後関係を変えることを許可します。\
```suggestion
```
説明が増えて流石に冗長になったので消します

2024-03-28 16:23 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +    Allow shuffling material slots.\
```suggestion
```

2024-03-28 16:23 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.ja.md
> +    マテリアルスロットの前後関係を変えることで、アバターの描画負荷をドローコール減らすことができます。\
```suggestion
    マテリアルスロットの前後関係を変えることで、アバターの描画負荷を減らすことができます。\
```
または
```suggestion
    マテリアルスロットの前後関係を変えることで、アバターの描画負荷を減らせる場合があります。\
```

2024-03-28 16:40 UTC, Sayamame-beans approved these changes
maybe ok!

2024-03-28 16:41 UTC, merged