Docs improvements
anatawa12/AvatarOptimizer pull request #961
Opened 2024-03-27 16:26 UTC by anatawa12

Fixes #544
Fixes #891

2024-03-28 10:29 UTC, Sayamame-beans commented
https://github.com/anatawa12/AvatarOptimizer/pull/961/commits/d7e035ba82108633627a9cf16308f401dae091c9 は別のレビュー中に気付いて気になったので直しました
が…Optimize Animatorが何をどうするのか全く情報ないですね…?

2024-03-28 13:22 UTC, anatawa12 commented
Animator Optimizer、何するというのが結構説明が重いのでどこで説明しようってことになる

2024-03-28 13:50 UTC, Sayamame-beans commented
量が多いなら`##`とかで節を生やして、そっちに詳細説明を委ねる感じが良さそうな気がしますね

2024-03-28 13:58 UTC, anatawa12 commented
節分けるか

2024-03-30 04:20 UTC, anatawa12 commented
ready for reviewのつもりです (reviewされてないので再requestはできない状態になってる)

2024-03-30 04:21 UTC, Sayamame-beans commented
> ready for reviewのつもりです (reviewされてないので再requestはできない状態になってる)

絶賛レビュー中です

2024-03-30 04:30 UTC, Sayamame-beans requested changes
部分レビュー

2024-03-30 04:30 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
"basic-concept"?

2024-03-30 04:30 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +title: "基本概念"
迷う…
```suggestion
title: "コンセプト"
```
```suggestion
title: "基本コンセプト"
```
basic-conceptの訳は基本概念であってるはずなんですが、しっくりこなくて…

2024-03-30 04:30 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +[^blend-shape]: BlendShapeはUnity上のモーフィングの名前です。MayaではTarget Shapes、BlenderではShape Key、MetasequoiaやMMDではモーフと呼ばれます。
単数か複数かどっちかに揃えたい

2024-03-30 04:30 UTC, Sayamame-beans commented on .docs/content/docs/tutorial/basic-usage/index.md
> +[^blend-shape]: BlendShape is the name of Morphing in Unity. Maya call them as Target Shapes, Blender calls them as Shape Key, Metasequoia and MMD call them as Morph.
同

2024-03-30 04:30 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-blendshape/index.ja.md
> +`プレビューのために、切り替えたBlendShapeの値を自動的に変更する`を有効にした場合、チェックボックスを切り替えた際に状態に基づいてBlendShapeの値を0または100に設定します。
```suggestion
`プレビューのために、切り替えたBlendShapeの値を自動的に変更する`を有効にすると、BlendShapeの指定を切り替えた時に、その値を自動的に100か0に設定します。
```

2024-03-30 04:30 UTC, Sayamame-beans commented on .docs/content/docs/reference/remove-mesh-by-blendshape/index.md
> +If you enabled `Automatically set BlendShape weight for preview when toggled`, the inspector will set BlendShape weight to 0 or 100 based on the toggle state.
```suggestion
If you enabled `Automatically set BlendShape weight for preview when toggled`, when you toggle specifying BlendShapes, their weight will be automatically set to 100 or 0.
```

2024-03-30 05:54 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.ja.md
> +[^blend-shape]: BlendShapeはUnity上のモーフィングの名前です。MayaではTarget Shapes、BlenderではShape Key、MetasequoiaやMMDではモーフと呼ばれます。
単数にします
```suggestion
[^blend-shape]: BlendShapeはUnity上のモーフィングの名前です。MayaではTarget Shape、BlenderではShape Key、MetasequoiaやMMDではモーフと呼ばれます。
```

2024-03-30 05:54 UTC, anatawa12 commented on .docs/content/docs/tutorial/basic-usage/index.md
> +[^blend-shape]: BlendShape is the name of Morphing in Unity. Maya call them as Target Shapes, Blender calls them as Shape Key, Metasequoia and MMD call them as Morph.
```suggestion
[^blend-shape]: BlendShape is the name of Morphing in Unity. Maya call them as Target Shape, Blender calls them as Shape Key, Metasequoia and MMD call them as Morph.
```

2024-03-30 06:36 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +- Entry/Exit to BlendTree\
-か/か悩ましい

2024-03-30 06:39 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +- Entry/Exit to BlendTree\
そもそも、この動作説明(できる限り変換)だとEntry/Exitに絞った名前で書くのは妙ですね…? (Anchor付いてないし一旦ヨシとします)

2024-03-30 06:42 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  This removes layers which are not have any state or transition.
この動作、レイヤーのindexを揃えるために差し込んだダミーレイヤーを消してしまいそうですね
(例: MMDワールドで表情操作レイヤーを無効化されてしまわないように、ダミーレイヤーを挟んでズラす)

2024-03-30 06:43 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  This removes layers which are not have any state or transition.
mmd対応はちゃんと残ります

2024-03-30 06:58 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  This removes layers which are not have any state or transition.
というと…? FXの上から3つのレイヤーが別のものになる/動かすアニメーションが増えるような操作はしないようにしてあるってことです?

2024-03-30 07:02 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  This removes layers which are not have any state or transition.
上から３つのレイヤーは消さないという処理が走ってます

他の最適化ではレイヤのウェイトが変わるかを見てるので、mmdワールドによってウェイトが変わる可能性のある2つのレイヤは他のレイヤとの結合は行われないようになっています

2024-03-30 07:46 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +- Merge Direct BlendTree Layers\
"Direct BlendTree Layer"の定義って、Direct Blend Treeしかないレイヤーってことで良いです…?

2024-03-30 07:47 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +- Merge Direct BlendTree Layers\
いや、説明が面倒そうなので触れないことにします

2024-03-30 07:47 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +- Merge Direct BlendTree Layers\
現状そうです。

2024-03-30 07:51 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  This removes layers which are not have any state or transition.
なるほどです

ちなみにもう1個思いついた疑問があるのですが、ここではstateやtransitionが無ければとありますが、stateもtransitionもparameterもちゃんとあるけど、全stateの中身のanimationが空でBehaviourも付いてないみたいなケースはどうなりますか? (Remove unused Objectsによって発生し得る気がする)

2024-03-30 07:53 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +  This removes layers which are not have any state or transition.
WD周りでなんか動作が変更するのが怖いので少なくとも今はやってないです

2024-03-30 08:20 UTC, Sayamame-beans commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +- Merge Direct BlendTree Layers\
これに触れようと思うと、`Direct BlendTree1つだけからなる複数のレイヤーを1つに統合します。`とか書かないといけないなと思いまして…(多分1レイヤー1つ想定のはずですよね)
若干読みづらそうなのですよね～

2024-03-30 08:22 UTC, anatawa12 commented on .docs/content/docs/reference/trace-and-optimize/index.md
> +- Merge Direct BlendTree Layers\
ですね。あとは今後BlendTreeじゃない1 stateのみのも結合していいよなとは思ってるので結構曖昧でいたい

2024-03-30 08:41 UTC, Sayamame-beans commented
review request: https://github.com/anatawa12/AvatarOptimizer/pull/961/commits/d2a12156dc54f495b52ede9171ba32670d23ce21

2024-03-30 09:35 UTC, anatawa12 commented
> review request: https://github.com/anatawa12/AvatarOptimizer/commit/d2a12156dc54f495b52ede9171ba32670d23ce21

OK

2024-03-30 11:29 UTC, Sayamame-beans requested changes
部分レビュー2

2024-03-30 11:29 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-physbone/index.ja.md
> +このコンポーネントは新しいPhysBoneのルートGameObjectを作成し、統合対象のPhysBoneによって揺らされるボーンをこのGameObjectの子にします。
```suggestion
このコンポーネントは、PhysBoneのルートとなるGameObjectを新たに作成し、統合対象のPhysBoneによって揺らされるボーンを、作成したGameObjectの子にします。
```

2024-03-30 11:29 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-physbone/index.md
> +This component will create a new PhysBone root GameObject and make the bones swayed by merge target PhysBones into children of this GameObject.
```suggestion
This component will create a new PhysBone root GameObject and make the bones swayed by merge target PhysBones into children of this GameObject.\
```

2024-03-30 11:29 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-physbone/index.ja.md
> +ルートGameObjectはPhysBoneに影響を受けるTransformとして扱われるため、各Merge PhysBoneごとにPhysBone Affected Transformsの数が1つ増えます。
```suggestion
なお、ルートとなっているGameObjectも、PhysBoneによって影響を受けるボーンの1つとみなされるため、各Merge PhysBoneごとに`PhysBone Affected Transforms`の数が1つ増えてしまいます。
```

2024-03-30 11:29 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-physbone/index.md
> +Since the root GameObject is treated as a PhysBone affected Transforms, the number of PhysBone Affected Transforms will be increased by one for each Merge PhysBone.
```suggestion
Since the root GameObject is treated as a PhysBone affected Transforms, the number of `PhysBone Affected Transforms` will be increased by one for each Merge PhysBone.
```

2024-03-30 11:29 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-physbone/index.md
> +The added PhysBone transform will not be swayed by PhysBone so this can be a bug of the VRCSDK Performance System.
```suggestion
The added PhysBone transform will not be swayed by PhysBone so this can be a bug of the VRChat Performance Rank System.
```

2024-03-30 11:29 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-physbone/index.ja.md
> +追加されたPhysBone TransformはPhysBoneによって揺らされないため、これはVRCSDK Performance Systemのバグである可能性があります。
```suggestion
このコンポーネントによって追加されるGameObjectがPhysBoneによって揺らされることはないため、これはVRChatのPerformance Rankシステムのバグである可能性があります。 
```

2024-03-30 13:43 UTC, Sayamame-beans requested changes
review for en faq

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +[`MergeSkinnedMesh`] does not automatically set the Root Bone, so you need to manually set the Root Bone of the Skinned Mesh Renderer for MergeSkinnedMesh.
```suggestion
[`AAO Merge Skinned Mesh`] component does not automatically set the `Root Bone`, so you need to manually set the `Root Bone` of the Merged Mesh.
(Merged Mesh is a Skinned Mesh Renderer which is attached along with `AAO Merge Skinned Mesh` component.)
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +[`MergeSkinnedMesh`]: ../reference/merge-skinned-mesh/
```suggestion
[`AAO Merge Skinned Mesh`]: ../reference/merge-skinned-mesh/
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +If you are using [Modular Avatar], you can add [`MA Mesh Settings`] to the root of the avatar to set the Root Bone and Bounds for the entire avatar.
```suggestion
If you are using [Modular Avatar], you can add [`MA Mesh Settings`] component to the root of the avatar to set the `Root Bone` and `Bounds` for the whole avatar.
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +## The brightness of the meshes merged with `MergeSkinnedMesh` is different from other meshes {#the-brightness-of-the-meshes-merged-with-mergeskinnedmesh-is-different-from-other-meshes}
```suggestion
## The brightness of the meshes merged with `AAO Merge Skinned Mesh` component is different from other meshes {#the-brightness-of-the-meshes-merged-with-aao-merge-skinned-mesh-component-is-different-from-other-meshes}
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +The problem that the brightness of the meshes merged with [`MergeSkinnedMesh`] is different from other meshes is often due to forgetting to specify the Anchor Override of the merged meshes.
```suggestion
This problem is often due to forgetting to specify the `Anchor Override` of the merged meshes.
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +[`MergeSkinnedMesh`] does not automatically set the Anchor Override, so you need to manually set the Anchor Override of the Skinned Mesh Renderer for MergeSkinnedMesh.
```suggestion
[`AAO Merge Skinned Mesh`] component does not automatically set the `Anchor Override`, so you need to manually set the `Anchor Override` of the Merged Mesh.
(Merged Mesh is a Skinned Mesh Renderer which is attached along with `AAO Merge Skinned Mesh` component.)
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +If you are using [Modular Avatar], you can add [`MA Mesh Settings`] to the root of the avatar to set the Anchor Override for the entire avatar.
```suggestion
If you are using [Modular Avatar], you can add [`MA Mesh Settings`] component to the root of the avatar to set the `Anchor Override` for the whole avatar.
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +## Material animations conflict when using `MergeSkinnedMesh` {#material-animations-conflict-when-using-mergeskinnedmesh}
```suggestion
## Material animations conflict when using `AAO Merge Skinned Mesh` component {#material-animations-conflict-when-using-aao-merge-skinned-mesh-component}
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +The problem that material animations conflict when using [`MergeSkinnedMesh`] is a known bug and is currently expected to conflicts.
```suggestion
This problem is a known bug and is currently expected to conflicts.
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +When merging meshes that are animating materials, be careful not to conflict when merging.
```suggestion
When merging meshes with animated materials, be careful not to conflict.
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +## BlendShape animations conflict when using `MergeSkinnedMesh` {#blendshape-animations-conflict-when-using-mergeskinnedmesh}
```suggestion
## BlendShape animations conflict when using `AAO Merge Skinned Mesh` component {#blendshape-animations-conflict-when-using-aao-merge-skinned-mesh-component}
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +The problem that BlendShape animations conflict when using [`MergeSkinnedMesh`] is a known bug and is currently expected to conflicts.
```suggestion
This problem is a known bug and is currently expected to conflicts.
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +When merging meshes that are animating BlendShapes, be careful not to conflict when merging.
```suggestion
When merging meshes with animated BlendShapes, be careful not to conflict.
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +## The behavior of the avatar is changed when using `Trace and Optimize` {#avatar-behavior-changed-when-using-trace-and-optimize}
これfaqの一番上に持ってくるべきかも。

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +## The behavior of the avatar is changed when using `Trace and Optimize` {#avatar-behavior-changed-when-using-trace-and-optimize}
```suggestion
## The behavior of the avatar is changed when using `AAO Trace and Optimize` component {#avatar-behavior-changed-when-using-aao-trace-and-optimize-component}
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +If the behavior of the avatar is changed when using `Trace and Optimize`, it is always be a bug unless you depend on bugs in other components of AvatarOptimizer.
```suggestion
If the behavior of the avatar is changed when using `AAO Trace and Optimize` component, it is always a bug unless you depend on bugs in other components of AvatarOptimizer.
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +If you want to support the development of Avatar Optimizer, feedback on [GitHub Discussions], bug reports, feature requests, pull requests, etc. on [GitHub issues] are welcome.
```suggestion
If you want to support the development of Avatar Optimizer, feedback on [GitHub Discussions], bug reports, feature requests, etc. on [GitHub issues], and pull requests are welcome.
```

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +Issues with [good first issue] are relatively easy to implement. It is recommended for your first pull request.
```suggestion
Issues with [good first issue] are relatively easy to implement. It is recommended for your first contribution.
```
こっちでも良さそう

2024-03-30 13:43 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +Also, issues with [help wanted] are issues that lack developers or information. Your participation in discussions and development would be appreciated.
```suggestion
Also, issues with [help wanted] are ones that lack developers or information. Your participation in discussions and development would be appreciated.
```

2024-03-30 14:15 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +メッシュが視界の中にあるのに非表示になってしまう問題は、多くの場合、Skinned Mesh RendererのRoot Boneの指定しわすれである事が多いです。
```suggestion
多くの場合、この問題はSkinned Mesh Rendererの`Root Bone`を指定し忘れていることが原因です。
```

2024-03-30 14:15 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +[`MergeSkinnedMesh`]はRoot Boneを自動的に設定しないため、MergeSkinnedMesh用のSkinned Mesh RendererのRoot Boneも手動で設定する必要があります。
```suggestion
[`AAO Merge Skinned Mesh`]コンポーネントは`Root Bone`の設定を自動的には行わないため、統合先のメッシュの`Root Bone`を手動で設定する必要があります。
(統合先のメッシュとは、`AAO Merge Skinned Mesh`コンポーネントと一緒に付いているSkinned Mesh Rendererのことです。)
```

2024-03-30 14:15 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +[`MergeSkinnedMesh`]: ../reference/merge-skinned-mesh/
```suggestion
[`AAO Merge Skinned Mesh`]: ../reference/merge-skinned-mesh/
```

2024-03-30 14:15 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +If you are using [Modular Avatar], you can add [`MA Mesh Settings`] to the root of the avatar to set the Root Bone and Bounds for the entire avatar.
そういえば何故bounds…? (同時にしか設定出来ないから?)

2024-03-30 14:50 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +If you are using [Modular Avatar], you can add [`MA Mesh Settings`] to the root of the avatar to set the Root Bone and Bounds for the entire avatar.
Boundsが`MA Mesh Settings`で設定されるので書いた感じ。

2024-03-30 14:57 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +When merging meshes that are animating materials, be careful not to conflict when merging.
もともそうだけど、with animated material propertiesとかwith shader propertiesとか表現変えたほうがいいのかもしれない

そしてMaterial Slot自体の置き換えの節追加したほうがいい感じかな。レビューapplyしたらそれ参考にやります

2024-03-30 14:58 UTC, Sayamame-beans requested changes
review for ja faq

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +もし[Modular Avatar]を使用している場合には、アバターのルートに[`MA Mesh Settings`]を追加して、Root Boneを設定することでアタバー全体のRoot BoneとBoundsを設定することができます。
```suggestion
[Modular Avatar]を使用している場合は、アバターのルートに[`MA Mesh Settings`]コンポーネントを追加して設定することにより、アバター全体の`Root Bone`と`Bounds`を設定することができます。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +## `MergeSkinnedMesh`で結合したメッシュの明るさが他のメッシュと異なる {#the-brightness-of-the-meshes-merged-with-mergeskinnedmesh-is-different-from-other-meshes}
```suggestion
## `AAO Merge Skinned Mesh`コンポーネントで統合したメッシュの明るさが他のメッシュと異なる {#the-brightness-of-the-meshes-merged-with-aao-merge-skinned-mesh-component-is-different-from-other-meshes}
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +[`MergeSkinnedMesh`]で結合したメッシュの明るさが他のメッシュと異なる問題は、多くの場合、結合したメッシュのAnchor Overrideの指定し忘れが原因です。
```suggestion
多くの場合、この問題は統合先のメッシュの`Anchor Override`を指定し忘れていることが原因です。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +[`MergeSkinnedMesh`]はAnchor Overrideを自動的に設定しないため、MergeSkinnedMesh用のSkinned Mesh RendererのAnchor Overrideも手動で設定する必要があります。
```suggestion
[`AAO Merge Skinned Mesh`]コンポーネントは`Anchor Override`の設定を自動的には行わないため、統合先のメッシュの`Anchor Override`を手動で設定する必要があります。
(統合先のメッシュとは、`AAO Merge Skinned Mesh`コンポーネントと一緒に付いているSkinned Mesh Rendererのことです。)
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +もし[Modular Avatar]を使用している場合には、アバターのルートに[`MA Mesh Settings`]を追加して、Anchor Overrideを設定することでアタバー全体のAnchor Overrideを設定することができます。
```suggestion
[Modular Avatar]を使用している場合は、アバターのルートに[`MA Mesh Settings`]コンポーネントを追加して設定することにより、アバター全体の`Anchor Override`を設定することができます。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +## `MergeSkinnedMesh`を使用するとマテリアルのアニメーションが競合する {#material-animations-conflict-when-using-mergeskinnedmesh}
```suggestion
## `AAO Merge Skinned Mesh`コンポーネントを使用すると、マテリアルに対するアニメーションが競合する {#material-animations-conflict-when-using-aao-merge-skinned-mesh-component}
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +[`MergeSkinnedMesh`]を使用するとマテリアルのアニメーションが競合する問題は、既知のバグで、現在のところは競合するのが仕様です。
```suggestion
この問題は既知のバグであり、現時点では競合してしまう仕様です。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +[`MergeSkinnedMesh`]を使用するとBlendShapeのアニメーションが競合する問題は、既知のバグで、現在のところは競合するのが仕様です。
```suggestion
この問題は既知のバグであり、現時点では競合してしまう仕様です。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +マテリアルのアニメーションを行っているメッシュを結合する際には、競合しないように気をつけて結合してください。
```suggestion
マテリアルに対してアニメーションされるメッシュを統合する際は、競合しないようご注意ください。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +競合する場合には警告が表示されるので、警告を確認してください。
```suggestion
競合する場合は警告が表示されるので、そちらを確認してください。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +競合する場合には警告が表示されるので、警告を確認してください。
```suggestion
競合する場合は警告が表示されるので、そちらを確認してください。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +BlendShapeのアニメーションを行っているメッシュを結合する際には、競合しないように気をつけて結合してください。
```suggestion
BlendShapeに対してアニメーションされるメッシュを統合する際は、競合しないようご注意ください。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +## `MergeSkinnedMesh`を使用するとBlendShapeのアニメーションが競合する {#blendshape-animations-conflict-when-using-mergeskinnedmesh}
```suggestion
## `AAO Merge Skinned Mesh`コンポーネントを使用すると、BlendShapeに対するアニメーションが競合する {#blendshape-animations-conflict-when-using-aao-merge-skinned-mesh-component}
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +## `Trace and Optimize`を使用するとアバターの振る舞いが変わる {#avatar-behavior-changed-when-using-trace-and-optimize}
```suggestion
## `AAO Trace and Optimize`コンポーネントを使用すると、アバターの振る舞いや見た目が変わる {#avatar-behavior-changed-when-using-aao-trace-and-optimize-component}
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +`Trace and Optimize`を使用するとアバターの振る舞いが変わる場合は、AvatarOptimizerの他のコンポーネントのバグに依存していない限り、バグです。
```suggestion
`AAO Trace and Optimize`コンポーネントを使用して、アバターの振る舞いや見た目が変わってしまった場合は、(アバターがAvatarOptimizerの他のコンポーネントのバグ挙動に依存していない限り、)全てバグです。例外はありません。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +[GitHub issues], [misskey][fediverse] (mastodon), [twitter] などで報告してください。
```suggestion
[GitHub issues]や[misskey][fediverse] (mastodon)、[twitter]などから報告をお願いいたします。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +Avatar Optimizerの開発を支援したい場合は、[GitHub Discussions]でのフィードバックや[GitHub issues]でのバグ報告、機能リクエスト、プルリクエスト等を歓迎します。
```suggestion
Avatar Optimizerの開発を支援したい場合、プルリクエストや[GitHub Discussions]でのフィードバック、[GitHub issues]でのバグ報告や機能追加要望などを歓迎しています。
```
順番変わっちゃいましたが、なんかそのままの順番だと弄っても日本語がしっくり来なかったので…

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +Avatar Optimizerの開発を支援したい場合は、[GitHub Discussions]でのフィードバックや[GitHub issues]でのバグ報告、機能リクエスト、プルリクエスト等を歓迎します。
本当はPRは重いので後ろに置きたいけど、github issuesに繋がって見えてしまう

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +[good first issue]がついたissueは比較的実装が簡単なissueです。初めてのプルリクエストにおすすめです。
```suggestion
[good first issue]が付いているissueは、比較的実装が簡単なissueです。初めてのプルリクエストにおすすめです。
```
```suggestion
[good first issue]が付いているissueは、比較的実装が簡単なissueです。初めてのコントリビューションにおすすめです。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +また、[help wanted]がついたissueは開発者や情報などが足りないissueです。議論や開発に参加していただけると助かります。
```suggestion
また、[help wanted]が付いているissueは、開発者や情報などが不足しているissueです。議論や開発に参加していただけると助かります。
```

2024-03-30 14:58 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +[github sponsors] や [booth] で金銭的な支援も受け付けています。
```suggestion
なお、[github sponsors]や[booth]での金銭的な支援も受け付けています。
```

2024-03-30 14:59 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +Issues with [good first issue] are relatively easy to implement. It is recommended for your first pull request.
issuesもcontributionに含むしちょっと微妙かも

2024-03-30 15:00 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +[`MergeSkinnedMesh`] does not automatically set the Root Bone, so you need to manually set the Root Bone of the Skinned Mesh Renderer for MergeSkinnedMesh.
その可能性はあります(文章使い回せると思うので、applyする時にやっちゃってください)

2024-03-30 15:01 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +When merging meshes that are animating materials, be careful not to conflict when merging.
あ～…(深く考えてなくてアニメーションでの操作全般を意図して書いちゃった)

2024-03-30 15:03 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +Issues with [good first issue] are relatively easy to implement. It is recommended for your first pull request.
確かに

2024-03-30 15:04 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +`Trace and Optimize`を使用するとアバターの振る舞いが変わる場合は、AvatarOptimizerの他のコンポーネントのバグに依存していない限り、バグです。
()に例外が書かれてて、その後ろに"例外はありません"はなんか違う気がする

2024-03-30 15:05 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +[GitHub issues], [misskey][fediverse] (mastodon), [twitter] などで報告してください。
"報告をお願いいたします。"、もう少しナチュラルな"報告をお願いします。"くらいでもいいとは思ったりしたけどまぁお願いだから"報告をお願いいたします。"も妥当だしちょっとどうしようってなった

2024-03-30 15:06 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +`Trace and Optimize`を使用するとアバターの振る舞いが変わる場合は、AvatarOptimizerの他のコンポーネントのバグに依存していない限り、バグです。
確かに(何も考えてなかった)

2024-03-30 15:06 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +`Trace and Optimize`を使用するとアバターの振る舞いが変わる場合は、AvatarOptimizerの他のコンポーネントのバグに依存していない限り、バグです。
消しました

2024-03-30 15:06 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +Avatar Optimizerの開発を支援したい場合は、[GitHub Discussions]でのフィードバックや[GitHub issues]でのバグ報告、機能リクエスト、プルリクエスト等を歓迎します。
```suggestion
Avatar Optimizerの開発を支援したい場合、[GitHub Discussions]でのフィードバックや[GitHub issues]でのバグ報告、機能リクエスト、またプルリクエストなどを歓迎しています。
```
とか？

2024-03-30 15:09 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +[`MergeSkinnedMesh`] does not automatically set the Root Bone, so you need to manually set the Root Bone of the Skinned Mesh Renderer for MergeSkinnedMesh.
```suggestion
[`AAO Merge Skinned Mesh`] component does not automatically set the `Root Bone`, so you need to manually set the `Root Bone` of the Merged Mesh[^merged-mesh].
```

2024-03-30 15:11 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +[`MergeSkinnedMesh`] does not automatically set the Anchor Override, so you need to manually set the Anchor Override of the Skinned Mesh Renderer for MergeSkinnedMesh.
```suggestion
[`AAO Merge Skinned Mesh`] component does not automatically set the `Anchor Override`, so you need to manually set the `Anchor Override` of the Merged Mesh[^merged-mesh].
```

2024-03-30 15:11 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +[help wanted]: https://github.com/anatawa12/AvatarOptimizer/labels/help%20wanted
```suggestion
[help wanted]: https://github.com/anatawa12/AvatarOptimizer/labels/help%20wanted

[^merged-mesh]: Merged Mesh is a Skinned Mesh Renderer which is attached along with `AAO Merge Skinned Mesh` component.
```

2024-03-30 15:12 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +[`MergeSkinnedMesh`]はRoot Boneを自動的に設定しないため、MergeSkinnedMesh用のSkinned Mesh RendererのRoot Boneも手動で設定する必要があります。
```suggestion
[`AAO Merge Skinned Mesh`]コンポーネントは`Root Bone`の設定を自動的には行わないため、統合先のメッシュ[^1]の`Root Bone`を手動で設定する必要があります。
```

2024-03-30 15:13 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +[help wanted]: https://github.com/anatawa12/AvatarOptimizer/labels/help%20wanted
```suggestion
[help wanted]: https://github.com/anatawa12/AvatarOptimizer/labels/help%20wanted

[^merged-mesh]: 統合先のメッシュとは、`AAO Merge Skinned Mesh`コンポーネントと一緒に付いているSkinned Mesh Rendererのことです。
```

2024-03-30 15:14 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +[`MergeSkinnedMesh`]はAnchor Overrideを自動的に設定しないため、MergeSkinnedMesh用のSkinned Mesh RendererのAnchor Overrideも手動で設定する必要があります。
```suggestion
[`AAO Merge Skinned Mesh`]コンポーネントは`Anchor Override`の設定を自動的には行わないため、統合先のメッシュ[^merged-mesh]の`Anchor Override`を手動で設定する必要があります。
```

2024-03-30 15:20 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +Avatar Optimizerの開発を支援したい場合は、[GitHub Discussions]でのフィードバックや[GitHub issues]でのバグ報告、機能リクエスト、プルリクエスト等を歓迎します。
アリかも

2024-03-30 15:20 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +Avatar Optimizerの開発を支援したい場合は、[GitHub Discussions]でのフィードバックや[GitHub issues]でのバグ報告、機能リクエスト、プルリクエスト等を歓迎します。
"や"だけ欲しいね

2024-03-30 15:21 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +Avatar Optimizerの開発を支援したい場合は、[GitHub Discussions]でのフィードバックや[GitHub issues]でのバグ報告、機能リクエスト、プルリクエスト等を歓迎します。
```suggestion
Avatar Optimizerの開発を支援したい場合、[GitHub Discussions]でのフィードバックや[GitHub issues]でのバグ報告、機能追加の要望、またプルリクエストなどを歓迎しています。
```

2024-03-30 15:22 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +[GitHub issues], [misskey][fediverse] (mastodon), [twitter] などで報告してください。
悩むけど、カジュアルでも良いかもです

2024-03-30 15:26 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +When merging meshes that are animating materials, be careful not to conflict when merging.
マテリアルスロットの競合は普通にmerge materialを無効化してもらえばいいので、別途書くべきだと思ったかんじです

2024-03-30 15:27 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +Issues with [good first issue] are relatively easy to implement. It is recommended for your first pull request.
pull requestのままいきます

2024-03-30 15:36 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +When merging meshes that are animating materials, be careful not to conflict when merging.
一旦applyしてからやります

2024-03-30 17:04 UTC, Sayamame-beans requested changes
review ja distributing prefabs

2024-03-30 17:04 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +4. VPAI インストーラー unitypackage を含め、ユーザーに unitypackage をインポートするように誘導してください。\
```suggestion
4. VPAIインストーラーunitypackageを同梱し、そのunitypackageをインポートするように指示してください。\
```

2024-03-30 17:04 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +   VPAI インストーラーは Avatar Optimizer のような VPM パッケージを unitypackage をインポートするだけでインストールするためのツールです。
```suggestion
   VPAIインストーラーは、Avatar OptimizerのようなVPMパッケージを、unitypackageをインポートするだけでインストールするためのツールです。
```

2024-03-30 17:04 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +   Avatar Optimizer 1.x.x 用の VPAI インストーラー unitypackage をダウンロードするためのリンクは[こちら][vpai]です。
```suggestion
   Avatar Optimizer 1.x.x用のVPAIインストーラーunitypackageをダウンロードするためのリンクは[こちら][vpai]です。
```

2024-03-30 19:20 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +## ユーザーを公式の Avatar Optimizer 配布先に誘導する {#guide-to-the-official-distribution}
配布元だったかも

2024-03-30 19:25 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +ユーザーを公式の Avatar Optimizer 配布先に誘導するための推奨方法は以下の通りです。
以下の方法が推奨されてるからどれかを使ってねってつもり

2024-03-30 19:30 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +   ミラーする際にはGitHubのReleasesからではなく、VPMのレポジトリをミラーしてください。
意図としては公式アクションがgithubレポジトリを指定できるのですがそれが非推奨だよっで感じですね

2024-03-30 23:51 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +## ユーザーを公式の Avatar Optimizer 配布先に誘導する {#guide-to-the-official-distribution}
でもなんか、"配布元"って公式自身が言うには違和感あったりしません? 第三者が使うような気がするというか…

2024-03-31 04:52 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +ユーザーを公式の Avatar Optimizer 配布先に誘導するための推奨方法は以下の通りです。
もしかすると、enumerateじゃなくてitemizeで良いかもしれませんね

2024-03-31 04:55 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +## ユーザーを公式の Avatar Optimizer 配布先に誘導する {#guide-to-the-official-distribution}
じゃあ配布場所か

2024-03-31 05:07 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +   ミラーする際にはGitHubのReleasesからではなく、VPMのレポジトリをミラーしてください。
もうちょっと具体的に書いた方が分かりやすいですかね～…?
VPMリポジトリ(vpm.json)自体 とか

2024-03-31 06:37 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +Since Avatar Optimizer is published under MIT License, it's allowed to redistribute it.
```suggestion
Since Avatar Optimizer is published under MIT License, redistribution is allowed.
```

2024-03-31 06:37 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +However, I strongly recommend you to guide your users to the official distribution of Avatar Optimizer.
```suggestion
However, I strongly recommend you to guide your users to the official distribution of Avatar Optimizer.\
```

2024-03-31 06:37 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +Your distribution of Avatar Optimizer may be outdated.
```suggestion
Unofficial distribution of Avatar Optimizer may be outdated. 
```

2024-03-31 06:37 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +If your distribution is outdated, it may have bugs that have already been fixed in the official distribution.
```suggestion
If users use outdated version, they may encounter bugs that have already been fixed in the official distribution. 
```

2024-03-31 06:37 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +if your user uses a newer version of Avatar Optimizer than your distribution, this will cause problems.
```suggestion
if your users use a newer version of Avatar Optimizer than unofficial distribution, some problems will be caused.
```

2024-03-31 06:37 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +また、Avatar Optimizer は前方互換性を保証していないため、あなたの配布するものよりも新しいバージョンの Avatar Optimizer を使っているユーザーの環境で問題が発生します。
> 非公式に配布されているものよりも新しいバージョンを使っているユーザーの環境で

これって多分、古いバージョンを使ったらというより、新しいバージョンを使っている人のバージョンが下がってしまった場合にですかね…? (古いバージョンのデータを新しいバージョンで読むのは良くて、新しいバージョンのデータを古いバージョンで読むのが駄目という解釈)

2024-03-31 06:42 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +また、Avatar Optimizer は前方互換性を保証していないため、あなたの配布するものよりも新しいバージョンの Avatar Optimizer を使っているユーザーの環境で問題が発生します。
```suggestion
また、Avatar Optimizerは前方互換性を保証していないため、新しいバージョンを使っているユーザーの環境で、非公式に配布されているものによってバージョンを下げてしまうと、問題が発生する可能性があります。
```

2024-03-31 06:48 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +また、Avatar Optimizer は前方互換性を保証していないため、あなたの配布するものよりも新しいバージョンの Avatar Optimizer を使っているユーザーの環境で問題が発生します。
> これって多分、古いバージョンを使ったらというより、新しいバージョンを使っている人のバージョンが下がってしまった場合にですかね…?

Yes.

2024-03-31 06:49 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +   ミラーする際にはGitHubのReleasesからではなく、VPMのレポジトリをミラーしてください。
"VPMレポジトリの内容を"とか？

2024-03-31 06:50 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +Your distribution of Avatar Optimizer may be outdated.
言いたいこととしてはあなたが配布すると古い可能性あるよねなのでUnofficialというよりYourだとおもう

2024-03-31 07:48 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +ユーザーを公式の Avatar Optimizer 配布先に誘導するための推奨方法は以下の通りです。
一応推奨順になってたりするので一応番号つけた。明確にするほどではないと思ってる

2024-03-31 08:04 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +Your distribution of Avatar Optimizer may be outdated.
```suggestion
Your unofficial distribution of Avatar Optimizer may be outdated. 
```

がちょうどいい？

2024-03-31 08:33 UTC, Sayamame-beans requested changes

2024-03-31 08:33 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +   If your asset is distributed with VPM, declare Avatar Optimizer as a dependency of your asset in your `package.json`
```suggestion
   Declare Avatar Optimizer as a dependency of your asset in your `package.json`
```

2024-03-31 08:33 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +   [Here][add-repo] is the link to add the Avatar Optimizer repository to VCC.
```suggestion
   [Here][add-repo] is the link to add the Avatar Optimizer Official repository to VCC.
```

2024-03-31 08:33 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +    When mirroring, mirror the VPM repository, not from the GitHub Releases.
```suggestion
   When mirroring, mirror the VPM repository, not from the GitHub Releases.
```
なんかインデントずれてる?

2024-03-31 08:33 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +   [This link][official-installation] is the official installation guide.
```suggestion
   [This link][official-installation] is the official installation guide of Avatar Optimizer.
```

2024-03-31 08:33 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +3. Link to [the booth page of Avatar Optimizer][booth-aao]. \
```suggestion
3. Link to [the Booth page of Avatar Optimizer][booth-aao].\
```

2024-03-31 08:33 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +   The booth page is one of the official distribution page of Avatar Optimizer.
```suggestion
   The Booth page is one of the official distribution page of Avatar Optimizer.
```

2024-03-31 08:33 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +   The booth item includes the latest version of VPAI installer unitypackage.
```suggestion
   The Booth item includes the latest version of VPAI installer unitypackage.
```
```suggestion
   In the Booth page, the latest version of VPAI installer unitypackage is provided.
```

2024-03-31 08:33 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +4. Include VPAI installer unitypackage and guide your users to import the unitypackage. \
```suggestion
4. Include VPAI installer unitypackage and guide your users to import the unitypackage.\
```

2024-03-31 08:33 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +   [Here][vpai] is the link to download the VPAI installer unitypackage for Avatar Optimizer 1.x.x
```suggestion
   [Here][vpai] is the link to download the VPAI installer unitypackage for Avatar Optimizer 1.x.x .
```
試しに入れてみる

2024-03-31 08:36 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +Your distribution of Avatar Optimizer may be outdated.
良いかも?

2024-03-31 08:37 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +## ユーザーを公式の Avatar Optimizer 配布先に誘導する {#guide-to-the-official-distribution}
そうなりそう

2024-03-31 08:40 UTC, Sayamame-beans commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +   ミラーする際にはGitHubのReleasesからではなく、VPMのレポジトリをミラーしてください。
"VPMリポジトリ"という言葉を正しく認識出来てるかに作用されそう
正しい定義だとvpm.jsonを指すと思うので問題ないと思うんですが…VPMリポジトリのGitHubリポジトリとして認識されることないかなぁと

2024-03-31 08:54 UTC, Sayamame-beans requested changes
partially re-review
元のreviewを見返してないので見落としあるかもですが、量多いので…

2024-03-31 08:54 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-physbone/index.ja.md
> +このコンポーネントは、PhysBoneのルートとなるGameObjectを新たに作成し、統合対象のPhysBoneによって揺らされるボーンを、作成したGameObjectの子にします。
```suggestion
このコンポーネントは、PhysBoneのルートとなるGameObjectを新たに作成し、統合対象のPhysBoneによって揺らされるボーンを、作成したGameObjectの子にします。\
```

2024-03-31 08:54 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-physbone/index.md
> +The added PhysBone transform will not be swayed by PhysBone so this can be a bug of the VRChat Performance Rank System.
```suggestion
The added GameObject by this component will not be swayed by PhysBone, so this can be a bug of the VRChat Performance Rank System.
```
日本語に合わせ

2024-03-31 08:57 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +if your user uses a newer version of Avatar Optimizer than your distribution, this will cause problems.
```suggestion
if your users use a newer version of Avatar Optimizer than your unofficial distribution and downgrade it to outdated version, some problems will be caused.
```

2024-03-31 08:58 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.md
> +   The booth item includes the latest version of VPAI installer unitypackage.
memo: 後者

2024-03-31 08:59 UTC, anatawa12 commented
faqのmaterial slot animationの話書きました

2024-03-31 09:01 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +## ユーザーを公式の Avatar Optimizer 配布先に誘導する {#guide-to-the-official-distribution}
```suggestion
## ユーザーをAvatar Optimizer公式の配布場所に誘導する {#guide-to-the-official-distribution}
```

2024-03-31 09:03 UTC, Sayamame-beans commented
細かな改行周りはapplyされてリリースされてから確認して直すかも

2024-03-31 09:03 UTC, anatawa12 commented on .docs/content/docs/developers/distributing-prefabs/index.ja.md
> +   ミラーする際にはGitHubのReleasesからではなく、VPMのレポジトリをミラーしてください。
vpm配布してる人はそのくらいちゃんと理解してくれると思うのでそこまで書くのは冗長だと思う

あとはvpmレポジトリのgithubレポジトリはvpmレポジトリの情報源として正しくしてるのでこれをみらーされてもそこまで困らない。
yankやらなんやらで若干内容を変更することがあるのでそれに対するものとしてgh releasesやめてねなので

2024-03-31 09:04 UTC, anatawa12 commented on .docs/content/docs/reference/merge-physbone/index.md
> +The added PhysBone transform will not be swayed by PhysBone so this can be a bug of the VRChat Performance Rank System.
`The GameObject added by this component`のほうが文法正しそう

2024-03-31 09:31 UTC, Sayamame-beans requested changes
github sponsors とか boothとか、[]で囲ってあるやつのcapitalize確認してなかったなぁとなっています…どうしよう

2024-03-31 09:31 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +## `AAO Merge Skinned Mesh`コンポーネントを使用すると、マテリアルプロパティに対するアニメーションが競合する {#material-animations-conflict-when-using-aao-merge-skinned-mesh-component}
```suggestion
## `AAO Merge Skinned Mesh`コンポーネントを使用すると、マテリアルプロパティに対するアニメーションが競合する {#material-property-animations-conflict-when-using-aao-merge-skinned-mesh-component}
```

2024-03-31 09:31 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +`AAO Merge Skinned Mesh` component will merge material sots of the mesh with same materials by default.
```suggestion
`AAO Merge Skinned Mesh` component will merge material slots using the same material of the merge target meshes by default.
```

2024-03-31 09:31 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +This will merge material slots which is animated.
```suggestion
This will also merge animated material slots.
```

2024-03-31 09:31 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +`AAO Merge Skinned Mesh`コンポーネントは、デフォルトで同じマテリアルを持つメッシュのマテリアルスロットを統合します。
```suggestion
`AAO Merge Skinned Mesh`コンポーネントは、統合対象のメッシュで同じマテリアルを使用しているマテリアルスロットをデフォルトで統合します。
```
mergeSMRのdocsに寄せ

2024-03-31 09:31 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +これにはアニメーションされているマテリアルスロットも含まれます。
```suggestion
これにはアニメーションされるマテリアルスロットも含まれます。
```

2024-03-31 09:31 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +アニメーションによってマテリアルが異なるように置き換えられる場合は、`AAO Merge Skinned Mesh`コンポーネントの`Merge Materials`の`Merge`をオフにしてください。
```suggestion
アニメーションによってそれぞれのマテリアルを別のものに置き換える場合は、`AAO Merge Skinned Mesh`コンポーネントの`マテリアルの統合`の`統合する`をオフにしてください。
```
i18n

2024-03-31 10:35 UTC, Sayamame-beans commented
同じキーが2つ…? (en未確認)
https://github.com/anatawa12/AvatarOptimizer/blob/ae09b65fec2c1785152c0c8a1bf8028d981e278b/Localization/ja-jp.po#L96-L100

2024-03-31 10:56 UTC, Sayamame-beans requested changes

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +いくつかのケースでは、そのバグが多くのユースケースに影響を与えないため、バグを一時的に放置することがあります。\
```suggestion
その動作を修正することで多くのユーザーに影響を与えてしまわないように、いくつかのユースケースに対しては修正を一時的に見合わせることがありますが、その動作は他のコンポーネントでは考慮されないかもしれません。
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +ただし、バグの振る舞いは他のコンポーネントには考慮されないかもしれません。
```suggestion
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +例えば、1.7.x以前のMergeSkinnedMeshはBlendShapeをマージします。\
```suggestion
例えば、1.7.x以前の`AAO Merge Skinned Mesh`コンポーネントは同名のBlendShapeを統合します。\
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +これは、個別にアニメーションできるBlendShapesをマージすると動作が変わってしまうため、バグとして扱われます。\
```suggestion
BlendShapesを統合すると、そのBlendShapeに対するアニメーションによる動作が変わってしまうため、これはバグとして扱われます。\
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +このバグを使用して、Skinned Mesh RendererのBlendShapeアニメーションを別のSkinned Mesh Rendererと同期させることができます。\
```suggestion
このバグを使用して、あるSkinned Mesh RendererのBlendShapeに対するアニメーションを、別のSkinned Mesh RendererのBlendShapeに対しても同時に作用させることができます。\
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +ただし、これはサポートされていない動作であり、他のコンポーネントが動作を壊すかもしれません。\
```suggestion
しかし、これはサポートされていない動作であり、他のコンポーネントが動作を壊すかもしれません。\
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +例えば、Trace and Optimizeの`BlendShapeを自動的に固定・除去する`は、Merge Skinned Meshによって動くようになる可能性のあるBlendShapeであっても、固定・除去します。
```suggestion
例えば、`AAO Trace and Optimize`コンポーネントの`BlendShapeを自動的に固定・除去する`は、`AAO Merge Skinned Mesh`コンポーネントによって動くようになる可能性があるBlendShapeであっても、固定・除去します。
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +Avatar Optimizerはバージョン管理に[セマンティックバージョニング]を使用し、コンポーネントの振る舞いには主にセマンティックバージョニングのルールを適用しています。
```suggestion
Avatar Optimizerはバージョン管理に[セマンティックバージョニング]を使用しており、コンポーネントの振る舞いには主にセマンティックバージョニングのルールを適用しています。
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +既に追加されたコンポーネントの振る舞いは、同じメジャーバージョンで変更されないことを保証します。\
```suggestion
すなわち、既に追加されたコンポーネントの振る舞いは、同じメジャーバージョン内では変更されないことが保証されます。\
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +ただし、既存のコンポーネントタイプに新しい機能を追加することがあり、新しく追加されたコンポーネントの振る舞いが変更されることがあります。
ここ解説欲しいです(理解出来なかった)

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +一部のバグでは、そのバグを修正するとコンポーネントの振る舞いが大幅に変更されることがあります。
```suggestion
一部のバグでは、そのバグを修正することによってコンポーネントの振る舞いが大幅に変更される場合があります。
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +そのようなバグを修正するためには、新しい振る舞いを有効にする新しいフラグを追加します。\
```suggestion
そのような場合には、新たな振る舞いを有効化するためのオプションを追加します。\
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +既存のコンポーネントではフラグをデフォルトで無効にしておくことで、既存のコンポーネントの振る舞いを維持し、
```suggestion
アバターに既に付いているコンポーネントでは、このオプションをデフォルトで無効にすることで以前までの振る舞いを維持し、
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +新しく追加されたコンポーネントではフラグをデフォルトで有効にすることで、新しいコンポーネントのバグを修正します。
```suggestion
アバターに新たに追加されたコンポーネントでは、このオプションをデフォルトで有効にすることで、バグが修正された新しい動作を行います。
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +この振る舞いの安定性にはいくつかの例外があります。
```suggestion
こういった、振る舞い維持の対処においてはいくつかの例外があります。
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +  たとえば、Trace and OptimizeのAdvanced Optionsはいつでも変更される可能性があります。
```suggestion
  例えば、`AAO Trace and Optimize`コンポーネントの`Advanced Options`は変更される可能性が常にあります。
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +- 実験的な機能としてマークされた機能は、上記のルールに従うことが保証されません。
```suggestion
- 実験的な機能としてマークされている機能は、上記のルールに従うことが保証されません。
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +- `Trace and Optimize`コンポーネントの振る舞いは、新しい最適化を実装することで変更される可能性があります。\
```suggestion
- `AAO Trace and Optimize`コンポーネントの振る舞いは、新しい最適化を実装することによって変更される可能性があります。\
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +  ただし、`Trace and Optimize`コンポーネントのデフォルト設定は、アバターの振る舞いに影響を与えないため、変更はアバターに影響を与えません。
```suggestion
  ただし、`AAO Trace and Optimize`コンポーネントのデフォルト設定では、アバターの振る舞いや見た目に影響を与えないようにしているため、この変更はアバターに一切影響を与えないはずです。
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +  (もし`Trace and Optimize`コンポーネントによってアバターの振る舞いが変わった場合は、バグとして報告してください。)
```suggestion
  (もし`AAO Trace and Optimize`コンポーネントによってアバターの振る舞いや見た目が変わってしまった場合は、バグとして[GitHub issues]や[misskey][fediverse] (mastodon)、[twitter]などから報告をお願いします。)
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +[セマンティックバージョニング]: https://semver.org/lang/ja/spec/v2.0.0.html
```suggestion
[セマンティックバージョニング]: https://semver.org/lang/ja/spec/v2.0.0.html
[GitHub issues]: https://github.com/anatawa12/AvatarOptimizer/issues/new/choose
[fediverse]: https://misskey.niri.la/@anatawa12
[twitter]: https://twitter.com/anatawa12_vrc
```

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +  (もし`Trace and Optimize`コンポーネントによってアバターの振る舞いが変わった場合は、バグとして報告してください。)
faqから持ってきました

2024-03-31 10:56 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
T&Oの項目を上の方に上げません? (enも同様)

2024-03-31 10:57 UTC, Sayamame-beans commented
(https://github.com/anatawa12/AvatarOptimizer/pull/961#issuecomment-2028633365 はanatawaさんにどうなってるか聞かないと分かんないです…)

2024-03-31 11:13 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.ja.md
> +いくつかのケースでは、そのバグが多くのユースケースに影響を与えないため、バグを一時的に放置することがあります。\
言いたいこと逆ですね。(想定されている)多くのユースケースではそのバグが影響ないので、バグを放置するって感じです

2024-03-31 11:17 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.ja.md
> +ただし、既存のコンポーネントタイプに新しい機能を追加することがあり、新しく追加されたコンポーネントの振る舞いが変更されることがあります。
例えばMergeSkinnedMeshにBlendShapeをマージしないオプション (またはマージするオプション)をつけて、Add Component時にはマージしないようになるけど、旧バージョンでAdd Componentしたやつはそのままマージするように動作するって感じ

2024-03-31 11:18 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.ja.md
> +この振る舞いの安定性にはいくつかの例外があります。
```suggestion
こういった、振る舞いの維持においてはいくつかの例外があります。
```

"維持の対処"、違和感

2024-03-31 11:21 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +いくつかのケースでは、そのバグが多くのユースケースに影響を与えないため、バグを一時的に放置することがあります。\
ああ、なるほど

2024-03-31 11:27 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +既に追加されたコンポーネントの振る舞いは、同じメジャーバージョンで変更されないことを保証します。\
```suggestion
すなわち、アバターに既に付いているコンポーネントの振る舞いは、同じメジャーバージョン内では変更されないことが保証されます。\
```

2024-03-31 11:30 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +ただし、既存のコンポーネントタイプに新しい機能を追加することがあり、新しく追加されたコンポーネントの振る舞いが変更されることがあります。
```suggestion
既存のコンポーネントに対して新しい機能が追加された場合には、それ以降にアバターに新たに追加されたコンポーネントの振る舞いのみ、それ以前のものから変更されることがあります。
```

2024-03-31 11:32 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +このツールは、外観をあまり変えずにアバターのパフォーマンスを最適化するのを助けるために設計されています。
```suggestion
このツールは、アバターの見た目を殆ど変化させることなく、簡単にアバターのパフォーマンスを最適化することを目的として設計されています。
```
これでどうだ

2024-03-31 11:39 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +  (もし`Trace and Optimize`コンポーネントによってアバターの振る舞いが変わった場合は、バグとして報告してください。)
あ～～…

じゃあ、この1つ前の、"～与えないはずです。"までで止めて、
```suggestion

これら以外で不自然な動作や奇妙な動作などに遭遇した場合は、まずfaqをご覧ください。
```
みたいな感じでfaqに飛ばすとか? (文章あんまり考えられてない)

2024-03-31 12:06 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.ja.md
> +  (もし`Trace and Optimize`コンポーネントによってアバターの振る舞いが変わった場合は、バグとして報告してください。)
faqに飛ばすこと自体は良さそう。faq、リンクしたいね

2024-03-31 12:11 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
忘れてた。やります

2024-03-31 12:14 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
fd673c2e530df9030896095e3e15fa56e2d6daf3

2024-03-31 12:17 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.ja.md
> +  (もし`Trace and Optimize`コンポーネントによってアバターの振る舞いが変わった場合は、バグとして報告してください。)
faq側に追記いるかと思ったけどなくても良さそうかな

2024-03-31 12:43 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-physbone/index.md
> +The added PhysBone transform will not be swayed by PhysBone so this can be a bug of the VRChat Performance Rank System.
確かに

2024-03-31 12:43 UTC, Sayamame-beans commented on .docs/content/docs/reference/merge-physbone/index.md
> +The added PhysBone transform will not be swayed by PhysBone so this can be a bug of the VRChat Performance Rank System.
直しました

2024-03-31 13:06 UTC, Sayamame-beans requested changes
re-review

2024-03-31 13:06 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.ja.md
> +この問題は既知のバグであり、現時点では競合してしまう仕様です。
```suggestion
この問題は既知のバグであり、現時点では競合してしまう仕様です。

```

2024-03-31 13:06 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +Here is the list of frequently asked questions about AvatarOptimizer.
```suggestion
Here is the list of frequently asked questions about Avatar Optimizer.
```

2024-03-31 13:06 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +If the behavior of the avatar is changed when using `AAO Trace and Optimize` component, it is always a bug unless you depend on bugs in other components of AvatarOptimizer.
```suggestion
If the behavior of the avatar is changed when using `AAO Trace and Optimize` component, it is always a bug unless you depend on bugs in other components of Avatar Optimizer.
```

2024-03-31 13:06 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +This problem is often due to forgetting to specify the `Anchor Override` of the merged meshes.
```suggestion
This problem is often due to forgetting to specify the `Anchor Override` of the merged meshes.\
```

2024-03-31 13:06 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +
```suggestion
```

2024-03-31 13:06 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +
```suggestion
```

2024-03-31 13:16 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.ja.md
> +  (もし`Trace and Optimize`コンポーネントによってアバターの振る舞いが変わった場合は、バグとして報告してください。)
```suggestion

これら以外で不自然な動作や奇妙な動作などに遭遇した場合は、まず[faq]をご覧ください。
```

2024-03-31 13:16 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.ja.md
> +[セマンティックバージョニング]: https://semver.org/lang/ja/spec/v2.0.0.html
```suggestion
[セマンティックバージョニング]: https://semver.org/lang/ja/spec/v2.0.0.html
[faq]: ../faq/
```

2024-03-31 13:20 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +[セマンティックバージョニング]: https://semver.org/lang/ja/spec/v2.0.0.html
```suggestion
[セマンティックバージョニング]: https://semver.org/lang/ja/spec/v2.0.0.html
[FAQ]: ../faq/
```

2024-03-31 13:20 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
> +  (もし`Trace and Optimize`コンポーネントによってアバターの振る舞いが変わった場合は、バグとして報告してください。)
```suggestion

これら以外で不自然な動作や奇妙な動作などに遭遇した場合は、まず[FAQ]をご覧ください。
```

2024-03-31 13:47 UTC, Sayamame-beans requested changes
might be last review?

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +This page explains the basic concepts of Avatar Optimizer.
```suggestion
This page describes the basic concepts of Avatar Optimizer.
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +This tool is initially designed for VRChat avatars, but it might be used for other Avatars supported by [NDMF].
```suggestion
This tool is initially designed for VRChat avatars, but it might be usable for other Avatars supported by [NDMF].
```
かもしれない?

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +Non-VRChat avatar support is completely community-based and may not be supported by the Avatar Optimizer team.
```suggestion
Non-VRChat avatar support is completely community-based and may not be supported by Avatar Optimizer dev team.
```
ここのtheは必要? (必要かもしれない)

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +This tool is not designed to make change behavior of the avatar.
```suggestion
Therefore, it is not intended to make changes of the avatar behavior.
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +All non-configured changes in the behavior of the avatar is treated as a bug, even if it might be useful some use cases.\
```suggestion
All non-configured changes in the avatar behavior is treated as a bug, even if it might be useful in some use cases.\
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +In some cases, we may put off the bug since it does not affects much for most use cases.\
```suggestion
In some cases, we may put off the bug since it does not affect so much for most use cases.\
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +For example, MergeSkinnedMesh in 1.7.x or older merges BlendShapes.\
```suggestion
For example, `AAO Merge Skinned Mesh` component in 1.7.x or older merges BlendShapes which have the same name.\
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +This behavior is treated as bug since this makes impossibe to animate the BlendShapes separately.\
```suggestion
This behavior is treated as a bug since this makes impossible to animate them separately.\
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +We may use this bug to sync the blendShape animation of an Skinned Mesh Renderer with another Skinned Mesh Renderer.\
```suggestion
You may use this bug to sync the BlendShape animation of an Skinned Mesh Renderer with one of another Skinned Mesh Renderer.\
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +For example, `Automatically Freeze BlendShape` in Trace and Optimize will freezes the blendShapes that might be merged by Merge Skinned Mesh.
```suggestion
For example, `Automatically Freeze BlendShape` in `AAO Trace and Optimize` component will freezes the BlendShapes which might be animated with this buggy behavior by being merged by `AAO Merge Skinned Mesh` component.
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +The Avatar Optimizer uses the [Semantic Versioning] for versioning and mostly applies the rules of Semantic Versioning to the behavior of the components.
```suggestion
Avatar Optimizer uses the [Semantic Versioning] for versioning and mostly applies the rules of Semantic Versioning to the behavior of the components.
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +However, we may add new features for existing component types and behavior of newly added components may be changed.
```suggestion
However, we may add new features for existing component and the behavior of newly added components may be changed.
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +In some bugs, fixing the bug may change the behavior of the component widely.\
```suggestion
In some bugs, fixing them may change the behavior of the component widely.\
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +To fix such bugs, we usually add new flag to enable the new behavior.\
flag or option

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +  For example, Advanced Options on the Trace and Optimize might be changed in any version.
```suggestion
  For example, `Advanced Options` on `AAO Trace and Optimize` component might be changed in any version.
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +- The behavior of `Trace and Optimize` component might be changed by implementing new optimization.\
```suggestion
- The behavior of `AAO Trace and Optimize` component might be changed by implementing new optimization.\
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +  However, the default settings of `Trace and Optimize` component will never change the behavior of your avatar, so changes must not affect the avatar.
```suggestion
  However, the default settings of `AAO Trace and Optimize` component will never change the behavior and appearance of your avatar, so changes must not affect the avatar.
```

2024-03-31 13:47 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +  However, the default settings of `Trace and Optimize` component will never change the behavior of your avatar, so changes must not affect the avatar.
appearanceもbehaviorの一種として見做してます? それならand appearanceは要らないです

2024-03-31 13:53 UTC, Sayamame-beans requested changes
this should be the last review

2024-03-31 13:53 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +[Semantic Versioning]: https://semver.org/
```suggestion
[Semantic Versioning]: https://semver.org/
[FAQ]: ../faq/
```

2024-03-31 13:53 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +There are few exception for this behavior stability.
```suggestion
There are few exceptions for this behavior stability.
```

2024-03-31 13:53 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +  (If your avatar behavior is changed by the `Trace and Optimize` component, please report it as a bug.)
```suggestion

When you encountered any unnatural or strange behavior other than these exceptions, please see [FAQ] first.
```

2024-03-31 13:55 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.md
> +Non-VRChat avatar support is completely community-based and may not be supported by the Avatar Optimizer team.
the多分あったほうがいいと思う
```suggestion
Non-VRChat avatar support is completely community-based and may not be supported by the Avatar Optimizer dev team.
```

2024-03-31 13:59 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.md
> +However, we may add new features for existing component types and behavior of newly added components may be changed.
"existing component"というと "already added components" のこと指してると勘違いされる気がしてtypesをつけてるので何かしらしたい

2024-03-31 14:00 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.md
> +To fix such bugs, we usually add new flag to enable the new behavior.\
技術屋としてはflagがしっくり来てる

2024-03-31 14:01 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +However, we may add new features for existing component types and behavior of newly added components may be changed.
component kindが存在するので紛らわしい気がした

2024-03-31 14:01 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.md
> +  However, the default settings of `Trace and Optimize` component will never change the behavior of your avatar, so changes must not affect the avatar.
別途書いたほうが明確ではあるので書いていいと思う。他の場所で behaviorでappearanceを含む意味で書いてること結構あると思うけど

2024-03-31 14:02 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +However, we may add new features for existing component types and behavior of newly added components may be changed.
already implemented component

2024-03-31 14:02 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +However, we may add new features for existing component types and behavior of newly added components may be changed.
とか?

2024-03-31 14:04 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.md
> +  However, the default settings of `Trace and Optimize` component will never change the behavior of your avatar, so changes must not affect the avatar.
じゃあFAQの方のT&Oのところもbehaviorだけになってたので、and appearance足さないとですね(タイトルと内容で2箇所ぐらいはあるはず?)
日本語の方には入ってるはず

2024-03-31 14:06 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.md
> +However, we may add new features for existing component types and behavior of newly added components may be changed.
"already implemented component"、よさそう

2024-03-31 14:11 UTC, anatawa12 commented on .docs/content/docs/basic-consept/index.md
> +However, we may add new features for existing component types and behavior of newly added components may be changed.
```suggestion
However, we may add new features for already implemented component and the behavior of newly added components may be changed.
```

2024-03-31 14:18 UTC, Sayamame-beans commented on .docs/content/docs/basic-consept/index.ja.md
(多分大丈夫だと思いますが)ディレクトリ名のことです

2024-04-01 03:12 UTC, Sayamame-beans requested changes
final last review?

2024-04-01 03:12 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +## The behavior of the avatar is changed when using `AAO Trace and Optimize` component {#avatar-behavior-changed-when-using-aao-trace-and-optimize-component}
```suggestion
## The behavior or appearance of the avatar is changed when using `AAO Trace and Optimize` component {#avatar-behavior-changed-when-using-aao-trace-and-optimize-component}
```
アンカーも変える?

2024-04-01 03:12 UTC, Sayamame-beans commented on .docs/content/docs/faq/index.md
> +If the behavior of the avatar is changed when using `AAO Trace and Optimize` component, it is always a bug unless you depend on bugs in other components of Avatar Optimizer.
```suggestion
If the behavior or appearance of the avatar is changed when using `AAO Trace and Optimize` component, it is always a bug unless you depend on bugs in other components of Avatar Optimizer.
```

2024-04-01 04:08 UTC, anatawa12 commented on .docs/content/docs/basic-concept/index.md
> +By making the flag disabled by default for existing components, we keep the behavior of the existing components and by making the flag enabled by default for newly added components, we fix the bug fo
両方揃えたほうが良さそうかな

2024-04-01 04:08 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +## The behavior of the avatar is changed when using `AAO Trace and Optimize` component {#avatar-behavior-changed-when-using-aao-trace-and-optimize-component}
アンカー、テキストに合わせてるのでアンカーも変えたい

2024-04-01 04:43 UTC, anatawa12 commented on .docs/content/docs/faq/index.md
> +## The behavior of the avatar is changed when using `AAO Trace and Optimize` component {#avatar-behavior-changed-when-using-aao-trace-and-optimize-component}
```suggestion
## The behavior or appearance of the avatar is changed when using `AAO Trace and Optimize` component {#avatar-behavior-or-appearance-changed-when-using-aao-trace-and-optimize-component}
```

2024-04-01 04:44 UTC, anatawa12 commented on .docs/content/docs/faq/index.ja.md
> +## `AAO Trace and Optimize`コンポーネントを使用すると、アバターの振る舞いや見た目が変わる {#avatar-behavior-changed-when-using-aao-trace-and-optimize-component}
```suggestion
## `AAO Trace and Optimize`コンポーネントを使用すると、アバターの振る舞いや見た目が変わる {#avatar-behavior-or-appearance-changed-when-using-aao-trace-and-optimize-component}
```

2024-04-01 04:44 UTC, anatawa12 commented on .docs/content/docs/basic-concept/index.md
> +By making the flag disabled by default for existing components, we keep the behavior of the existing components and by making the flag enabled by default for newly added components, we fix the bug fo
```suggestion
By making the flag disabled by default for already added components, we keep the behavior of the existing components and by making the flag enabled by default for newly added components, we fix the bug for newly added components.
```

2024-04-01 05:10 UTC, Sayamame-beans commented on .docs/content/docs/basic-concept/index.md
> +By making the flag disabled by default for existing components, we keep the behavior of the existing components and by making the flag enabled by default for newly added components, we fix the bug fo
であれば、
```suggestion
By making the flag disabled by default for already added components, we keep the behavior of already added components and by making the flag enabled by default for newly added components, we fix the bug for newly added components.
```

2024-04-01 06:07 UTC, Sayamame-beans approved these changes
LGTM!

2024-04-01 06:08 UTC, merged