feat(merge-direct-blend-tree): merge non Direct BlendTree
anatawa12/AvatarOptimizer pull request #980
Opened 2024-04-03 11:05 UTC by nekobako

Fixes #979 です

2024-04-03 15:12 UTC, anatawa12 requested changes
ほかは概ね良さそうです

ありがとうございます

2024-04-03 15:35 UTC, nekobako commented on Internal/AnimatorOptimizer/MergeDirectBlendTree.cs
> +            var alwaysOneParameter = $"AlwaysOne_{Guid.NewGuid()}";
先頭に `AAO_` を付けました！

2024-04-04 02:28 UTC, anatawa12 approved these changes
LGTM ありがとうございます！

2024-04-04 02:28 UTC, merged

2024-04-04 11:04 UTC, Sayamame-beans commented
@anatawa12 Merge"Direct"BlendTreeじゃなくなっちゃいませんか? (コンポーネント名 及び prereleaseでないchangelog など)

2024-04-04 11:33 UTC, anatawa12 commented
あー直さないといけないですね