Support bool parameters in Entry/Exit to BlendTree optimization
anatawa12/AvatarOptimizer pull request #982
Opened 2024-04-03 11:10 UTC by nekobako

Fixes #981 です

2024-04-03 17:34 UTC, anatawa12 requested changes
ありがとうございます

2024-04-04 14:08 UTC, nekobako commented on Internal/AnimatorOptimizer/EntryExitToBlendTree.cs
If と IfNot の case を分けてそれぞれ書きました。

2024-04-04 14:11 UTC, nekobako commented on Internal/AnimatorOptimizer/EntryExitToBlendTree.cs
> +                states.Add((value.IntValue ?? (value.BoolValue.Value ? 1 : 0), state.motion));
-epsilon, 0, epsilon の BlendTree になるようにしました。

2024-04-04 14:19 UTC, nekobako commented
conventional commit と CHANGELOG のチェックに引っかかってしまったのですがどう対応すればよいでしょうか・・？

2024-04-04 14:58 UTC, anatawa12 commented
> conventional commit と CHANGELOG のチェックに引っかかってしまったのですがどう対応すればよいでしょうか・・？

Actionsシステムのバグのようだったので再実行しました

2024-04-04 15:01 UTC, anatawa12 approved these changes
コード自体は良さそうです

テストは未確認ですすみません

2024-04-04 15:10 UTC, nekobako commented
ありがとうございます。

2024-04-04 17:03 UTC, anatawa12 approved these changes
テストも良さそうですねありがとうございます

2024-04-04 17:03 UTC, merged