feat: Remove mesh by mask
anatawa12/AvatarOptimizer pull request #998
Opened 2024-04-09 15:15 UTC by anatawa12

Fixes #924
Related: #834 (真っ白/黒テクスチャで消せる)

2024-04-10 11:11 UTC, Sayamame-beans requested changes
部分的

2024-04-10 11:11 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "このコンポーネントはMerge Skinned Meshコンポーネントに対応していません。Merge Skinned Meshの統合対象に追加してください。"
```suggestion
msgstr "このコンポーネントはMerge Skinned Meshコンポーネントに対応していません。\n
そのため、このコンポーネントは統合先のメッシュではなく統合対象のメッシュに追加してください。"
```
keyが謎
MergeSMRは`Source Edit Skinned Mesh Component`なので、NoSource～というのは何故…?
このNoは併用駄目だよの意味のNo?

2024-04-10 11:11 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "マスクテクスチャー"
```suggestion
msgstr "マスクテクスチャ"
```

2024-04-10 11:11 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "マテリアルスロット {0} 有効"
```suggestion
msgstr "{0}番のマテリアルスロットに適用"
```

2024-04-10 11:11 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "マスクが設定されていません"
```suggestion
msgstr "マスクテクスチャが設定されていません。"
```

2024-04-10 11:11 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "マスクテクスチャが読み取り可能ではありません"
```suggestion
msgstr "マスクテクスチャが読み取り可能ではありません。"
```

2024-04-10 11:11 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "マスクテクスチャのRead/Write Enabledが有効になっていることを確認してください"
```suggestion
msgstr "マスクテクスチャのRead/Write Enabledが有効になっていることを確認してください。"
```

2024-04-10 11:11 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "未知のモードが指定されています"
```suggestion
msgstr "未知のモードが指定されています。"
```

2024-04-10 11:11 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "MeshがSkinned Mesh Rendererに設定されていません"
```suggestion
msgstr "Skinned Mesh RendererにMeshが設定されていません。"
```

2024-04-10 12:40 UTC, anatawa12 commented on .docs/content/docs/reference/remove-mesh-by-mask/index.ja.md
> +このコンポーネントを使用すると、アルファマスク用のテクスチャや、[gatosyocoraさんのMeshDeleterWithTexture]用のマスクテクスチャーを簡単に利用することができます。
たしかに`MeshDeleterWithTexture`だけでもいいかも

2024-04-10 12:41 UTC, anatawa12 commented on .docs/content/docs/reference/remove-mesh-by-mask/index.ja.md
> +メッシュのマテリアルスロットの一覧が表示されます。
です。とりあえず。
Enabledのいちとか考えるのが少し大変だったので

2024-04-10 12:43 UTC, anatawa12 commented on Localization/ja-jp.po
> +msgstr "このコンポーネントはMerge Skinned Meshコンポーネントに対応していません。Merge Skinned Meshの統合対象に追加してください。"
> このNoは併用駄目だよの意味のNo?

はい。

2024-04-10 12:52 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "このコンポーネントはMerge Skinned Meshコンポーネントに対応していません。Merge Skinned Meshの統合対象に追加してください。"
無い意味のNoかと思って混乱してました

2024-04-13 10:18 UTC, Sayamame-beans requested changes

2024-04-13 10:18 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +"指定されたマスクによって動かされる頂点とそのポリゴンを削除します\n"
普通におかしかったけど気付いてなかった()
```suggestion
"マスクテクスチャで指定した範囲のポリゴンを削除します。\n"
```

2024-04-13 10:18 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +"すべてのポリゴンが削除される場合にはそのSubMeshが削除されます"
```suggestion
"すべてのポリゴンが削除される場合は、そのSubMeshごと削除します。"
```
submeshって言葉入れても大丈夫かな…ってなったけど(他で使って無さそう)、他に適切な表現無さそうなのでヨシ

2024-04-13 10:18 UTC, Sayamame-beans commented on Localization/en-us.po
> +"Remove vertices that are not masked by the specified mask texture.\n"
```suggestion
"Remove some polygons in any area specified by mask textures.\n"
```

2024-04-13 10:18 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +"すべてのポリゴンが削除される場合にはそのSubMeshが削除されます"
ところで日本語と英語で書いてある内容が違う…

2024-04-13 10:18 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Material Slot {0} Enabled"
```suggestion
msgstr "Apply to Material Slot {0}"
```
日本語にそろえてみた

2024-04-13 10:18 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Mask Texture is not readable"
```suggestion
msgstr "Mask Texture is not readable."
```

2024-04-13 10:18 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Mask Texture is not set"
```suggestion
msgstr "Mask Texture is not set."
```

2024-04-13 10:18 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "Unknown Mode is specified."
```suggestion
msgstr "Unknown Remove Mode is specified."
```

2024-04-13 10:18 UTC, Sayamame-beans commented on Localization/ja-jp.po
> +msgstr "未知のモードが指定されています"
ちょっと変えた

2024-04-13 10:18 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "No Mesh is specified to Skinned Mesh Renderer"
```suggestion
msgstr "No Mesh is specified to the Skinned Mesh Renderer."
```

2024-04-13 10:18 UTC, Sayamame-beans commented on Localization/en-us.po
> +msgstr "The component does not support Merge Skinned Mesh component. Please add to source renderers of MergeS kinned Mesh."
```suggestion
msgstr "This component does not support Merge Skinned Mesh component.\n"
"So, please add this component to the source renderers of Merge Skinned Mesh."
```

2024-04-13 11:26 UTC, anatawa12 commented on Localization/en-us.po
> +"Mask texture should be readable and have alpha channel."
完全に気づいてなかったけどこの英語分謎だな。github copolotで誤って入力したかも。
```suggestion
```

2024-04-13 11:26 UTC, anatawa12 commented on Localization/ja-jp.po
> +"すべてのポリゴンが削除される場合にはそのSubMeshが削除されます"
そもそもポリゴンがないSubMesh削除は別コンポーネントかTrace and Optimizeに持っていくことにします

```suggestion
```

2024-04-13 16:14 UTC, anatawa12 commented on Localization/en-us.po
> +"Remove some polygons in any area specified by mask textures.\n"
```suggestion
msgstr "Remove some polygons in any area specified by mask textures."
```

2024-04-13 16:14 UTC, anatawa12 commented on Localization/ja-jp.po
> +"マスクテクスチャで指定した範囲のポリゴンを削除します。\n"
```suggestion
msgstr "マスクテクスチャで指定した範囲のポリゴンを削除します。"
```

2024-04-13 16:15 UTC, Sayamame-beans approved these changes

2024-04-13 16:20 UTC, merged